### ISSUE TITLE
[Feature Request] MITRE Caldera

### ISSUE THREAD

**Issue by ZachTheSplunker** [splunk/attack_range#1004]
[MITRE Caldera](https://caldera.mitre.org/) is a scalable, automated adversary emulation platform. The UI makes it trivial to plan and launch attacks against target machines. It would be great to incorporate this in Splunk Attack Range!

**Comment by P4T12ICK** [comment]
Hi Zach, we had Mitre Caldera integrated into Attack Range in the past, but it was very unstable during that time. I didn't test the latest version.

**Comment by P4T12ICK** [comment]
I just saw your feature request. This is awesome. Let me review it.
