### ISSUE TITLE
Ansible uses Windows 2016 even if Windows 2019/2022 is selected

### ISSUE THREAD

**Issue by pschivo** [splunk/attack_range#1009]
I've just created a new instance of Attack Range, downloading latest release, and this behaviour remains from older versions. It doesn't matter if you choose 1 or 2 Windows machines, the thing is even if you choose Windows 2019/2022 as it asks for, it installs Windows 2016 for all of them.

attack_range.yml:

general:
  cloud_provider: local
  attack_range_password: Aj81gt59!
local: {}
windows_servers:
- hostname: ar-win-dc
  windows_image: windows-server-2019
  create_domain: '1'
  install_red_team_tools: '1'
  bad_blood: '1'
  install_caldera_agent: '1'
- hostname: ar-win-2
  windows_image: windows-server-2022
  join_domain: '1'
  install_red_team_tools: '1'
  install_caldera_agent: '1'
linux_servers:
- hostname: ar-linux
  install_caldera_agent: '1'

attack_range.py resume:

==> ar-win-attack-range-key-pair-ar-0: **Checking if box 'd1vious/windows2016' version '1.0' is up to date...**
==> ar-win-attack-range-key-pair-ar-0: Clearing any previously set forwarded ports...
==> ar-win-attack-range-key-pair-ar-0: Fixed port collision for 3389 => 3389. Now on port 2200.
==> ar-win-attack-range-key-pair-ar-0: Fixed port collision for 22 => 2222. Now on port 2201.
==> ar-win-attack-range-key-pair-ar-0: Clearing any previously set network interfaces...
==> ar-win-attack-range-key-pair-ar-0: Preparing network interfaces based on configuration...
    ar-win-attack-range-key-pair-ar-0: Adapter 1: nat
    ar-win-attack-range-key-pair-ar-0: Adapter 2: hostonly
==> ar-win-attack-range-key-pair-ar-0: Forwarding ports...
    ar-win-attack-range-key-pair-ar-0: 3389 (guest) => 2200 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-0: 22 (guest) => 2201 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-0: 5985 (guest) => 6985 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-0: 3389 (guest) => 5389 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-0: 5985 (guest) => 55985 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-0: 5986 (guest) => 55986 (host) (adapter 1)
==> ar-win-attack-range-key-pair-ar-0: Running 'pre-boot' VM customizations...
==> ar-win-attack-range-key-pair-ar-0: Booting VM...
==> ar-win-attack-range-key-pair-ar-0: Waiting for machine to boot. This may take a few minutes...
    ar-win-attack-range-key-pair-ar-0: WinRM address: 127.0.0.1:6985
    ar-win-attack-range-key-pair-ar-0: WinRM username: vagrant
    ar-win-attack-range-key-pair-ar-0: WinRM execution_time_limit: PT2H
    ar-win-attack-range-key-pair-ar-0: WinRM transport: plaintext
==> ar-win-attack-range-key-pair-ar-0: Machine booted and ready!
==> ar-win-attack-range-key-pair-ar-0: Checking for guest additions in VM...
    ar-win-attack-range-key-pair-ar-0: The guest additions on this VM do not match the installed version of
    ar-win-attack-range-key-pair-ar-0: VirtualBox! In most cases this is fine, but in rare cases it can
    ar-win-attack-range-key-pair-ar-0: prevent things such as shared folders from working properly. If you see
    ar-win-attack-range-key-pair-ar-0: shared folder errors, please make sure the guest additions within the
    ar-win-attack-range-key-pair-ar-0: virtual machine match the version of VirtualBox you have installed on
    ar-win-attack-range-key-pair-ar-0: your host and reload your VM.
    ar-win-attack-range-key-pair-ar-0:
    ar-win-attack-range-key-pair-ar-0: Guest Additions Version: 5.2.16
    ar-win-attack-range-key-pair-ar-0: VirtualBox Version: 7.1
==> ar-win-attack-range-key-pair-ar-0: Setting hostname...
==> ar-win-attack-range-key-pair-ar-0: Configuring and enabling network interfaces...
==> ar-win-attack-range-key-pair-ar-0: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> ar-win-attack-range-key-pair-ar-0: flag to force provisioning. Provisioners marked to run always will still run.
==> ar-win-attack-range-key-pair-ar-0: Running provisioner: file...
    ar-win-attack-range-key-pair-ar-0: windows_vars_0.json => /tmp/windows_vars_0.json
==> ar-win-attack-range-key-pair-ar-1: Importing base box 'd1vious/windows2016'...
==> ar-win-attack-range-key-pair-ar-1: Matching MAC address for NAT networking...
==> ar-win-attack-range-key-pair-ar-1: **Checking if box 'd1vious/windows2016' version '1.0' is up to date...**
==> ar-win-attack-range-key-pair-ar-1: Setting the name of the VM: ar-win-2
==> ar-win-attack-range-key-pair-ar-1: Fixed port collision for 3389 => 2200. Now on port 2202.
==> ar-win-attack-range-key-pair-ar-1: Fixed port collision for 22 => 2201. Now on port 2203.
==> ar-win-attack-range-key-pair-ar-1: Fixed port collision for 5985 => 55985. Now on port 2204.
==> ar-win-attack-range-key-pair-ar-1: Fixed port collision for 5986 => 55986. Now on port 2205.
==> ar-win-attack-range-key-pair-ar-1: Clearing any previously set network interfaces...
==> ar-win-attack-range-key-pair-ar-1: Preparing network interfaces based on configuration...
    ar-win-attack-range-key-pair-ar-1: Adapter 1: nat
    ar-win-attack-range-key-pair-ar-1: Adapter 2: hostonly
==> ar-win-attack-range-key-pair-ar-1: Forwarding ports...
    ar-win-attack-range-key-pair-ar-1: 3389 (guest) => 2202 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-1: 22 (guest) => 2203 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-1: 5985 (guest) => 6986 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-1: 3389 (guest) => 5390 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-1: 5985 (guest) => 2204 (host) (adapter 1)
    ar-win-attack-range-key-pair-ar-1: 5986 (guest) => 2205 (host) (adapter 1)
==> ar-win-attack-range-key-pair-ar-1: Running 'pre-boot' VM customizations...
==> ar-win-attack-range-key-pair-ar-1: Booting VM...
==> ar-win-attack-range-key-pair-ar-1: Waiting for machine to boot. This may take a few minutes...
    ar-win-attack-range-key-pair-ar-1: WinRM address: 127.0.0.1:6986
    ar-win-attack-range-key-pair-ar-1: WinRM username: vagrant
    ar-win-attack-range-key-pair-ar-1: WinRM execution_time_limit: PT2H
    ar-win-attack-range-key-pair-ar-1: WinRM transport: plaintext

**Comment by P4T12ICK** [comment]
Hello, thank you for reporting this issue. I will work on it.

**Comment by P4T12ICK** [comment]
This should be fixed. Windows Server 2016 & 2019 is supported on Attack Range local.
