### ISSUE TITLE
ESCU searches uses macros that are not in the range

### ISSUE THREAD

**Issue by patel-bhavin** [splunk/attack_range#119]

**Comment by patel-bhavin** [comment]
PR created for this issue, adding a macros.conf and metadata folder for permissions in ansible

**Comment by d1vious** [comment]
@patel-bhavin should we move these macros to be part of the ESCU package instead, that way is shipped OOB https://github.com/splunk/security-content/tree/develop/package

**Comment by d1vious** [comment]
this was worked into ESCU
