### ISSUE TITLE
failed install 

### ISSUE THREAD

**Issue by spitzd** [splunk/attack_range#127]
Hi,

I am running 64-bit Windows 10 Pro and having issues during the install process.  I am using;
- VirtualBox-6.0.14-133895-Win
- vagrant_2.2.6_x86_64
- python-3.8.0
Successfully activated venv but when I run **pip install -r requirements.txt**, this errors out with the below.  I have tried in cmd and ps with the same result.  Wondering if you have come across this before. 

__VENV_PROMPT__C:\Users\DS\Documents\GitHub\attack_range>pip install -r requirements.txt
Collecting ansible==2.7.12
  Using cached https://files.pythonhosted.org/packages/0a/ad/7c05268f24c9a9234a6a10c6b96271ac7b71fcac3e6ab6955dcc7761bcc3/ansible-2.7.12.tar.gz
Collecting ansible-runner==1.4.4
  Using cached https://files.pythonhosted.org/packages/ac/e0/e475d8b5c185b64821158075943c1168db5b9fc59a47cd4dab6696e5a1ed/ansible_runner-1.4.4-py2.py3-none-any.whl
Collecting apipkg==1.5
  Using cached https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
Collecting atomicwrites==1.3.0
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting attrs==19.3.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: bcrypt==3.1.7 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 6)) (3.1.7)
Collecting boto3==1.10.20
  Using cached https://files.pythonhosted.org/packages/67/66/1a448eb2fe88120b3c05caf27baad0f659205f3bb7c9f8633d9ecf7384b4/boto3-1.10.20-py2.py3-none-any.whl
Collecting botocore==1.13.20
  Using cached https://files.pythonhosted.org/packages/e6/bf/1be397fc65d6b8cfaa400fdc855bf381a73183d8bada8e3775b0e036a7cd/botocore-1.13.20-py2.py3-none-any.whl
Collecting certifi==2019.9.11
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Requirement already satisfied: cffi==1.13.2 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 10)) (1.13.2)
Collecting chardet==3.0.4
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting configparser==4.0.2
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting contextlib2==0.6.0.post1
  Using cached https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Requirement already satisfied: cryptography==2.8 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 14)) (2.8)
Collecting docutils==0.15.2
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting execnet==1.7.1
  Using cached https://files.pythonhosted.org/packages/d3/2e/c63af07fa471e0a02d05793c7a56a9f7d274a8489442a5dc4fb3b2b3c705/execnet-1.7.1-py2.py3-none-any.whl
Collecting idna==2.8
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting importlib-metadata==0.23
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Requirement already satisfied: Jinja2==2.10.3 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 19)) (2.10.3)
Collecting jmespath==0.9.4
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting lockfile==0.12.2
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe==1.1.1 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 22)) (1.1.1)
Collecting mock==3.0.5
  Using cached https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting more-itertools==7.2.0
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Collecting ntlm-auth==1.4.0
  Using cached https://files.pythonhosted.org/packages/50/09/5e397eb18685b14fd8b209e26cdb4fa6451c82c1bcc651fef05fa73e7b27/ntlm_auth-1.4.0-py2.py3-none-any.whl
Collecting packaging==19.2
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Requirement already satisfied: paramiko==2.6.0 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 27)) (2.6.0)
Collecting path.py==12.0.1
  Using cached https://files.pythonhosted.org/packages/40/62/1464f08672cac67e529967ba83b46f38da5d0ca48ac1ce2a9e7d7680ea10/path.py-12.0.1-py3-none-any.whl
Collecting pexpect==4.7.0
  Using cached https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl
Collecting pluggy==0.13.1
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting psutil==5.6.5
  Using cached https://files.pythonhosted.org/packages/03/94/e4ee514cfbc4cca176fcc6b4b1118a724848b570941e90f0b98a9bd234e1/psutil-5.6.5-cp38-cp38-win32.whl
Collecting ptyprocess==0.6.0
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting py==1.8.0
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Requirement already satisfied: pycparser==2.19 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 34)) (2.19)
Requirement already satisfied: PyNaCl==1.3.0 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 35)) (1.3.0)
Collecting pyparsing==2.4.5
  Using cached https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl
Collecting pytest==5.3.0
  Using cached https://files.pythonhosted.org/packages/30/c5/cf0d56d9e0458f66cfef10bc74b375597c34e53e522e23e817673e83f1b9/pytest-5.3.0-py3-none-any.whl
Collecting python-daemon==2.2.4
  Using cached https://files.pythonhosted.org/packages/5a/0c/57f15b1572661877ff1acbe66c2f5be9d999ae5fb128e22933d374f62aa1/python_daemon-2.2.4-py2.py3-none-any.whl
Collecting python-dateutil==2.8.0
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting python-terraform==0.10.1
  Using cached https://files.pythonhosted.org/packages/60/a2/10fa8a5d79096f96f0a1b9917fe3038b453e40b39cc22e07410a365f2dc3/python-terraform-0.10.1.tar.gz
Collecting python-vagrant==0.5.15
  Using cached https://files.pythonhosted.org/packages/bb/c6/0a6d22ae1782f261fc4274ea9385b85bf792129d7126575ec2a71d8aea18/python-vagrant-0.5.15.tar.gz
Collecting pywinrm==0.3.0
  Using cached https://files.pythonhosted.org/packages/0d/12/13a3117bbd2230043aa32dcfa2198c33269665eaa1a8fa26174ce49b338f/pywinrm-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: PyYAML==5.1.2 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 43)) (5.1.2)
Collecting requests==2.22.0
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting requests-ntlm==1.1.0
  Using cached https://files.pythonhosted.org/packages/03/4b/8b9a1afde8072c4d5710d9fa91433d504325821b038e00237dc8d6d833dc/requests_ntlm-1.1.0-py2.py3-none-any.whl
Collecting s3transfer==0.2.1
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: six==1.12.0 in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 47)) (1.12.0)
Collecting tabulate==0.8.6
  Using cached https://files.pythonhosted.org/packages/c4/41/523f6a05e6dc3329a5660f6a81254c6cd87e5cfb5b7482bae3391d86ec3a/tabulate-0.8.6.tar.gz
Collecting termcolor==1.1.0
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting urllib3==1.25.7
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting wcwidth==0.1.7
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting wget==3.2
  Using cached https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
Collecting xmltodict==0.12.0
  Using cached https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Collecting zipp==0.6.0
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\ds\appdata\local\programs\python\python38-32\lib\site-packages (from ansible==2.7.12->-r requirements.txt (line 1)) (41.2.0)
Collecting colorama; sys_platform == "win32"
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Installing collected packages: ansible, psutil, lockfile, docutils, python-daemon, ptyprocess, pexpect, ansible-runner, apipkg, atomicwrites, attrs, jmespath, python-dateutil, urllib3, botocore, s3transfer, boto3, certifi, chardet, configparser, contextlib2, execnet, idna, more-itertools, zipp, importlib-metadata, mock, ntlm-auth, pyparsing, packaging, path.py, pluggy, py, colorama, wcwidth, pytest, python-terraform, python-vagrant, requests, requests-ntlm, xmltodict, pywinrm, tabulate, termcolor, wget
    Running setup.py install for ansible ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ds\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DS\\AppData\\Local\\Temp\\pip-install-mlmfbyj8\\ansible\\setup.py'"'"'; __file__='"'"'C:\\Users\\DS\\AppData\\Local\\Temp\\pip-install-mlmfbyj8\\ansible\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DS\AppData\Local\Temp\pip-record-4gs2h9sv\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\DS\AppData\Local\Temp\pip-install-mlmfbyj8\ansible\
    Complete output (57 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\ansible
    copying lib\ansible\constants.py -> build\lib\ansible
    copying lib\ansible\release.py -> build\lib\ansible
    copying lib\ansible\__init__.py -> build\lib\ansible
    creating build\lib\ansible\cli
    copying lib\ansible\cli\adhoc.py -> build\lib\ansible\cli
    copying lib\ansible\cli\config.py -> build\lib\ansible\cli
    copying lib\ansible\cli\console.py -> build\lib\ansible\cli
    copying lib\ansible\cli\doc.py -> build\lib\ansible\cli
    copying lib\ansible\cli\galaxy.py -> build\lib\ansible\cli
    copying lib\ansible\cli\inventory.py -> build\lib\ansible\cli
    copying lib\ansible\cli\playbook.py -> build\lib\ansible\cli
    copying lib\ansible\cli\pull.py -> build\lib\ansible\cli
    copying lib\ansible\cli\vault.py -> build\lib\ansible\cli
    copying lib\ansible\cli\__init__.py -> build\lib\ansible\cli
    creating build\lib\ansible\compat
    copying lib\ansible\compat\__init__.py -> build\lib\ansible\compat
    creating build\lib\ansible\config
    copying lib\ansible\config\data.py -> build\lib\ansible\config
    copying lib\ansible\config\manager.py -> build\lib\ansible\config
    copying lib\ansible\config\__init__.py -> build\lib\ansible\config
    creating build\lib\ansible\errors
    copying lib\ansible\errors\yaml_strings.py -> build\lib\ansible\errors
    copying lib\ansible\errors\__init__.py -> build\lib\ansible\errors
    creating build\lib\ansible\executor
    copying lib\ansible\executor\action_write_locks.py -> build\lib\ansible\executor
    copying lib\ansible\executor\module_common.py -> build\lib\ansible\executor
    copying lib\ansible\executor\playbook_executor.py -> build\lib\ansible\executor
    copying lib\ansible\executor\play_iterator.py -> build\lib\ansible\executor
    copying lib\ansible\executor\stats.py -> build\lib\ansible\executor
    copying lib\ansible\executor\task_executor.py -> build\lib\ansible\executor
    copying lib\ansible\executor\task_queue_manager.py -> build\lib\ansible\executor
    copying lib\ansible\executor\task_result.py -> build\lib\ansible\executor
    copying lib\ansible\executor\__init__.py -> build\lib\ansible\executor
    creating build\lib\ansible\galaxy
    copying lib\ansible\galaxy\api.py -> build\lib\ansible\galaxy
    copying lib\ansible\galaxy\login.py -> build\lib\ansible\galaxy
    copying lib\ansible\galaxy\role.py -> build\lib\ansible\galaxy
    copying lib\ansible\galaxy\token.py -> build\lib\ansible\galaxy
    copying lib\ansible\galaxy\__init__.py -> build\lib\ansible\galaxy
    creating build\lib\ansible\inventory
    copying lib\ansible\inventory\data.py -> build\lib\ansible\inventory
    copying lib\ansible\inventory\group.py -> build\lib\ansible\inventory
    copying lib\ansible\inventory\helpers.py -> build\lib\ansible\inventory
    copying lib\ansible\inventory\host.py -> build\lib\ansible\inventory
    copying lib\ansible\inventory\manager.py -> build\lib\ansible\inventory
    copying lib\ansible\inventory\__init__.py -> build\lib\ansible\inventory
    creating build\lib\ansible\modules
    copying lib\ansible\modules\__init__.py -> build\lib\ansible\modules
    creating build\lib\ansible\module_utils
    copying lib\ansible\module_utils\acme.py -> build\lib\ansible\module_utils
    error: can't copy 'lib\ansible\module_utils\ansible_release.py': doesn't exist or not a regular file
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\ds\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DS\\AppData\\Local\\Temp\\pip-install-mlmfbyj8\\ansible\\setup.py'"'"'; __file__='"'"'C:\\Users\\DS\\AppData\\Local\\Temp\\pip-install-mlmfbyj8\\ansible\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DS\AppData\Local\Temp\pip-record-4gs2h9sv\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

Thanks for any pointers to fix this.

**Comment by d1vious** [comment]
@spitzd thank you so much for sharing, we done a ton of testing on OSX but not much on win10 to build the environment. Let us do a bit more testing and get back to you.

**Comment by spitzd** [comment]
@d1vious thank you! The install went perfectly on my Mac but since I only have 16GB RAM, it really slows down my machine. As such, I’m trying to run this on my Win 10 machine which has 32GB RAM

**Comment by patel-bhavin** [comment]
@spitzd : hey man, did some quick googling on the issue and seems like Ansible is not supported on Windows Platform. You can find more information on the ansible website:

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements -> look for "Windows"

Hope this helps. Closing this issue for now!

**Comment by patel-bhavin** [comment]
going to update the README have an explicit note that it works only on nix* systems
