### ISSUE TITLE
Adding more detail to vagrant config wiki

### ISSUE THREAD

**Issue by sescandor** [splunk/attack_range#187]
For step #1 of https://github.com/splunk/attack_range/wiki/Configure-Attack-Range-for-Vagrant#vagrant-configuration it would be great to add a bit more detail for installing virtualbox for osx. Specifically, vagrant only runs with specific versions of virtualbox (latest is 6.0 that works well), however, brew cask install uses virtualbox 6.1.

**Comment by d1vious** [comment]
@sescandor thank you so much, let me circle back with the team and work on better docs for this.

**Comment by d1vious** [comment]
Hey we added the specific commands for OSX and also a note about working with Vagrant. Hope [this reads](https://github.com/splunk/attack_range/wiki/Configure-Attack-Range-for-Vagrant#vagrant-configuration) better.
