### ISSUE TITLE
MLTK is not loaded as an available app in Splunk Attack Range instances

### ISSUE THREAD

**Issue by jzsplunk** [splunk/attack_range#213]
MLTK and its dependency python for scientific computing are not loaded as available TAs when we bring up a new splunk instance int the attack range.

**Comment by rvaldez617** [comment]
Just 2 things -
1) Python for scientific computing should be installed first, and is architecture specific.
2) MLTK is installed as part of ES versions >= 6.0, so this should be an either/or with ES
