### ISSUE TITLE
Feature request: make Splunk server an optional component

### ISSUE THREAD

**Issue by philroyer-phantom** [splunk/attack_range#218]
Now that we have Phantom, Kali, and multiple Windows instances, we might want to enable a build that does not include the splunk server. This would make it faster to test Phantom-only workflows. We could use a similar environment variable of 1 or 0 to enable or disable splunk.

**Comment by P4T12ICK** [comment]
I think because of so many dependencies, this is not a good idea and would it make a lot more complicated then implement it for other components. With the latest Phantom branch, Phantom is built anyway as the first machine.
