### ISSUE TITLE
Feature Request: List support OS

### ISSUE THREAD

**Issue by reswob10** [splunk/attack_range#219]
As I was having problems installing the attack_range on my Win10 host, I started googling the errors I was having and it appears that ansible is not supported on Win10 (or any windows).  

If that is true, it would have helped to have a list of supported OS on the wiki.

OTOH, if this SHOULD install on a Win10 host, here is the error I get when I run the last part of the install command (this is inside the virtual environment):  py -m pip install -r .\requirements.txt

```

    error: can't copy 'lib\ansible\module_utils\ansible_release.py': doesn't exist or not a regular file

    ----------------------------------------
Command "E:\splunk-attack\attack_range\env\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\craig\\AppData\\Local\\Temp\\pip-install-2t1iwkn0\\ansible\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\craig\AppData\Local\Temp\pip-record-phwa7rjy\install-record.txt --single-version-externally-managed --compile --install-headers E:\splunk-attack\attack_range\env\include\site\python3.7\ansible" failed with error code 1 in C:\Users\craig\AppData\Local\Temp\pip-install-2t1iwkn0\ansible\
```

I get the same error when I try to install outside the virtual environment.

There were some suggested solutions I found:
https://stackoverflow.com/questions/51167099/installing-ansible-python-package-on-windows
Uses Docker

https://stackoverflow.com/questions/48694085/how-to-overcome-pip-install-ansible-on-windows-failing-with-filename-or-extens
ansible does not appear to publish .whl files anymore.  

https://www.jeffgeerling.com/blog/2017/using-ansible-through-windows-10s-subsystem-linux
getting ready to try this.

**Comment by P4T12ICK** [comment]
We are mainly using Mac or Linux to use the Attack Range. Have you been successful by using the Windows 10 linux subsystem?

**Comment by reswob10** [comment]
Sorry I haven't responded to this....  
I'm going to try and re-install on a linux box.  I will try the Win 10 subsystem as well....

You can close this if you like, I just thought it would be nice in the readme to say Win10 not supported...
