### ISSUE TITLE
Vagrant - step splunk apps>   FAILED! => {"msg": "The task includes an option with an undefined variable

### ISSUE THREAD

**Issue by leirissa** [splunk/attack_range#220]
TASK [search_head : Check if python app exists] ********************************
ok: [attack-range-splunk-server]

TASK [search_head : download Python app from S3 bucket] ************************
fatal: [attack-range-splunk-server]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'splunk_python_app' is undefined\n\nThe error appears to be in '/home/homelab/attack_range/ansible/roles/search_head/tasks/install_mltk_app.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: download Python app from S3 bucket\n ^ here\n"}

RUNNING HANDLER [search_head : restart splunk] *********************************

PLAY RECAP *********************************************************************
attack-range-splunk-server : ok=33 changed=22 unreachable=0 failed=1 skipped=1 rescued=0 ignored=0

The bug is in vagrant/splunk_server/Vagrantfile

change splunk_mltk_ta to splunk_mltk_app and splunk_python_ta to splunk_python_app.

**Comment by rvaldez617** [comment]
There was a mis-named variable in the code. This has been fixed and should work properly now. Thanks to leirissa for quickly reporting this issue!
