### ISSUE TITLE
Installation fails - MacOS - Catalina 10.15.3 

### ISSUE THREAD

**Issue by federico22285** [splunk/attack_range#228]
Hi Guys, 

Love the idea behind this project, from my side I get the feeling that there is no enough information as what versions exactly do I need to have of everything for this to run properly. You said in the documentation that this was tested in MacOS and Linux, it would be great to understand exactly what system was this tested on and all the software versions. A quick example of the errors I am getting on the first try. 

> `(attack_virtual) bash-3.2$ python attack_range.py -m vagrant -a build

 ```
   
**attack_range is using config at path attack_range.conf
2020-02-21 18:43:33,412 - INFO - attack_range - INIT - attack_range v1
2020-02-21 18:43:33,418 - INFO - attack_range - [action] > build

Bringing machine 'attack-range-splunk-server' up with 'virtualbox' provider...
Bringing machine 'attack-range-domain-controller' up with 'virtualbox' provider...
==> attack-range-splunk-server: Box 'generic/ubuntu1804' could not be found. Attempting to find and install...
    attack-range-splunk-server: Box Provider: virtualbox
    attack-range-splunk-server: Box Version: >= 0
==> attack-range-splunk-server: Loading metadata for box 'generic/ubuntu1804'
    attack-range-splunk-server: URL: https://vagrantcloud.com/generic/ubuntu1804
==> attack-range-splunk-server: Adding box 'generic/ubuntu1804' (v2.0.6) for provider: virtualbox
    attack-range-splunk-server: Downloading: https://vagrantcloud.com/generic/boxes/ubuntu1804/versions/2.0.6/providers/virtualbox.box
    attack-range-splunk-server: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> attack-range-splunk-server: Successfully added box 'generic/ubuntu1804' (v2.0.6) for 'virtualbox'!
==> attack-range-splunk-server: Importing base box 'generic/ubuntu1804'...
==> attack-range-splunk-server: Matching MAC address for NAT networking...
==> attack-range-splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.6' is up to date...
==> attack-range-splunk-server: Setting the name of the VM: attack-range-splunk-server
==> attack-range-splunk-server: Clearing any previously set network interfaces...
==> attack-range-splunk-server: Preparing network interfaces based on configuration...
    attack-range-splunk-server: Adapter 1: nat
    attack-range-splunk-server: Adapter 2: hostonly
==> attack-range-splunk-server: Forwarding ports...
    attack-range-splunk-server: 8000 (guest) => 8000 (host) (adapter 1)
    attack-range-splunk-server: 8089 (guest) => 8089 (host) (adapter 1)
    attack-range-splunk-server: 22 (guest) => 2222 (host) (adapter 1)
==> attack-range-splunk-server: Running 'pre-boot' VM customizations...
==> attack-range-splunk-server: Booting VM...
==> attack-range-splunk-server: Waiting for machine to boot. This may take a few minutes...
    attack-range-splunk-server: SSH address: 127.0.0.1:2222
    attack-range-splunk-server: SSH username: vagrant
    attack-range-splunk-server: SSH auth method: private key
    attack-range-splunk-server: 
    attack-range-splunk-server: Vagrant insecure key detected. Vagrant will automatically replace
    attack-range-splunk-server: this with a newly generated keypair for better security.
    attack-range-splunk-server: 
    attack-range-splunk-server: Inserting generated public key within guest...
    attack-range-splunk-server: Removing insecure key from the guest if it's present...
    attack-range-splunk-server: Key inserted! Disconnecting and reconnecting using new SSH key...
==> attack-range-splunk-server: Machine booted and ready!
==> attack-range-splunk-server: Checking for guest additions in VM...
    attack-range-splunk-server: The guest additions on this VM do not match the installed version of
    attack-range-splunk-server: VirtualBox! In most cases this is fine, but in rare cases it can
    attack-range-splunk-server: prevent things such as shared folders from working properly. If you see
    attack-range-splunk-server: shared folder errors, please make sure the guest additions within the
    attack-range-splunk-server: virtual machine match the version of VirtualBox you have installed on
    attack-range-splunk-server: your host and reload your VM.
    attack-range-splunk-server: 
    attack-range-splunk-server: Guest Additions Version: 5.2.32
    attack-range-splunk-server: VirtualBox Version: 6.0
==> attack-range-splunk-server: Setting hostname...
==> attack-range-splunk-server: Configuring and enabling network interfaces...
==> attack-range-splunk-server: Running provisioner: ansible...
    attack-range-splunk-server: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [search_head : add splunk group] ******************************************
changed: [attack-range-splunk-server]

TASK [search_head : add splunk user] *******************************************
changed: [attack-range-splunk-server]

TASK [search_head : make /opt writetable by splunk] ****************************
changed: [attack-range-splunk-server]

TASK [search_head : checking if splunk is install] *****************************
ok: [attack-range-splunk-server]

TASK [search_head : is splunk installed?] **************************************
skipping: [attack-range-splunk-server]

TASK [search_head : download splunk] *******************************************
fatal: [attack-range-splunk-server]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to 127.0.0.1 closed.", "unreachable": true}

PLAY RECAP *********************************************************************
attack-range-splunk-server : ok=4    changed=3    unreachable=1    failed=0    skipped=1    rescued=0    ignored=0   

Traceback (most recent call last):
  File "attack_range.py", line 134, in <module>
    controller.build()
  File "/Users/federico/Downloads/attack_range/modules/VagrantController.py", line 47, in build
    v1.up(provision=True)
  File "/Users/federico/Downloads/attack_range/attack_virtual/lib/python3.7/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/Users/federico/Downloads/attack_range/attack_virtual/lib/python3.7/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1.
(attack_virtual) bash-3.2$** 
`


```

**Comment by d1vious** [comment]
@federico22285 thank you for the feedback I am happy you enjoy the concept. Now as to your bug, it seems the error is not exactly related to the attack_range cli command eg `attack_range.py` but something with the Ansible logic that is erroring out. Specifically it seems like it is having an issue trying to download Splunk eg 
```
TASK [search_head : download splunk] *******************************************
fatal: [attack-range-splunk-server]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to 127.0.0.1 closed.", "unreachable": true}
```
You should be able to built this just using vagrant and Ansible, try and `cd attack_range/vagrant` and then `vagrant up` report back what kind of error you get.

**Comment by federico22285** [comment]
@d1vious Thanks for your feedback, please see below.

`(attack_virtual) bash-3.2$ vagrant up
Bringing machine 'attack-range-splunk-server' up with 'virtualbox' provider...
Bringing machine 'attack-range-domain-controller' up with 'virtualbox' provider...
==> attack-range-splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.6' is up to date...
==> attack-range-splunk-server: Clearing any previously set forwarded ports...
==> attack-range-splunk-server: Clearing any previously set network interfaces...
==> attack-range-splunk-server: Preparing network interfaces based on configuration...
    attack-range-splunk-server: Adapter 1: nat
    attack-range-splunk-server: Adapter 2: hostonly
==> attack-range-splunk-server: Forwarding ports...
    attack-range-splunk-server: 8000 (guest) => 8000 (host) (adapter 1)
    attack-range-splunk-server: 8089 (guest) => 8089 (host) (adapter 1)
    attack-range-splunk-server: 22 (guest) => 2222 (host) (adapter 1)
==> attack-range-splunk-server: Running 'pre-boot' VM customizations...
==> attack-range-splunk-server: Booting VM...
==> attack-range-splunk-server: Waiting for machine to boot. This may take a few minutes...
    attack-range-splunk-server: SSH address: 127.0.0.1:2222
    attack-range-splunk-server: SSH username: vagrant
    attack-range-splunk-server: SSH auth method: private key
==> attack-range-splunk-server: Machine booted and ready!
==> attack-range-splunk-server: Checking for guest additions in VM...
    attack-range-splunk-server: The guest additions on this VM do not match the installed version of
    attack-range-splunk-server: VirtualBox! In most cases this is fine, but in rare cases it can
    attack-range-splunk-server: prevent things such as shared folders from working properly. If you see
    attack-range-splunk-server: shared folder errors, please make sure the guest additions within the
    attack-range-splunk-server: virtual machine match the version of VirtualBox you have installed on
    attack-range-splunk-server: your host and reload your VM.
    attack-range-splunk-server: 
    attack-range-splunk-server: Guest Additions Version: 5.2.32
    attack-range-splunk-server: VirtualBox Version: 6.0
==> attack-range-splunk-server: Setting hostname...
==> attack-range-splunk-server: Configuring and enabling network interfaces...
==> attack-range-splunk-server: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> attack-range-splunk-server: flag to force provisioning. Provisioners marked to run always will still run.
==> attack-range-domain-controller: Box 'd1vious/windows2016' could not be found. Attempting to find and install...
    attack-range-domain-controller: Box Provider: virtualbox
    attack-range-domain-controller: Box Version: >= 0
==> attack-range-domain-controller: Loading metadata for box 'd1vious/windows2016'
    attack-range-domain-controller: URL: https://vagrantcloud.com/d1vious/windows2016
==> attack-range-domain-controller: Adding box 'd1vious/windows2016' (v1.0) for provider: virtualbox
    attack-range-domain-controller: Downloading: https://vagrantcloud.com/d1vious/boxes/windows2016/versions/1.0/providers/virtualbox.box
==> attack-range-domain-controller: Box download is resuming from prior download progress
    attack-range-domain-controller: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> attack-range-domain-controller: Successfully added box 'd1vious/windows2016' (v1.0) for 'virtualbox'!
==> attack-range-domain-controller: Importing base box 'd1vious/windows2016'...
==> attack-range-domain-controller: Matching MAC address for NAT networking...
==> attack-range-domain-controller: Checking if box 'd1vious/windows2016' version '1.0' is up to date...
==> attack-range-domain-controller: Setting the name of the VM: attack-range-domain-controller
==> attack-range-domain-controller: Clearing any previously set network interfaces...
==> attack-range-domain-controller: Preparing network interfaces based on configuration...
    attack-range-domain-controller: Adapter 1: nat
    attack-range-domain-controller: Adapter 2: hostonly
==> attack-range-domain-controller: Forwarding ports...
    attack-range-domain-controller: 3389 (guest) => 3389 (host) (adapter 1)
    attack-range-domain-controller: 22 (guest) => 2222 (host) (adapter 1)
    attack-range-domain-controller: 5985 (guest) => 6000 (host) (adapter 1)
    attack-range-domain-controller: 5985 (guest) => 55985 (host) (adapter 1)
    attack-range-domain-controller: 5986 (guest) => 55986 (host) (adapter 1)
==> attack-range-domain-controller: Running 'pre-boot' VM customizations...
==> attack-range-domain-controller: Booting VM...
==> attack-range-domain-controller: Waiting for machine to boot. This may take a few minutes...
    attack-range-domain-controller: WinRM address: 127.0.0.1:6000
    attack-range-domain-controller: WinRM username: vagrant
    attack-range-domain-controller: WinRM execution_time_limit: PT2H
    attack-range-domain-controller: WinRM transport: plaintext
==> attack-range-domain-controller: Machine booted and ready!
==> attack-range-domain-controller: Checking for guest additions in VM...
    attack-range-domain-controller: The guest additions on this VM do not match the installed version of
    attack-range-domain-controller: VirtualBox! In most cases this is fine, but in rare cases it can
    attack-range-domain-controller: prevent things such as shared folders from working properly. If you see
    attack-range-domain-controller: shared folder errors, please make sure the guest additions within the
    attack-range-domain-controller: virtual machine match the version of VirtualBox you have installed on
    attack-range-domain-controller: your host and reload your VM.
    attack-range-domain-controller: 
    attack-range-domain-controller: Guest Additions Version: 5.2.16
    attack-range-domain-controller: VirtualBox Version: 6.0
==> attack-range-domain-controller: Setting hostname...
==> attack-range-domain-controller: Waiting for machine to reboot...
==> attack-range-domain-controller: Configuring and enabling network interfaces...
==> attack-range-domain-controller: Mounting shared folders...
    attack-range-domain-controller: /vagrant => /Users/federico/Downloads/attack_range/vagrant
==> attack-range-domain-controller: Running provisioner: ansible...
    attack-range-domain-controller: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
objc[9580]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[9580]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by d1vious** [comment]
ah that is actually an error caused by ansible and OSX .. you can see a bit more about the bug here: https://github.com/ansible/ansible/issues/34056 .. a quick work around is simply exporting the following variable before running the attack range `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`. Although if I am not mistaken we should/were doing this as part of the `attack_range.py` CLI command. Let me make sure this did not get lost.

**Comment by d1vious** [comment]
added this as part of the CLI https://github.com/splunk/attack_range/blob/develop/attack_range.py#L14
