### ISSUE TITLE
Error launching source instance - This version has been removed and is no longer available to new customers.

### ISSUE THREAD

**Issue by powermundsen** [splunk/attack_range#231]
When I run the terraform version of attack range I cannot accept the terms and subscribe due to the ubuntu image not being available for new customers any longer (https://aws.amazon.com/marketplace/pp?sku=6l278ltstzlu1yvlpd3h8kdkq).

Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=6l278ltstzlu1yvlpd3h8kdkq
        status code: 401, request id: 598d622c-ab45-4643-8d84-ce4fcc3c1aa5

**Comment by P4T12ICK** [comment]
Hello,

can you do the following changes under terraform/modules/splunk-server/resources.tf:

from:
owners = ["679593333241"]

to:
owners = ["099720109477"]

Let me know if that will fix the issue. We will work on that to get it fixed.

Best regards,
Patrick

**Comment by powermundsen** [comment]
Hi

The change worked well. 

Thanks,

André

**Comment by P4T12ICK** [comment]
Awesome thank you.
