### ISSUE TITLE
Ubuntu + Vagrant build fails at ES post-install setup

### ISSUE THREAD

**Issue by aunraza** [splunk/attack_range#233]
Hello, when enabling ES install, I get the following error:

``TASK [search_head : Run es post-install setup] *********************************
fatal: [attack-range-splunk-server]: FAILED! => {"changed": true, "cmd": ["/opt/splunk/bin/splunk", "search", "| essinstall", "-auth", "admin:*****"], "delta": "0:00:01.608341", "end": "2020-03-04 11:43:12.291611", "msg": "non-zero return code", "rc": 17, "start": "2020-03-04 11:43:10.683270", "stderr": "FATAL: Error in 'essinstall' command: External search command exited unexpectedly with non-zero error code 1.", "stderr_lines": ["FATAL: Error in 'essinstall' command: External search command exited unexpectedly with non-zero error code 1."], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
attack-range-splunk-server : ok=15   changed=2    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   

Traceback (most recent call last):
  File "attack_range.py", line 134, in <module>
    controller.build()
  File "/home/socboss/attackRange/attack_range/modules/VagrantController.py", line 47, in build
    v1.up(provision=True)
  File "/home/socboss/attackRange/attack_range/venv/lib/python3.6/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/home/socboss/attackRange/attack_range/venv/lib/python3.6/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/socboss/attackRange/attack_range/venv/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1.
``

If I don't install ES, then all works as expected. Any tips / suggestions / recommendations?

**Comment by P4T12ICK** [comment]
Hello, 

I'm happy that you already try our newest features :-)
Did you store the ES spl file into the apps folder? Which version of ES did you use?

**Comment by aunraza** [comment]
Hi, yes, it was 6.10, and it was in the apps folder. It did copy fine, and even seemed to have installed based on the ansible output. It was just the post-install setup that seemed to fail:

TASK [search_head : Copy enterprise security to server] ************************
ok: [attack-range-splunk-server]

TASK [search_head : Install es app via REST] ***********************************
ok: [attack-range-splunk-server]

TASK [search_head : Run es post-install setup] *********************************
fatal: [attack-range-splunk-server]: FAILED! => {"changed": true, "cmd": ["/opt/splunk/bin/splunk", "search", "| essinstall", "-auth", "admin:xxxxx"], "delta": "0:00:01.608341", "end": "2020-03-04 11:43:12.291611", "msg": "non-zero return code", "rc": 17, "start": "2020-03-04 11:43:10.683270", "stderr": "FATAL: Error in 'essinstall' command: External search command exited unexpectedly with non-zero error code 1.", "stderr_lines": ["FATAL: Error in 'essinstall' command: External search command exited unexpectedly with non-zero error code 1."], "stdout": "", "stdout_lines": []}

**Comment by P4T12ICK** [comment]
Hi, Enterprise Security version 6.10 needs Splunk Enterprise version 8. The Attack Range uses default the version 7.3.2. Can you test it with ES 5.3.1? We are working on updating the Attack Range to Splunk 8 and the latest ES release.

**Comment by aunraza** [comment]
ah okay! good to know! i'll check and get back to you.

**Comment by aunraza** [comment]
Seems 5.3 works, at least for the ES install. Apologies for the delayed update - was having other issues.

**Comment by P4T12ICK** [comment]
Thank you for your feedback.
