### ISSUE TITLE
Packer does not honor aws region specified in attack_range.conf

### ISSUE THREAD

**Issue by rvaldez617** [splunk/attack_range#234]
Packer appears to create the instances and associated AMIs in the region specified as the default in awscli.

**Comment by P4T12ICK** [comment]
The specified region in Attack Range and awscli needs to be always the same. Otherwise a bunch of functions are not working properly. I will check our docs, if we make that clear during installation.

**Comment by rvaldez617** [comment]
Roger that. For what it's worth, I had no issues with terraform mode, just packer.
