### ISSUE TITLE
Failure to change hostname for domain controller.

### ISSUE THREAD

**Issue by aunraza** [splunk/attack_range#236]
Hello, I'm getting an exception error when running the python vagrant build. The following is the error I get for the Windows Domain Controller:

```
TASK [windows_common : Change the hostname] ************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: winrm.exceptions.InvalidCredentialsError: the specified credentials were rejected by the server
fatal: [attack-range-domain-controller]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
attack-range-domain-controller : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Traceback (most recent call last):
  File "attack_range.py", line 134, in <module>
    controller.build()
  File "/root/attack_range/modules/VagrantController.py", line 47, in build
    v1.up(provision=True)
  File "/root/attack_range/venv/lib/python3.6/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/root/attack_range/venv/lib/python3.6/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/attack_range/venv/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1.
```

**Comment by P4T12ICK** [comment]
Hi, after you run the build command, the vagrant file is generated. Then (when it fails), you can cd into the vagrant folder and execute: vagrant up
Please post the error message here. Thank you.

**Comment by aunraza** [comment]
When I run vagrant up, it skips past the domain controller, and moves on to the next machine. However, when I do vagrant --provision attack-range-domain-controller, I get the following error:

`
vagrant# vagrant provision attack-range-domain-controller
==> attack-range-domain-controller: Running provisioner: ansible...
    attack-range-domain-controller: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [attack-range-domain-controller]: UNREACHABLE! => {"changed": false, "msg": "plaintext: the specified credentials were rejected by the server", "unreachable": true}

PLAY RECAP *********************************************************************
attack-range-domain-controller : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
`

This is the same message if I run vagrant up --provision, where the splunk server is successful, but I get the same error for the domain-controller. 

==> attack-range-domain-controller: Checking if box 'd1vious/windows2016' version '1.0' is up to date...
==> attack-range-domain-controller: Running provisioner: ansible...
    attack-range-domain-controller: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [attack-range-domain-controller]: UNREACHABLE! => {"changed": false, "msg": "plaintext: the specified credentials were rejected by the server", "unreachable": true}

PLAY RECAP *********************************************************************
attack-range-domain-controller : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by P4T12ICK** [comment]
Okay this is weird. What changes did you do in attack_range.conf? Did you destroy the Attack Range before building it again? If not, can you try to do this?

**Comment by aunraza** [comment]
Yeah, it is weird. I did try to destroy it, actually thinking that it may be a "user" related issue, switched to the root account with a fresh git clone. Here are the versions I'm running if it helps:

- OS: Ubuntu Desktop 18.04.1 (updated) 
- VirtualBox: 6.1.4 r136177 (Qt5.9.5)
- Vagrant: 2.2.7
- Ansible: 2.9.2
- Python: 3.6.9

I did change the attack_range.conf - here are the changes I made:

1. change all the values for the passwords - splunk, caldera, win.

2. Enable all the machines: 
```
[environment]
# specify your Attack Range environment by enable (1) or disable (0) machines

windows_domain_controller = 1
# enable a windows domain controller
# possible values: 1, 0

windows_server = 1
# enable a windows server
# possible values: 1, 0

kali_machine = 1
# enable a kali linux machine
# possible values: 1, 0

windows_client = 1
# enable a windows client
# this is only possible for vagrant in the moment
# possible values: 1, 0
```

**Comment by P4T12ICK** [comment]
For me it looks like that the windows domain controller was not destroyed successful because the default vagrant boxes have the user password combination vagrant:vagrant and then during build we change the password to the password defined in the .conf file. When you then build it again, it can't connect anymore with vagrant:vagrant and it fails. Can you ensure that the machines are completely destroyed? Maybe remove it manually.

**Comment by aunraza** [comment]
Alright. Let me try that. Will report back.

**Comment by aunraza** [comment]
While the previous script was going on, an error popped up around the windows server only accepting certain characters in the hostname, so I checked the Vagrantfile and noticed that there was an underscore. I changed that to a hyphen, and then ran the build script again. 

I also went ahead and destroyed the domain controller only, and then re-ran the python build script. This time it seems to have gone past the errors I'd been seeing every time I ran it. Not sure what caused it to fail in the first place, and then get stuck in that cycle, but doing the vagrant destroy, and running the script again seems to have helped. I will post back after to confirm if it has completed successfully.

**Comment by aunraza** [comment]
Also, the hyphen was not in the domain-controller hostname, but the other windows server - it was named win_server. I renamed it to win-server.

**Comment by P4T12ICK** [comment]
Thank you for this feedback and thank you for making attack range better. We will fix this as soon as possible.

**Comment by aunraza** [comment]
This seems to be working now... now the windows 10 machine is still having issues. Cleaned up everything, and then cloned the git repo again, made the modifications to the conf file. 

Now seeing the following:

```
TASK [windows_domain_client : Run join domain] *********************************
fatal: [attack-range-win10]: UNREACHABLE! => {"changed": false, "msg": "winrm connection error: HTTPConnectionPool(host='127.0.0.1', port=5985): Read timed out. (read timeout=30)", "unreachable": true}

PLAY RECAP *********************************************************************
attack-range-win10         : ok=11   changed=8    unreachable=1    failed=0    skipped=2    rescued=0    ignored=0   

Traceback (most recent call last):
  File "attack_range.py", line 134, in <module>
    controller.build()
  File "/root/attack_range/modules/VagrantController.py", line 47, in build
    v1.up(provision=True)
  File "/root/attack_range/venv/lib/python3.6/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/root/attack_range/venv/lib/python3.6/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/attack_range/venv/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1.
```

**Comment by aunraza** [comment]
> Thank you for this feedback and thank you for making attack range better. We will fix this as soon as possible.

If I use vagrant up for each machine that failed due to the python script, will the setup still work? Or do I have to use the python script to make the entire range work?

**Comment by P4T12ICK** [comment]
The python script will prepare all the variables. Afterwards you could also run it with vagrant up.
