### ISSUE TITLE
Vagrant unable to SSH to Kali

### ISSUE THREAD

**Issue by aunraza** [splunk/attack_range#238]
Hello, after running the build script, and it failing multiple times to bring up different machines, I ended up doing vagrant up manually for every machine. When I got to the Kali machine, it seems that it is able to bring it up, but for some reason the machine has two ethernet interfaces eth0 and eth1. Vagrant is assigning eth0 the 10.0.1.8 IP address, however, it is unable to reach the 10.0.1.1 gateway. If i shut that interface down, and bring up eth1 with 10.0.1.8 IP, it is reachable, however, Vagrant seems to be mapping the SSH address to adapter 1 (likely eth0), and eventually ends up timing out during the connection. I am not entirely sure what to change in Vagrant to provide the correct IP address. Any recommendations?

**Comment by P4T12ICK** [comment]
Sorry for the late reply. Do you still have this problem?

**Comment by aunraza** [comment]
Don't recall - been a while. Actually gave up after trying quite a bit.
Will try again at some point.

**Comment by P4T12ICK** [comment]
Okay let me know. For me it was working. I will close the issue. Let's create a new one if it's still not working.
