### ISSUE TITLE
Instance Ubuntu 18 (Ubuntu 18.04 LTS) Minimal - no longer available.

### ISSUE THREAD

**Issue by fwijnholds** [splunk/attack_range#244]
The BattlDroid reports the following: 

`Error: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=6l278ltstzlu1yvlpd3h8kdkq
	status code: 401, request id: 9ed5c5b0-e48f-4f4c-af0d-71dc6302bc6d`

When I follow the URL it get the message:
`This version has been removed and is no longer available to new customers.`

**Comment by akjhhauyo956dhhv05** [comment]
same

**Comment by P4T12ICK** [comment]
Did you use the latest version of the Attack Range?

**Comment by P4T12ICK** [comment]
I think this problem is solved, isn't it. I will keep it open for two days and then close it.

**Comment by fwijnholds** [comment]
I haven't tested with the new release, will try. Closed !
