### ISSUE TITLE
subprocess error while booting up 

### ISSUE THREAD

**Issue by ropuf** [splunk/attack_range#250]
(venv) root@ubuntu:~/attack_range# python3 attack_range.py -m vagrant -a build

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2020-04-13 14:26:58,394 - INFO - attack_range - INIT - attack_range v1
2020-04-13 14:26:58,401 - INFO - attack_range - [action] > build

Bringing machine 'attack-range-splunk-server' up with 'virtualbox' provider...
Bringing machine 'attack-range-windows-domain-controller' up with 'virtualbox' provider...
==> attack-range-splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.6' is up to date...
==> attack-range-splunk-server: Clearing any previously set forwarded ports...
==> attack-range-splunk-server: Vagrant has detected a configuration issue which exposes a
==> attack-range-splunk-server: vulnerability with the installed version of VirtualBox. The
==> attack-range-splunk-server: current guest is configured to use an E1000 NIC type for a
==> attack-range-splunk-server: network adapter which is vulnerable in this version of VirtualBox.
==> attack-range-splunk-server: Ensure the guest is trusted to use this configuration or update
==> attack-range-splunk-server: the NIC type using one of the methods below:
==> attack-range-splunk-server: 
==> attack-range-splunk-server:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
==> attack-range-splunk-server:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
==> attack-range-splunk-server: Clearing any previously set network interfaces...
==> attack-range-splunk-server: Preparing network interfaces based on configuration...
    attack-range-splunk-server: Adapter 1: nat
    attack-range-splunk-server: Adapter 2: hostonly
==> attack-range-splunk-server: Forwarding ports...
    attack-range-splunk-server: 8000 (guest) => 8000 (host) (adapter 1)
    attack-range-splunk-server: 8089 (guest) => 8089 (host) (adapter 1)
    attack-range-splunk-server: 22 (guest) => 2222 (host) (adapter 1)
==> attack-range-splunk-server: Running 'pre-boot' VM customizations...
==> attack-range-splunk-server: Booting VM...
Traceback (most recent call last):
  File "attack_range.py", line 145, in <module>
    controller.build()
  File "/root/attack_range/modules/VagrantController.py", line 54, in build
    v1.up(provision=True)
  File "/root/attack_range/venv/lib/python3.5/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/root/attack_range/venv/lib/python3.5/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1

I am using ubuntu vm as base machine .i tried to update & upgrade but no output.plz help me out

**Comment by P4T12ICK** [comment]
Sorry for my late reply. Can you please cd into vagrant folder and run vagrant up and share the error message in this thread. Thank you.

**Comment by ropuf** [comment]
(venv) root@biometric-Vostro-3470:~/attack_range# python attack_range.py -m vagrant -a build

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2020-04-17 03:04:16,855 - INFO - attack_range - INIT - attack_range v1
2020-04-17 03:04:16,909 - INFO - attack_range - [action] > build

Bringing machine 'attack-range-splunk-server' up with 'virtualbox' provider...
Bringing machine 'attack-range-windows-domain-controller' up with 'virtualbox' provider...
==> attack-range-splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.6' is up to date...
==> attack-range-splunk-server: Clearing any previously set forwarded ports...
==> attack-range-splunk-server: Clearing any previously set network interfaces...
==> attack-range-splunk-server: Preparing network interfaces based on configuration...
    attack-range-splunk-server: Adapter 1: nat
    attack-range-splunk-server: Adapter 2: hostonly
==> attack-range-splunk-server: Forwarding ports...
    attack-range-splunk-server: 8000 (guest) => 8000 (host) (adapter 1)
    attack-range-splunk-server: 8089 (guest) => 8089 (host) (adapter 1)
    attack-range-splunk-server: 22 (guest) => 2222 (host) (adapter 1)
==> attack-range-splunk-server: Running 'pre-boot' VM customizations...
==> attack-range-splunk-server: Booting VM...
==> attack-range-splunk-server: Waiting for machine to boot. This may take a few minutes...
    attack-range-splunk-server: SSH address: 127.0.0.1:2222
    attack-range-splunk-server: SSH username: vagrant
    attack-range-splunk-server: SSH auth method: private key
    attack-range-splunk-server: Warning: Connection reset. Retrying...
    attack-range-splunk-server: Warning: Remote connection disconnect. Retrying...
    attack-range-splunk-server: Warning: Connection reset. Retrying...
    attack-range-splunk-server: Warning: Remote connection disconnect. Retrying...
==> attack-range-splunk-server: Machine booted and ready!
==> attack-range-splunk-server: Checking for guest additions in VM...
==> attack-range-splunk-server: Setting hostname...
==> attack-range-splunk-server: Configuring and enabling network interfaces...
==> attack-range-splunk-server: Running provisioner: ansible...
    attack-range-splunk-server: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [search_head : add splunk group] ******************************************
ok: [attack-range-splunk-server]

TASK [search_head : add splunk user] *******************************************
ok: [attack-range-splunk-server]

TASK [search_head : make /opt writetable by splunk] ****************************
ok: [attack-range-splunk-server]

TASK [search_head : checking if splunk is install] *****************************
ok: [attack-range-splunk-server]

TASK [search_head : is splunk installed?] **************************************
ok: [attack-range-splunk-server] => {
    "msg": "splunk is already installed under /opt/splunk"
}

TASK [search_head : download splunk] *******************************************
skipping: [attack-range-splunk-server]

TASK [search_head : install splunk binary] *************************************
skipping: [attack-range-splunk-server]

TASK [search_head : accept license and start splunk] ***************************
skipping: [attack-range-splunk-server]

TASK [search_head : enable boot-start] *****************************************
skipping: [attack-range-splunk-server]

TASK [search_head : restart splunk] ********************************************
skipping: [attack-range-splunk-server]

TASK [search_head : Create folder directory for inputs configuration] **********
ok: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/inputs_app/local/)

TASK [search_head : copy inputs.conf] ******************************************
ok: [attack-range-splunk-server]

TASK [search_head : Create folder directory for indexes configuration] *********
ok: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/indexes_app/local/)

TASK [search_head : copy indexes.conf to splunk server] ************************
ok: [attack-range-splunk-server]

TASK [search_head : copy authorize.conf for default searchable indexes_app] ****
ok: [attack-range-splunk-server]

TASK [search_head : Create folder directory for web configuration] *************
ok: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/web_app/local/)

TASK [search_head : copy web.conf to splunk server] ****************************
ok: [attack-range-splunk-server]

TASK [search_head : Create folder directory for server configuration] **********
ok: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/server_app/local/)

TASK [search_head : copy server.conf to splunk server] *************************
ok: [attack-range-splunk-server]

TASK [search_head : restart splunk] ********************************************
fatal: [attack-range-splunk-server]: FAILED! => {"changed": false, "msg": "Could not find the requested service splunk: host"}



after i did cd vagrant and vagrant up i am getting the above error.
i upgraded my system to ubuntu 18.04 but no luck
pls help

**Comment by P4T12ICK** [comment]
This is a weird issue. You use Ubuntu 18.04 as OS? Which vagrant version do you use? Which ansible version do you use? We will today release a new version which do some bug fixes in vagrant, can you try the to update to the latest state as of tomorrow? Do you always run a destroy before you try to build the attack range again?

**Comment by ropuf** [comment]
fine.after i destroyed previous attack it ran but

a new error here
starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2020-04-18 01:13:18,162 - INFO - attack_range - INIT - attack_range v1

execute savedsearch: ESCU - Creation of Shadow Copy - Rule

Traceback (most recent call last):
  File "attack_range.py", line 160, in <module>
    controller.search(search_name)
  File "/root/attack_range/modules/VagrantController.py", line 120, in search
    splunk_sdk.search(target_ip,str(self.config['splunk_admin_password']), search_name, self.log)
  File "/root/attack_range/modules/splunk_sdk.py", line 16, in search
    password=splunk_password
  File "/root/attack/attack_range/venv/lib/python3.5/site-packages/splunklib/client.py", line 331, in connect
    s.login()
  File "/root/attack/attack_range/venv/lib/python3.5/site-packages/splunklib/binding.py", line 883, in login
    cookie="1") # In Splunk 6.2+, passing "cookie=1" will return the "set-cookie" header
  File "/root/attack/attack_range/venv/lib/python3.5/site-packages/splunklib/binding.py", line 1235, in post
    return self.request(url, message)
  File "/root/attack/attack_range/venv/lib/python3.5/site-packages/splunklib/binding.py", line 1252, in request
    response = self.handler(url, message, **kwargs)
  File "/root/attack/attack_range/venv/lib/python3.5/site-packages/splunklib/binding.py", line 1392, in request
    connection.request(method, path, body, head)
  File "/usr/lib/python3.5/http/client.py", line 1122, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1167, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1118, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 944, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 887, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1268, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 859, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host


i have no firewall running in my OS .
pls help

**Comment by d1vious** [comment]
@ropuf mind sharing with us the full execution command? Also the output of `python attack_range.py -m <whatmode you used> -lm`. For example 

```
└── # python attack_range.py -lm -m terraform

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.

attack_range is using config at path attack_range.conf
2020-04-20 11:55:09,913 - INFO - attack_range - INIT - attack_range v1

Terraform Status

ERROR: Can't find configured EC2 Attack Range Instances in AWS.
```
