### ISSUE TITLE
HTTP Error access forbidden 

### ISSUE THREAD

**Issue by ropuf** [splunk/attack_range#254]
(venv) root@biometric-Vostro-3470:~/attack_range# python3 attack_range.py -m vagrant -a destroy

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2020-04-18 20:43:35,310 - INFO - attack_range - INIT - attack_range v1
2020-04-18 20:43:35,315 - INFO - attack_range - [action] > destroy

==> attack-range-windows-domain-controller: VM not created. Moving on...
==> attack-range-splunk-server: VM not created. Moving on...
2020-04-18 20:43:37,372 - INFO - attack_range - attack_range has been destroy using vagrant successfully
(venv) root@biometric-Vostro-3470:~/attack_range# python3 attack_range.py -m vagrant -a destroy

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2020-04-18 20:43:49,677 - INFO - attack_range - INIT - attack_range v1
2020-04-18 20:43:49,682 - INFO - attack_range - [action] > destroy

==> attack-range-windows-domain-controller: VM not created. Moving on...
==> attack-range-splunk-server: VM not created. Moving on...
2020-04-18 20:43:52,008 - INFO - attack_range - attack_range has been destroy using vagrant successfully
(venv) root@biometric-Vostro-3470:~/attack_range# vboxmanage list vms
(venv) root@biometric-Vostro-3470:~/attack_range# cd vagrant/
(venv) root@biometric-Vostro-3470:~/attack_range/vagrant# vagrant up
Bringing machine 'attack-range-splunk-server' up with 'virtualbox' provider...
Bringing machine 'attack-range-windows-domain-controller' up with 'virtualbox' provider...
==> attack-range-splunk-server: Importing base box 'generic/ubuntu1804'...
==> attack-range-splunk-server: Matching MAC address for NAT networking...
==> attack-range-splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.6' is up to date...
==> attack-range-splunk-server: Setting the name of the VM: attack-range-splunk-server
==> attack-range-splunk-server: Clearing any previously set network interfaces...
==> attack-range-splunk-server: Preparing network interfaces based on configuration...
    attack-range-splunk-server: Adapter 1: nat
    attack-range-splunk-server: Adapter 2: hostonly
==> attack-range-splunk-server: Forwarding ports...
    attack-range-splunk-server: 8000 (guest) => 8000 (host) (adapter 1)
    attack-range-splunk-server: 8089 (guest) => 8089 (host) (adapter 1)
    attack-range-splunk-server: 22 (guest) => 2222 (host) (adapter 1)
==> attack-range-splunk-server: Running 'pre-boot' VM customizations...
==> attack-range-splunk-server: Booting VM...
==> attack-range-splunk-server: Waiting for machine to boot. This may take a few minutes...
    attack-range-splunk-server: SSH address: 127.0.0.1:2222
    attack-range-splunk-server: SSH username: vagrant
    attack-range-splunk-server: SSH auth method: private key
    attack-range-splunk-server: 
    attack-range-splunk-server: Vagrant insecure key detected. Vagrant will automatically replace
    attack-range-splunk-server: this with a newly generated keypair for better security.
    attack-range-splunk-server: 
    attack-range-splunk-server: Inserting generated public key within guest...
    attack-range-splunk-server: Removing insecure key from the guest if it's present...
    attack-range-splunk-server: Key inserted! Disconnecting and reconnecting using new SSH key...
==> attack-range-splunk-server: Machine booted and ready!
==> attack-range-splunk-server: Checking for guest additions in VM...
    attack-range-splunk-server: The guest additions on this VM do not match the installed version of
    attack-range-splunk-server: VirtualBox! In most cases this is fine, but in rare cases it can
    attack-range-splunk-server: prevent things such as shared folders from working properly. If you see
    attack-range-splunk-server: shared folder errors, please make sure the guest additions within the
    attack-range-splunk-server: virtual machine match the version of VirtualBox you have installed on
    attack-range-splunk-server: your host and reload your VM.
    attack-range-splunk-server: 
    attack-range-splunk-server: Guest Additions Version: 5.2.32
    attack-range-splunk-server: VirtualBox Version: 6.0
==> attack-range-splunk-server: Setting hostname...
==> attack-range-splunk-server: Configuring and enabling network interfaces...
==> attack-range-splunk-server: Running provisioner: ansible...
    attack-range-splunk-server: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [search_head : add splunk group] ******************************************
changed: [attack-range-splunk-server]

TASK [search_head : add splunk user] *******************************************
changed: [attack-range-splunk-server]

TASK [search_head : make /opt writetable by splunk] ****************************
changed: [attack-range-splunk-server]

TASK [search_head : checking if splunk is install] *****************************
ok: [attack-range-splunk-server]

TASK [search_head : is splunk installed?] **************************************
skipping: [attack-range-splunk-server]

TASK [search_head : download splunk] *******************************************
changed: [attack-range-splunk-server]

TASK [search_head : install splunk binary] *************************************
changed: [attack-range-splunk-server]

TASK [search_head : accept license and start splunk] ***************************
changed: [attack-range-splunk-server]

TASK [search_head : enable boot-start] *****************************************
changed: [attack-range-splunk-server]

TASK [search_head : restart splunk] ********************************************
changed: [attack-range-splunk-server]

TASK [search_head : Create folder directory for inputs configuration] **********
changed: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/inputs_app/local/)

TASK [search_head : copy inputs.conf] ******************************************
changed: [attack-range-splunk-server]

TASK [search_head : Create folder directory for indexes configuration] *********
changed: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/indexes_app/local/)

TASK [search_head : copy indexes.conf to splunk server] ************************
changed: [attack-range-splunk-server]

TASK [search_head : copy authorize.conf for default searchable indexes_app] ****
changed: [attack-range-splunk-server]

TASK [search_head : Create folder directory for web configuration] *************
changed: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/web_app/local/)

TASK [search_head : copy web.conf to splunk server] ****************************
changed: [attack-range-splunk-server]

TASK [search_head : Create folder directory for server configuration] **********
changed: [attack-range-splunk-server] => (item=/opt/splunk/etc/apps/server_app/local/)

TASK [search_head : copy server.conf to splunk server] *************************
changed: [attack-range-splunk-server]

TASK [search_head : restart splunk] ********************************************
changed: [attack-range-splunk-server]

TASK [search_head : Copy enterprise security to server] ************************
skipping: [attack-range-splunk-server]

TASK [search_head : Install es app via REST] ***********************************
skipping: [attack-range-splunk-server]

TASK [search_head : Run es post-install setup] *********************************
skipping: [attack-range-splunk-server]

TASK [search_head : Check if ESCU App exists] **********************************
ok: [attack-range-splunk-server]

TASK [search_head : download ESCU app from S3 bucket] **************************
changed: [attack-range-splunk-server]

TASK [search_head : Install escu app via REST] *********************************
ok: [attack-range-splunk-server]

TASK [search_head : download ASX app from S3 bucket] ***************************
fatal: [attack-range-splunk-server]: FAILED! => {"changed": false, "dest": "/tmp/asx_app.tgz", "elapsed": 1, "msg": "Request failed", "response": "HTTP Error 403: Forbidden", "status_code": 403, "url": "https://attack-range-appbinaries.s3-us-west-2.amazonaws.com/Splunk_ASX-latest.tar.gz"}

i was running the machine fine .All of a suddden this error comes up
pls help

**Comment by P4T12ICK** [comment]
That was our fault. I'm sorry. We updated the app and forgot to make it public. Can you try again? Thank you very much.

**Comment by d1vious** [comment]
We changed policies in our s3 bucket to avoid this in the future. Thank you!
