### ISSUE TITLE
Question on how to solve this?

### ISSUE THREAD

**Issue by s1nglethr3ad** [splunk/attack_range#264]
`(venv):attack_range user$ sudo python3 attack_range.py -m vagrant -a build

attack_range is using config at path attack_range.conf
2020-05-04 19:43:00,652 - INFO - attack_range - INIT - attack_range v1
2020-05-04 19:43:00,658 - INFO - attack_range - [action] > build

Bringing machine 'attack-range-splunk-server' up with 'virtualbox' provider...
==> attack-range-splunk-server: Box 'generic/ubuntu1804' could not be found. Attempting to find and install...
    attack-range-splunk-server: Box Provider: virtualbox
    attack-range-splunk-server: Box Version: >= 0
==> attack-range-splunk-server: Loading metadata for box 'generic/ubuntu1804'
    attack-range-splunk-server: URL: https://vagrantcloud.com/generic/ubuntu1804
==> attack-range-splunk-server: Adding box 'generic/ubuntu1804' (v2.0.6) for provider: virtualbox
    attack-range-splunk-server: Downloading: https://vagrantcloud.com/generic/boxes/ubuntu1804/versions/2.0.6/providers/virtualbox.box
    attack-range-splunk-server: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> attack-range-splunk-server: Successfully added box 'generic/ubuntu1804' (v2.0.6) for 'virtualbox'!
==> attack-range-splunk-server: Importing base box 'generic/ubuntu1804'...
==> attack-range-splunk-server: Matching MAC address for NAT networking...
==> attack-range-splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.6' is up to date...
A VirtualBox machine with the name 'attack-range-splunk-server' already exists.
Please use another name or delete the machine with the existing
name, and try again.
2020-05-04 19:45:44,789 - ERROR - attack_range - vagrant failed to build`

On MacOS 10.15.4
Vagrant 2.2.7
VBox 6.1.6
Python 3.6.0

I get this error with no mods to the attack_range.conf.  No previous vagrant runs.

**Comment by P4T12ICK** [comment]
Hi, can you try to delete the VirtualBox Machine attack-range-splunk-server and try it again?

**Comment by s1nglethr3ad** [comment]
> I did and it works.  I did not realize the many places vagrant created files/directories upon build.  Thanks!
> 
> Hi, can you try to delete the VirtualBox Machine attack-range-splunk-server and try it again?
