### ISSUE TITLE
Host VM freezes during setup

### ISSUE THREAD

**Issue by Karma1331** [splunk/attack_range#287]
I'm working on standing up attack range with vagrant and the host VM comes to a dead halt right after printing the following. Any idea what I can do to troubleshoot?
![image](https://user-images.githubusercontent.com/61952449/85336701-adb24880-b4a4-11ea-8205-e996c525a384.png)

**Comment by P4T12ICK** [comment]
Hi, what OS do you use and which version of virtualbox? At one point, I had similar issues with some virtualbox version on MacOS.

**Comment by Karma1331** [comment]
Hi there, 

This is a CentOS 8.0 VM running on a VirtualBox 6.1.6. Inside that CentOS VM is where I am using vagrant to build attack range, the version of VirtualBox inside the VM is 6.0.22.

**Comment by Karma1331** [comment]
Did not fix it, just moving over to another VM (Ubuntu) and using that. Thanks for the response |* A 7 R 1 ( |( 

;)
