### ISSUE TITLE
Vagrant abstract class error

### ISSUE THREAD

**Issue by Karma1331** [splunk/attack_range#290]
Do you have any insight as to what I need to do when faced with this message? I'm still learning Python to troubleshoot it but any insight would be appreciated.

![image](https://user-images.githubusercontent.com/61952449/85904849-693dea00-b7cf-11ea-81eb-6668d6c070f9.png)

**Comment by mrpappagiorgio** [comment]
I am receiving the same error....

**Comment by P4T12ICK** [comment]
we are preparing a new release for today and that issue should be fixed. Thanks for reporting.

**Comment by P4T12ICK** [comment]
this is solved, isn't it?

**Comment by Karma1331** [comment]
It is thank you sir.
