### ISSUE TITLE
Problem with Caldera and the Operations function

### ISSUE THREAD

**Issue by powermundsen** [splunk/attack_range#292]
I'm having a problem with Operations in caldera. I have made sure that there is an agent running on the machine and that the desired adversary contains a few different tactics. But when I try to run the Operation no tactics are added and Caldera ends up not running anything. Is there a problem with the version of Caldera since it says "no version" in the top right corner, or am I doing something wrong? 
![image](https://user-images.githubusercontent.com/7474194/86767455-4b347d00-c04c-11ea-9adf-8917c158a9a6.png)

**Comment by P4T12ICK** [comment]
we are working on improving our caldera implementation. We will use another agent.

**Comment by P4T12ICK** [comment]
this should be fixed.
