### ISSUE TITLE
Building on AWS linux instance failed

### ISSUE THREAD

**Issue by alasdairb** [splunk/attack_range#294]
Following the terraform build inststuctions using an AWS linux instance
got this message
"Amazon Linux 2"

  Stored in directory: /home/ec2-user/.cache/pip/wheels/dd/91/fa/f4295813f6b3d6c66265dfecb170235a104d56392c60d79187
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ec2-user/gitcode/attack_range/venv/bin/python -u -c 'imp

![image](https://user-images.githubusercontent.com/24987994/86796375-6dd38f80-c066-11ea-8765-99e83d3f24a2.png)

**Comment by d1vious** [comment]
@alasdairb give this script a try: https://github.com/splunk/attack_range/wiki/Ubuntu-18.04-Installation-Script I am assuming your missing some of the OS dependency.

**Comment by alasdairb** [comment]
Hi, I tried with Ubuntu 18.04.4 LTS
I executed https://github.com/splunk/attack_range/wiki/Ubuntu-18.04-Installation-Script
I then customised attack_range.conf (for eu-west-1)
I executed python attack_range.py -m terraform -a build

I get this error 
python attack_range.py -m terraform -a build
Traceback (most recent call last):
  File "attack_range.py", line 5, in <module>
    from pathlib import Path
ImportError: No module named pathlib

I repeated it against a new deployment in AWS and got the same message.

**Comment by d1vious** [comment]
looks like you shell might not have the virtual environment activated, eg: 

```
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
```

try running these and then doing a build. Also confirm that awscli is configured if you can by running `aws s3 ls` your s3 buckets should show up 😄

**Comment by alasdairb** [comment]
So I sat down yesterday.
I worked through the missing dependancies, 
 pip install more-itertools
pip install pathlib
pip install configparser

I found that in the Ireland region eu-west-1 it struggled with finding the AMI images
It could not install Kali
module.networkModule.data.aws_availability_zones.available: Refreshing state...

Error: Your query returned no results. Please change your search criteria and try again.

  on modules/kali_machine/resources.tf line 2, in data "aws_ami" "latest-kali-linux":
   2: data "aws_ami" "latest-kali-linux" {


Traceback (most recent call last):
  File "attack_range.py", line 156, in <module>
    controller.build()
  File "/home/ubuntu/attack_range/modules/TerraformController.py", line 43, in build
    self.list_machines()
  File "/home/ubuntu/attack_range/modules/TerraformController.py", line 183, in list_machines
    instances = aws_service.get_all_instances(self.config)
  File "/home/ubuntu/attack_range/modules/aws_service.py", line 37, in get_all_instances
    if len(instance['Tags']) > 0:
KeyError: 'Tags'
(venv) ubuntu@ip-172-31-15-68:~/attack_range$ more  modules/kali_machine/resources.tf


When I run destroy I get
![image](https://user-images.githubusercontent.com/24987994/86891403-af138000-c0f6-11ea-9a1e-21c73bcb377b.png)

**Comment by alasdairb** [comment]
Destroyed the environment above, and so I have switchd back to a AWS Linux instance today as my control point for this build in eu-west-1. I got terraform running (with a some modifications to the AWS instance along the lines of the ubuntu customisations. When I execute python attack_range.py -m terraform -a build  with the defaults.  I am running in this aws region (eu-west-1) so i changed to config file the absolute min. (just region, passwords and key name).  
sudo yum update
sudo yum install python3
sudo yum install python3-devel.x86_64
sudo yum install python-virtualenv.noarch
wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
sudo yum install git
sudo yum install gcc
git clone https://github.com/splunk/attack_range && cd attack_range
cd terraform
terraform init
cd ..
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
aws configure
Copy ssh key over
vi attack_range.conf
### then the attach_range.py -m terraform -a build
### python attack_range.py -m terraform/ -a simulate -st T1003.001 -t attack-range-windows-domain-controller
Logged into Splunk successfully
I get an error in Splunk attack range dashboard 
"Error in 'sseidenrichment' command: (KeyError) 'error'

**Comment by P4T12ICK** [comment]
Did the build command run without an error? The sseidenrichment comes from the Security Essentials App. We will have a look into this issue. This should only affect this certain dashboard and no other functionality of Attack Range.

**Comment by alasdairb** [comment]
Command ran without error. I'm going to go back and do it again but this time add Kali

**Comment by alasdairb** [comment]
So ran it all the way through, got 5 machines built, but missing ES up set the scripts so no apps installed. Still only one error on build.

**Comment by alasdairb** [comment]
HI,
I'm struggling to execute this command (it worked yesterday)
(venv) [ec2-user@ip-192-168-1-142 attack_range]$ python attack_range.py -m
terraform -a simulate -st T1003.001 -t
attack-range-windows-domain-controller

attack_range is using config at path attack_range.conf
2020-07-09 15:49:11,574 - INFO - attack_range - INIT - attack_range v1
Traceback (most recent call last):
  File "attack_range.py", line 168, in <module>
    controller.simulate(target, simulation_techniques)
  File "/home/ec2-user/attack_range/modules/TerraformController.py", line
159, in simulate
    target_public_ip = aws_service.get_single_instance_public_ip(target,
self.config)
  File "/home/ec2-user/attack_range/modules/aws_service.py", line 19, in
get_single_instance_public_ip
    return instance['NetworkInterfaces'][0]['Association']['PublicIp']
TypeError: 'NoneType' object is not subscriptable
(venv) [ec2-user@ip-192-168-1-142 attack_range]$

**Comment by alasdairb** [comment]
I should say, I'm really impressed with the tool, and the potential of it.

**Comment by alasdairb** [comment]
So I solved the problem above by running "... attach_range.py -m terraform -a build" That lead terraform to reconstruct its errant state file. and it did not recreate the terraform.
I was able to test, I did slightly amend within splunk to get the displays to how I wanted them. I think that it creates a good springboard to learn from.
