### ISSUE TITLE
Build fails on Splunk Stream search head task: change file ownership

### ISSUE THREAD

**Issue by Karma1331** [splunk/attack_range#296]
Hi there, 
I've tried building attack range using vagrant in Ubuntu and it keeps failing with the error message shown in image 1. However the file does indeed exist as verified by image 2.

Image 1:
![image](https://user-images.githubusercontent.com/61952449/86873312-a8a7e880-c0a3-11ea-8b1f-ea9e5dcb1a95.png)

Image 2:
![image](https://user-images.githubusercontent.com/61952449/86873652-587d5600-c0a4-11ea-834b-e19fc9d04a03.png)

**Comment by P4T12ICK** [comment]
This is a difficult issue. I just built it with vagrant on my Macbook without an issue. Our different host OS version shouldn't matter in this case.

**Comment by d1vious** [comment]
@Karma1331 I was also not able to replicate the issue. I wonder if you are using a different vagrant box than us. Do you mind running `vagrant box list` .. currently this is my output:

```
┌──[jhernandez@jhernandez-mbp-cb9a8]─[~/splunk/attack_range on  develop!]
└── # vagrant box list
d1vious/windows10   (virtualbox, 1.0)
d1vious/windows2016 (virtualbox, 1.0)
generic/ubuntu1804  (virtualbox, 1.9.18)
```

**Comment by Karma1331** [comment]
Hi there, this is my output:

(venv) karma@Range:~/Documents/attack_range$ vagrant box list
generic/ubuntu1804 (virtualbox, 3.0.10)

**Comment by jzsplunk** [comment]
@Karma1331 thanks for the update! This one is tricky to reproduce on our end would you mind sharing any host OS information or other library specific version info that is readily available (@P4T12ICK is right most likely this independent of host OS but it cant hurt at this point...) .  Are you on OS X/Homebrew?  One suggestion regardless of OS would be to clone a fresh version of attack range and make sure you have updated library dependencies in pip and whatever package manager you are using for the OS ( brew update/brew doctor may even help us in terms of underlying libraries if on OS X).

**Comment by Karma1331** [comment]
My pleasure @jzsplunk  ! Here's some info about my setup, please let me know if you'd like more info. I tried indenting in here but it sucked so here's a pdf of my specs.

[Specs.pdf](https://github.com/splunk/attack_range/files/4899849/Specs.pdf)

**Comment by jzsplunk** [comment]
@Karma1331 a team member of ours seems to have found a fix (first cut of the logic in this PR: https://github.com/splunk/attack_range/pull/300/files).  Here is his correspoding vbox info as well for timeout purposes it appears the splunk stream app was taking too long to install on vbox in certain instances see if this helps and keep us posted: `   config.vm.provider "virtualbox" do |vb, override|
-    vb.gui = true
+    vb.gui = false
     vb.name = "#{VM_NAME}"
     vb.customize ["modifyvm", :id, "--memory", 6144]
-    vb.customize ["modifyvm", :id, "--cpus", 4]
+    vb.customize ["modifyvm", :id, "--cpus", 1]
+    vb.customize ["modifyvm", :id, "--cpuexecutioncap", 20]`

**Comment by Karma1331** [comment]
Hi @jzsplunk , that did not fix it, please see screenshot below: 
![image](https://user-images.githubusercontent.com/61952449/87624361-3790b280-c6ed-11ea-80a3-09179f34ef36.png)

How else can i help?

**Comment by jzsplunk** [comment]
@Karma1331 we updated the develop branch with some fixes for handing DSP installs better.  Try pulling the latest and see if you still have the issue when you get a chance.  Thanks for all your feedback!

**Comment by Karma1331** [comment]
Sorry it's taken so long, I'll get to it this weekend hopefully.

**Comment by jzsplunk** [comment]
@Karma1331 take your time when you get a chance we would love your feedback no rush though thanks again for all your time.
