### ISSUE TITLE
Using Vagrant does not default to VirtualBox

### ISSUE THREAD

**Issue by nickston3** [splunk/attack_range#303]
Is it possible to give the option of a Vagrant provider or force virtualbox as the default?

I use several providers in my environment and got stuck trouble shooting aws/terraform when my vagrant default is aws... d'oh
I'd also like to contribute other providers in the future (like esxi for cloud thats not a cloud)

Something like this:
`v1.up(provision=True, provider="virtualbox")`

**Comment by d1vious** [comment]
@nickston3 certainly, this should be an easy enough change, got a PR going: https://github.com/splunk/attack_range/pull/304

**Comment by d1vious** [comment]
hey PR merged and this is looking good thank you again for raising!
