### ISSUE TITLE
Vargrant DNS settings issue with Splunk Server Deploy

### ISSUE THREAD

**Issue by jzsplunk** [splunk/attack_range#306]
When running the latest develop branch @rvaldez617 and I both keep running into DNS issues on the ubuntu box configured to download Splunk Server.  @rvaldez617 was able to fix the issue by adding an explicit entry to a DNS server in ansible but it looks like those settings might be brittle and the better fix is in this gist (still testing).   

https://gist.github.com/mitchellh/1277049
https://groups.google.com/g/vagrant-up/c/cJ9m-A0hFDU?pli=1

`TASK [search_head : download splunk] *******************************************
fatal: [attack-range-splunk-server]: FAILED! => {"changed": false, "dest": "/opt/", "elapsed": 3, "gid": 0, "group": "root", "mode": "0777", "msg": "Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>", "owner": "root", "size": 4096, "state": "directory", "uid": 0, "url": "https://download.splunk.com/products/splunk/releases/8.0.2/linux/splunk-8.0.2-a7f645ddaf91-Linux-x86_64.tgz"}

PLAY RECAP *********************************************************************
attack-range-splunk-server : ok=5    changed=4    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by rvaldez617** [comment]
Note that this only happened with Vagrant. I'm not sure what changed as this worked before. I suspect it's a change in the behavior of the installed OS, but not sure. The splunk build comes up with a configured DNS server of 127.0.0.53, which is unresponsive. I did a quick fix by adding an ansible step to manually configure DNS, but as mentioned above, probably not the best solution, but seems to work for now.

**Comment by jzsplunk** [comment]
@peter-cg does not hit an issue on the latest develop.  The difference in configs is my machine is OS X Catalina 10.15.5, Virtualbox Version 6.1.12 r139181 (Qt5.6.3).  Peter is on OS X Mojave 10.14.6 Vagrant 2.2.9 but only vbox 6.1.10.

**Comment by rvaldez617** [comment]
I tested on Catalina 10.15.4, vbox 6.1.4, vagrant 2.2.7
