### ISSUE TITLE
Splunk Landing Page contains error with sseidenrichment command

### ISSUE THREAD

**Issue by d1vious** [splunk/attack_range#313]
When loading a new attack range I get the following:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1476868/88843469-2cd72280-d1af-11ea-82cf-d67daac54e20.png">

**Comment by s-koniarz** [comment]
Same error as well

**Comment by etz69** [comment]
This is because sseidenrichment from SSE has found a technique which is not supported by SSE. In recent version of SSE this issue is handled correctly and will not break the command execution. 
Better approach is to update the reporting app to use local lookup and drop dependency to SSE.

**Comment by d1vious** [comment]
@etz69 thank you so much for correcting this! I see now things are working as expected 🤘

**Comment by dlamspl** [comment]
@d1vious You can download updated reporting app from below. The new version of SSE works only by ignoring the error but no data is provided. Below updated app supports sub techniques now. However there is still dependency on SSE to retrieve all splunk detections, but only in one widget.
https://github.com/dlamspl/splunk_attack_range_reporting/releases/download/v1.0.5/splunk_attack_range_reporting-1.0.5.tar.gz
