### ISSUE TITLE
splunk_es_app set to version 611 in current attack_range.conf

### ISSUE THREAD

**Issue by Hops-AF** [splunk/attack_range#315]
In the attack_range.conf file splunk_es_app is hardcoded to an older version of 611.  This results in a failure of ansible and can be corrected by updating the splunk_es_app variable to 620 in the attack_range.conf. Recommend updating or giving additional info in the commented out section of the attack_range.conf for individuals to input the correct version.

**Comment by d1vious** [comment]
@Hops-AF we add an example field in there, not necessarily "hard coded", but also there is a comment that specifies to update it base on the version you will use and placed under the `apps/` folder see: https://github.com/splunk/attack_range/blob/develop/attack_range.conf#L171-L172
