### ISSUE TITLE
MacOS 10.15.5 - attack_range.py ERROR: splunklib.results is not a package error

### ISSUE THREAD

**Issue by forensic65x** [splunk/attack_range#321]
I'm attempting to launch the Terraform Attack range from macOS.

I get the following error regarding splunklib.

python3 attack_range.py --mode terraform --action build
Traceback (most recent call last):
  File "attack_range.py", line 7, in <module>
    from modules.TerraformController import TerraformController
  File "../github/attack_range/modules/TerraformController.py", line 4, in <module>
    from modules import aws_service, splunk_sdk, kubernetes_service, github_service
  File "../github/attack_range/modules/splunk_sdk.py", line 3, in <module>
    import splunklib.results as results
ModuleNotFoundError: No module named 'splunklib.results'; 'splunklib' is not a package

I've confirmed Splunklib is installed.

pip3 install splunklib
Collecting splunklib
  Using cached splunklib-1.0.0-py3-none-any.whl (4.6 kB)
Requirement already satisfied: requests in ./venv/lib/python3.8/site-packages (from splunklib) (2.22.0)
...
Successfully installed pycrypto-2.6.1 splunklib-1.0.0

Any suggestions?

**Comment by P4T12ICK** [comment]
Hi, do you have the virtualenv activated and installed all packages from requirements.txt, as described in the wiki? Then, you don't need to install packages manually. The package for the splunklib is called splunk-sdk in pip but I recommend you to follow the wiki article.

**Comment by forensic65x** [comment]
That worked.  Thanks for the quick reply.  I did get another error regarding kali.  I'll open another issue for that.
