### ISSUE TITLE
Enable a kali linux machine - ERROR: can't find configured EC2 Attack Range

### ISSUE THREAD

**Issue by forensic65x** [splunk/attack_range#322]
I set the following:

phantom_server = 0
# enable a phantom server
# possible values: 1, 0

windows_domain_controller = 1
# enable a windows domain controller
# possible values: 1, 0

windows_server = 1
# enable a windows server
# possible values: 1, 0

kali_machine = 1
# enable a kali linux machine
# possible values: 1, 0

windows_client = 0
# enable a windows client
# this is only possible for vagrant in the moment
# possible values: 1, 0

I then ran this: python3 attack_range.py --mode terraform --action build

It successfully created the domain controller, splunk server and windows server.

It did not create a kali server and gave the following error:

=============

Error: Your query returned no results. Please change your search criteria and try again.

  on modules/kali_machine/resources.tf line 2, in data "aws_ami" "latest-kali-linux":
   2: data "aws_ami" "latest-kali-linux" {

Status EC2 Machines

ERROR: Can't find configured EC2 Attack Range Instances in AWS.

==============

Did I miss something?

**Comment by d1vious** [comment]
that is an interesting issue, have you tried/looked at https://github.com/splunk/attack_range/issues/297 it might help.. I suspect it has something to do with your AWS account having access to the Kali AMI for that region.

**Comment by forensic65x** [comment]
#297 helped.  the kali_machine/resources.tf had 2 typos that needed to be corrected.

Line 9 changed to this:        values = ["kali-linux-2020.*"]
Line 35 changed to this:       user        = "kali"

Once I made those 2 changes, I didn't get the 'can't find configured EC2' error.  I did have to accept the license for Kali after making those 2 changes.

The kicker - I'm attempting to launch this on the Free tier and I now get this error when it attempts to launch the Kali instance..

Error: Error launching source instance: VcpuLimitExceeded: You have requested more vCPU capacity than your current vCPU limit of 32 allows

How many vCPU are the 3 other instances (Splunk, Windows Server and Domain Controller) set to use for this range?

**Comment by forensic65x** [comment]
I'm good to go.  Making those 2 changes to the kali resources.tf solved the kali install issue.  If I actually had experience creating a pull, making the change to the resource file and submitting it I would.. lol
