### ISSUE TITLE
BOTSv2 and BOTSv3 data not being loaded

### ISSUE THREAD

**Issue by forensic65x** [splunk/attack_range#323]
Here's my config setting for BOTS:

  #### SELECTED ALL 3 BOTS datasets
  splunk_bots_dataset = 1a,2a,3

When reviewing the installed apps I only saw this:

I then searched the BOTS indexes. Both botsv2 and botsv3 indexes are empty.

  Search: index=botsv1 earliest=0
  Results: 955,807

  Search: index=botsv2 earliest=0
  Results: 0 

  Search: index=botsv3 earliest=0
  Results: 0 

Then checked the apps for the datasets..  

Saw an entry for BOTS v1 - but none for BOTSv2 or v3..

  Splunk Boss of the SOC (BOTS) Version 1 Data Set | botsv1_data_set

====

Any suggestions?

**Comment by d1vious** [comment]
@forensic65x not sure what is going wrong there, we just pushed a major update yesterday might be worth destroying,removing attack_range and re-cloning. Also important to note that the time events for bots are indexed are not during spin up for the range but when the events actually occurred. Check out it: 

![image](https://user-images.githubusercontent.com/1476868/90187439-c2fe7180-dd87-11ea-9a70-4474dd8bcfb9.png)

More than happy to jump on a zoom if you are still running issues.

**Comment by forensic65x** [comment]
I selected 'All Time' for the searches.  My bad for not including a screenshot.

**Comment by bpenn-splunk** [comment]
Hi Todd, this is Bruce Penn. Any luck per Jose's recommendation? Otherwise, we can get on a Zoom session soon

**Comment by daveherrald** [comment]
I was doing some other work with Attack Range this evening and gave it a test. Like Jose, I was not able to reproduce the problem. I am using AWS/Terraform with [this version](https://github.com/splunk/attack_range/commit/9c1e032244422f50d85ff44c5911c91a3f6be939) of the code. I was using the development branch (beware master branch is broken as of this commit and should not be used) and the attached config file which specifies versions 1a,2a,3. I would take Jose's advice and pull the latest. Try replicating my success with this minimal config file before adding other elements to your range. Please do report back here.

[attack_range.conf.txt](https://github.com/splunk/attack_range/files/5078015/attack_range.conf.txt)

**Comment by forensic65x** [comment]
I did what he suggested and smoked the existing directory and downloaded a fresh copy a couple days ago. 

I attempted to build it a couple times and destroyed it between rebuilds.

Looks like it keeps failing at the same point each time (bolded).

I can send you the attack_range.conf file minus the passwords if that helps.


module.splunk-server.aws_instance.splunk-server: Still creating... [2h6m33s elapsed]
module.splunk-server.aws_instance.splunk-server (local-exec): changed: [REDACTED]

module.splunk-server.aws_instance.splunk-server (local-exec): PLAY RECAP *********************************************************************
module.splunk-server.aws_instance.splunk-server (local-exec): REDACTED             : ok=28   changed=25   unreachable=1    failed=0    skipped=8    rescued=0    ignored=0

Error: Error running command 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu --private-key ~/.ssh/id_rsa -i 'REDACTED,' playbooks/splunk_server.yml -e 'ansible_python_interpreter=/usr/bin/python3 

TASK [search_head : check if BOTSv2 app exists] ********************************
skipping: [REDACTED]

TASK [search_head : download BOTSv2 dataset] ***********************************
skipping: [REDACTED]

TASK [search_head : check if BOTSv2 attack only app exists] ********************
ok: [REDACTED]

**TASK [search_head : download BOTSv2 attack only dataset] ***********************
fatal: [REDACTED]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to REDACTED closed.", "unreachable": true}**

RUNNING HANDLER [splunk_phantom : restart splunk] ******************************
changed: [REDACTED]

PLAY RECAP *********************************************************************
REDACTED             : ok=28   changed=25   unreachable=1    failed=0    skipped=8    rescued=0    ignored=0   

**Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
         status code: 400, request id: 7dea3632-2ac6-4201-903b-5eea7c591b67

  on modules/windows-server/resources.tf line 60, in resource "aws_eip" "windows_server_ip_client":
  60: resource "aws_eip" "windows_server_ip_client"**

Additional attempt..

TASK [search_head : check if BOTSv1 attack only app exists] ********************
ok: [REDACTED]

TASK [search_head : download BOTSv1 attack only dataset] ***********************
changed: [REDACTED]

TASK [search_head : check if BOTSv2 app exists] ********************************
skipping: [REDACTED]

TASK [search_head : download BOTSv2 dataset] ***********************************
skipping: [REDACTED]

TASK [search_head : check if BOTSv2 attack only app exists] ********************
ok: [REDACTED]

**TASK [search_head : download BOTSv2 attack only dataset] ***********************
fatal: [REDACTED]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to REDACTED closed.", "unreachable": true}**

RUNNING HANDLER [splunk_phantom : restart splunk] ******************************
changed: [REDACTED]

PLAY RECAP *********************************************************************
REDACTED              : ok=28   changed=25   unreachable=1    failed=0    skipped=8    rescued=0    ignored=0   

**Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
    status code: 400, request id: 2d1c8f01-8cea-4f68-a996-a05c21f42c6c

  on modules/windows-server/resources.tf line 60, in resource "aws_eip" "windows_server_ip_client":
  60: resource "aws_eip" "windows_server_ip_client" {**

**Comment by daveherrald** [comment]
Yes the config file would help. It's why I posted mine. Please post it here with sensitive values removed.

**Comment by daveherrald** [comment]
Oh hold the phone... as I look at your output more closely, it looks like you are running into an AWS limit on the number of Elastic IPs in your account:

`**Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
status code: 400, request id: 7dea3632-2ac6-4201-903b-5eea7c591b67`

I would address that first before trying again.

**Comment by forensic65x** [comment]
How many are needed?  This is my first AWS adventure... lol

**Comment by daveherrald** [comment]
It's a good question for @d1vious :-)

**Comment by d1vious** [comment]
A public is needed for every asset you bring up. What I suspect might be happening is since you have had a few failures there are remnants confits in AWS from previous executions. Please go to your AWS console -> EC2 -> Elastic IPs and release any unused ones. Also check your running instances and make sure you terminate any attack range ones that might be there.
