### ISSUE TITLE
BOTSv2 full dataset too large for default cloud search head

### ISSUE THREAD

**Issue by daveherrald** [splunk/attack_range#328]
With AWS/Terraform and specifying the full v2 dataset in the config file like this: 

splunk_bots_dataset = 2

I get the following error. 

<img width="1315" alt="2020-08-14_20-58-58" src="https://user-images.githubusercontent.com/480456/90304047-0a146180-de71-11ea-82d1-0268456728a5.png">

When I SSH in I see:

<img width="649" alt="2020-08-14_21-02-16" src="https://user-images.githubusercontent.com/480456/90304115-7e4f0500-de71-11ea-8b15-040878db6fdc.png">

**Comment by d1vious** [comment]
Current Splunk volume is 30gb
 ```
┌──[xxxx]─[~/attack_range/terraform/modules on  develop!]
└── # cat splunk-server/resources.tf | grep volume
    volume_type = "gp2"
    volume_size = "30"
```

try bumping it to 60gb if that works, then we can file PR to increase the disk space to allow for BOTs datasets.

**Comment by daveherrald** [comment]
Nice I did not know where to adjust the specs :-) Tested with 60GB and it seems to work well. Rather than increasing the default, though, perhaps just documenting this required adjustment in the config file comments is enough. The full BOTSv2 data set is not a common install , as we strongly recommend the much smaller V2 attack-only version which fits fine in the current default. I will submit the PR either way (change the .tf file OR update the docs). Let me know your thoughts.

**Comment by d1vious** [comment]
I don't think adding the extra space hurts too much, the worst side effect is an increase in cost, but it is minimal. If you shoot over a PR for the space bump 😄 I would owe you +1 more 🍻 in my tab. Also huge thank you!

**Comment by daveherrald** [comment]
https://github.com/splunk/attack_range/pull/333

**Comment by P4T12ICK** [comment]
I think that is solved
