### ISSUE TITLE
Documentation - Links to Local and Cloud Repos

### ISSUE THREAD

**Issue by wilshire059** [splunk/attack_range#331]
I noticed https://github.com/splunk/attack_range_local/ gives a 404. Have the local and cloud repos been taken down or moved? If so, the documentation should probably be updated with the correct links.

**Comment by d1vious** [comment]
@wilshire059 unfortunately this is correct, we haven't gotten around finishing up the local range repo yet. It should be ready in the next two week. Links are correct, repos are currently private unfortunately.  I will keep this issue open until we open up the attack_range_local repo.

**Comment by victorvillar** [comment]
Any updates on this topic?

**Comment by P4T12ICK** [comment]
Almost done. In case you need it urgently you can go back to a previous commit, e.g. https://github.com/splunk/attack_range/tree/f1ce9574920cf1af0a0d2f0690a2d454ceb73b79

**Comment by P4T12ICK** [comment]
Attack Range local and Attack Range Cloud should be open sourced now.
