### ISSUE TITLE
ip_whitelist does not allow more than 1 IP address

### ISSUE THREAD

**Issue by xlinsplunk** [splunk/attack_range#335]
when adding IP to ip_whitelist in attack_range.conf, specify more than 1 IP will error out when build the range. for example,

ip_whitelist = 204.107.0.0/16, 24.5.0.0/16

will give error at the beginning if build:

Error: "204.107.0.0/16, 24.5.0.0/16" is not a valid CIDR block: invalid CIDR address: 204.107.0.0/16, 24.5.0.0/16

**Comment by P4T12ICK** [comment]
we are able to support this now
