### ISSUE TITLE
support for installation of additional packages during install. 

### ISSUE THREAD

**Issue by mchowdhury-splunk** [splunk/attack_range#353]
Hello:

Will there be an option to install additional packages if required? For instance If I want have something  like eventgen or any custom packages, how do I include this during automated install. 

Thanks.

**Comment by ghoto** [comment]
The installation of custom software it's not under the radar, however you can extend AR by modifying Ansible scripts/configuration to add the software you need to the instances.

If the software you need to install benefits all users of AR, we might consider it to be part of AR.
