### ISSUE TITLE
Build Issue ? 

### ISSUE THREAD

**Issue by harveybob** [splunk/attack_range#370]
Attempting to re-build attack lab in AWS via terraform Mac os x results in following errors after trying to run simulation

python attack_range.py -a simulate -st T1003.001 -t attack-range-windows-domain-controller

 File "attack_range.py", line 136, in main
    controller.simulate(target, simulation_techniques, simulation_atomics)
  File "/Users/key/attack_range/modules/TerraformController.py", line 132, in simulate
    target_public_ip = aws_service.get_single_instance_public_ip(
  File "/Users/key/attack_range/modules/aws_service.py", line 19, in get_single_instance_public_ip
    return instance['NetworkInterfaces'][0]['Association']['PublicIp']
TypeError: 'NoneType' object is not subscriptable

The "aws" region is eu-west-2.

I've rebuild the environment a few times and cleared vend. If you can offer any help it's a great project

**Comment by harveybob** [comment]
Issue was caused by instance name prefixed with default

python attack_range.py -a simulate -st T1003.001 -t default-attack-range-windows-domain-controller

works fine

Or editing instance names

**Comment by harveybob** [comment]
Issue was caused by instance name prefixed with default

python attack_range.py -a simulate -st T1003.001 -t default-attack-range-windows-domain-controller

works fine

Or editing instance names

**Comment by d1vious** [comment]
hey yea, did you find the example somewhere in the readme? We might have to clean things up :-)
