### ISSUE TITLE
Unable to login Caldera AWS

### ISSUE THREAD

**Issue by harveybob** [splunk/attack_range#397]
Built single Splunk Server/Caldera in AWS.

Unable to login. I added the rule to security groups in AWS to allow port 8888
Password changed in config file.

Tried logging in as both red and admin.
Following message received in syslog
Oct 31 10:51:35 splunk-server-2477298 caldera[905]: 2020-10-31 10:51:35 - DEBUG (auth_svc.py:78 login_user) admin logging in:

Login screen returns back to login

**Comment by ps51337** [comment]
I have got the same issue. I was checking different branches and the issue has been present for a long time.
Will this be fixed soon?

**Comment by vonn1e** [comment]
I have the same problem, glad to see it's not just me

**Comment by P4T12ICK** [comment]
I will debug this. Sorry for my late reply.

**Comment by P4T12ICK** [comment]
It should work again. I upgraded to the latest Caldera release 2.8.1. and added the missing security group. Let me know if it's working for you.

**Comment by ps51337** [comment]
Thank you for the help.
I can access Caldera now but I do not see the results of simulations run from Caldera in Splunk Attack Range Dashboard. I also do not see anything when querying index="attack" for Caldera output. Is it normal?

**Comment by secbaymax** [comment]
> I will debug this. Sorry for my late reply.

It's still not working for local build. Please coud you check it.

**Comment by P4T12ICK** [comment]
Caldera is not producing a nice log as Atomic Red Team does, at least as far as I know. That's why it's not that easy to ingest the output of Caldera simulation into the index=attack. When I'm wrong, let me know where I can find this log file. Thank you. @ps51337

**Comment by ps51337** [comment]
I am attaching the sample JSON output from Caldera. I think that the logs are clear enough (look at Steps section).
Is it possible to enable support for Caldera output in Splunk? Running simulations in Caldera, totally separated and without support of Splunk Attack Range, does not make much sense in my opinion. The simulations and different techniques/attacks should be visible in Attack Range Reporting in Splunk the same way as Atomic Red Team.
Thanks @P4T12ICK .
[Test1 - 2020-11-19 11_00_38.json.txt](https://github.com/splunk/attack_range/files/5581677/Test1.-.2020-11-19.11_00_38.json.txt)

**Comment by ps51337** [comment]
Hi @P4T12ICK
Is there any plan to integrate Caldera with Splunk soon?
Thanks a lot for the help.

**Comment by P4T12ICK** [comment]
@ps51337 yes the log file looks good. In which folder are the logs written?

**Comment by ps51337** [comment]
@P4T12ICK I am not sure if they are stored in folders in pretty format. For sure you can download them by querying REST API but how they are exactly stored and what file paths are used need to be checked more precisely by checking the appropriate functions.

https://github.com/mitre/caldera/blob/master/app/api/rest_api.py
See download_file function

https://github.com/mitre/caldera/blob/master/app/service/file_svc.py

**Comment by P4T12ICK** [comment]
yes that is the problem. If it's automatically stored in a file, I can easily read them with a splunk universal forwarder. Querying a rest api is a bigger task.

**Comment by josehelps** [comment]
@ps51337 @harveybob looks like this was resolved, thank you!
