### ISSUE TITLE
Attack Range Wiki error/change needed

### ISSUE THREAD

**Issue by julianwieg** [splunk/attack_range#401]
Hello,
with the removal of local installs/vagrant from attack_range the guide written by me on medium is no longer accurate and should be removed.

So on page   https://github.com/splunk/attack_range/wiki    remove
_`Or his getting start guide written by a hero in the community @JulianWieg`_

**Comment by P4T12ICK** [comment]
Should we add it to the attack_range_local project instead?

**Comment by julianwieg** [comment]
Hi.  No would not bother. My article was written before the 'split' of attack range vs attack range local. 
I pointed my article/how-to now to attack range local and the attack range local installation works and is well documented/easier then when I wrote the article and 'local' did not exist

**Comment by P4T12ICK** [comment]
Thank you

**Comment by josehelps** [comment]
@julianwieg updated, thank you 👍
