### ISSUE TITLE
Error installing ES 6.4.0

### ISSUE THREAD

**Issue by kseidenschnur** [splunk/attack_range#416]
Getting an error when installing ES 6.4.0. Seems that the ESSINSTALL command needs a new argument.
Got it fixed by adding  --ssl_enablement auto to ESS ansible script.

But ES 6.2 is throwing an error. Would need to add a condition either based on .conf or by the filename? Not sure if its worth it since people will most likley using the latest release?

Created a pull request for attack range local containing the simple fix for 6.4.0 without the condition.

**Comment by josehelps** [comment]
@kseidenschnur thank you so much for testing that out, I agree `--ssl_enablement auto` should be added, the tool should default to latest always. We do not test ES in our CI pipeline and last I checked was on 6.2. Was poking around https://github.com/kseidenschnur/attack_range/ but did not see a branch for this, assuming it is not this one https://github.com/splunk/attack_range/pull/380

**Comment by P4T12ICK** [comment]
I prepared a PR with a fix, https://github.com/splunk/attack_range/pull/433

**Comment by P4T12ICK** [comment]
This is fixed
