### ISSUE TITLE
Caldera - Dependencies check failing during the build

### ISSUE THREAD

**Issue by secbaymax** [splunk/attack_range#418]
Caldera - Dependencies check failing during the build.
It tries for 3 times and fail causing caldera down after resume from failed step. 

Please can you check on this @P4T12ICK 

****LOG:**** 
TASK [caldera : Ensure caldera dependencies are present] ***********************
FAILED - RETRYING: Ensure caldera dependencies are present (3 retries left).
FAILED - RETRYING: Ensure caldera dependencies are present (2 retries left).
FAILED - RETRYING: Ensure caldera dependencies are present (1 retries left).
failed: [attack-range-splunk-server] (item=['python3', 'python3-dev', 'python3-pip', 'python3-virtualenv', 'python-virtualenv', 'git-core', 'libffi-dev', 'libssl-dev', 'acl', 'haproxy']) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": ["python3", "python3-dev", "python3-pip", "python3-virtualenv", "python-virtualenv", "git-core", "libffi-dev", "libssl-dev", "acl", "haproxy"], "msg": "Failed to update apt cache: E:Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/main/binary-amd64/by-hash/SHA256/ed0089acce716a99d0e2f5b24cf07869cc32ce14d41bda4d139e5ff36ee3e454  Hash Sum mismatch\nHashes of expected file:\n - Filesize:1425484 [weak]\n - SHA256:ed0089acce716a99d0e2f5b24cf07869cc32ce14d41bda4d139e5ff36ee3e454\n - SHA1:e8db2c3c49181550151126dd45be0082fddffe9d [weak]\n - MD5Sum:e1d5bbd2218b0b842ceb3ea5008841f9 [weak]\nHashes of received file:\n - SHA256:76c4ef3050dacb352cad896bbf84109d1537886075fe5a756899524cadb214ed\n - SHA1:6306912bd0c4764bc38d5be993c9b67d29f06a3d [weak]\n - MD5Sum:f9fd8435c1a57240f6548e99de102b81 [weak]\n - Filesize:1425484 [weak]\nLast modification reported: Thu, 26 Nov 2020 18:15:01 +0000\nRelease file created at: Sun, 29 Nov 2020 19:00:40 +0000\n, E:Some index files failed to download. They have been ignored, or old ones used instead."}

**Comment by P4T12ICK** [comment]
It worked for you a couple of days an now it's not working for you isn't it? Is it related to attack_range_local? If yes, can you open an issue in attack_range_local repository. Thank you.

**Comment by secbaymax** [comment]
I raised new issue in attack range local.

However, if you see error it is mismatch of hashes due to recent updates. 
Check last 3 lines in above log @P4T12ICK 

Last modification reported: Thu, 26 Nov 2020 18:15:01 +0000\nRelease file created at: Sun, 29 Nov 2020 19:00:40 +0000\n, E:Some index files failed to download. They have been ignored, or old ones used instead."}

**Comment by P4T12ICK** [comment]
Will close it here. Need to be fixed in attack_range_local
