### ISSUE TITLE
Windows Client Requires Elastic Network Interface (ENA) - Update Wiki

### ISSUE THREAD

**Issue by splunk-james** [splunk/attack_range#421]
might be worth updating the wiki for the windows client AMI creation process to include the fact that an Elastic Network Interface (ENA) is likely required for the AMI.  When I followed the process as documented the build process failed given the default instance type for the windows client requires ENA.

I simply created a new AMI from the imported AMI and enabled ENA support and all worked.  I followed the process below:
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/enhanced-networking-ena.html

Error when attempting build without ENA support:
module.splunk-server.aws_instance.splunk-server: Creation complete after 28m14s [id=i-05b31425cfeabc13f]
module.splunk-server.aws_eip.splunk_ip: Creating...
module.splunk-server.aws_eip.splunk_ip: Creation complete after 2s [id=eipalloc-0364e131ecd895415]

Error: Error launching source instance: InvalidParameterCombination: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'm5.2xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA.
	status code: 400, request id: 76df3b81-d004-458c-bd25-5650f327aba1

  on modules/windows-client/resources.tf line 15, in resource "aws_instance" "windows_client":
  15: resource "aws_instance" "windows_client" {

**Comment by josehelps** [comment]
James sorry for not getting back to you sooner, do you specifically mean this wiki page? https://github.com/splunk/attack_range/wiki/Upload-Windows-10-AMI-to-AWS?
