### ISSUE TITLE
caldera.service does not exit gracefully when stopped/restarted

### ISSUE THREAD

**Issue by vulnerablebydesign** [splunk/attack_range#431]
**Issue**: caldera.service does not exit gracefully when stopped/restarted
**Impact**: Training progress, user additions, plugin enables, etc do not persist through necessary caldera.service restarts
**Fix**: #https://github.com/mitre/caldera/issues/1983#issuecomment-751024809
**Fix summary**: Add the following to [https://github.com/splunk/attack_range/blob/develop/ansible/roles/caldera/templates/systemd-caldera.service.j2](url) :
`KillSignal=SIGINT`

**My environment**: AWS and Ubuntu 18.04 (per instructions below)
[https://github.com/splunk/attack_range/wiki/AWS:-Ubuntu-18.04-Installation](url)

**Comment by P4T12ICK** [comment]
I prepared a PR with the suggested fix, https://github.com/splunk/attack_range/pull/433
Can you please check it? Thank you.

**Comment by josehelps** [comment]
We just merged a fix for this thank you again for raising it :smile:
