### ISSUE TITLE
Error while running build command

### ISSUE THREAD

**Issue by Sreejith2k** [splunk/attack_range#432]
python attack_range.py -a build 
Tried this as well - python attack_range.py -m terraform -a build
Same error
`Traceback (most recent call last):
  File "attack_range.py", line 7, in <module>
    from modules.TerraformController import TerraformController
  File "/opt/attack_range/modules/TerraformController.py", line 2, in <module>
    from modules.IEnvironmentController import IEnvironmentController
  File "/opt/attack_range/modules/IEnvironmentController.py", line 2, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC`

**Comment by P4T12ICK** [comment]
I think something went wrong with your virtual environment and pip. Did you do the steps explained in the wiki to setup the attack range?

**Comment by josehelps** [comment]
@Sreejith2k did you try rebuilding your virtual env for python? 
```
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
```
