### ISSUE TITLE
VBoxManage: error during build

### ISSUE THREAD

**Issue by damanib21** [splunk/attack_range#440]
During the setup of the attack_range_local environment I continue to get the following error.

==> attack-range-splunk-server: Running 'pre-boot' VM customizations...
==> attack-range-splunk-server: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b1ce8e78-ddc2-4765-83d9-24da5af68ddb", "--type", "gui"]

Stderr: VBoxManage: error: The virtual machine 'attack-range-splunk-server' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

2021-01-19 19:26:31,518 - ERROR - attack_range - vagrant failed to build

I have rebuilt the ubuntu environment as well as having reinstalled vagrant and virtualbox to no avail

**Comment by josehelps** [comment]
@damanib21 that NS_ERROR_FAILURE seems to be associated with an issue on MacOS, is this the OS you are using? Checkout: https://github.com/hashicorp/vagrant/issues/8687
