### ISSUE TITLE
On shortening post boot time for Domain Controllers

### ISSUE THREAD

**Issue by miskoSplunk** [splunk/attack_range#442]
https://github.com/splunk/attack_range/blob/152a2f1d8997e2f82f635aab7f4f0d50808a896b/ansible/roles/windows_domain_controller/tasks/create.yml#L33

@d1vious I think that "wait time" cannot/should not be shortened - to what I remember, it takes some time for a DC to bring up all services after a reboot/shutdown. However, this may just be my perception from observing DCs  that were deployed on VMware and AWS.

**Comment by josehelps** [comment]
hey you opened an issue for this instead of commenting on the previous one, noted :-)
