### ISSUE TITLE
"Linux endpoint" referred to in image in Readme doesnt exist in project files 

### ISSUE THREAD

**Issue by ezztahoun** [splunk/attack_range#455]
"Linux endpoint" referred to in image in Readme doesnt exist in project files. Instead there is a windows10 workstation.

**Comment by josehelps** [comment]
@ezzeldinadel you are absolutely right .. let me add this as an enhancement request.

**Comment by P4T12ICK** [comment]
This is done. Thank you @ezzeldinadel
