### ISSUE TITLE
Add the Mac

### ISSUE THREAD

**Issue by MHaggis** [splunk/attack_range#465]
Add the Mac from AWS to Attack Range.

Notes:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-mac-instances.html#mac-instance-considerations
- Need a dedicated host: https://registry.terraform.io/modules/DanielRDias/dedicated-host/aws/latest
- Additional API: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateHosts.html
Have to release the dedicated instance at the end.

Post build:
- OSQuery
- Ship to Splunk

**Comment by splunk-james** [comment]
I was about to start looking into this exact thing and had started setting up a test range in ap-southeast-1 which supports mac1 dedicated instances, if there is anything I can do to help please let me know.

**Comment by P4T12ICK** [comment]
Hi @splunk-james, we are happy for every contribution. How was your first tests with the Mac instance?
