### ISSUE TITLE
Add an option to not use EIPs by default

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#478]
EIPs tend to be very limited in AWS resources, we should allow this as optional, otherwise some builds can fail with the following error: 

```
Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
	status code: 400, request id: 4bb95421-a6f3-4eef-8af5-818f7645e093
```

**Comment by ccl0utier** [comment]
Yes please.  With a default limit of 5 EIPs per account, most builds will likely fail in account that are already using for anything else.

**Comment by P4T12ICK** [comment]
Done
