### ISSUE TITLE
"WARNING, unable to determine the public ip"

### ISSUE THREAD

**Issue by mikecybersec** [splunk/attack_range#494]
When using Docker to configure the attack range, I'm getting the following

` > configuring attack_range settings
WARNING, unable to determine the public ip`

Is this caused by my AWS configuration?

**Comment by josehelps** [comment]
I do not think so, usually that comes up when it cannot curl to `https://v4.ident.me`, check out the full function https://github.com/splunk/attack_range/blob/develop/modules/configuration.py#L210-L214, it just sets external_ip to empty. Should not have caused any issues in building I hope?

**Comment by josehelps** [comment]
@mikecybersec hope this solved your issue, please let me know if it did not by replying to this comment.
