### ISSUE TITLE
Define AWS IAM policies for building a range

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#504]
Today we tell users we require administrative access, this is too broad, we should define clear set of policies we need in order to build a range. A good starting place is: https://gist.github.com/clong/5eae6a83e6484bb2c01fa5e9cc6e8c9d. This was reported by Vishnuvardhan SB in user slack.

**Comment by sbvishnu** [comment]
@d1vious 
I tested it already with the policies defined in https://gist.github.com/clong/5eae6a83e6484bb2c01fa5e9cc6e8c9d. But I get the below error during the terraform initialization. Looks like the attack range needs more policies defined. Probably can you try adding 'DescribeAvailabilityZones’ to the policies list and see if that works?
![AvailabilityZones Error - Attack range](https://user-images.githubusercontent.com/77316914/120966811-5d4efc00-c784-11eb-8d4a-51588df5f948.JPG)

**Comment by josehelps** [comment]
@patel-bhavin created a draft for a granular policy here: https://github.com/splunk/attack_range/wiki/Granular-AWS-policy
