### ISSUE TITLE
Add ESXI Support

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#508]
This seems pretty straight forward enhancement to accomplish using the following terraform hooks: https://github.com/josenk/terraform-provider-esxi

This was request by a user via Twitter https://twitter.com/burning_pm/status/1409666768671436810?s=21

**Comment by josehelps** [comment]
looked into this, unfortunatly to add ESXi only support would require some manual steps from a user to get things (like OS images) deploy which somewhat goes against the premise of being able to run things in a CI pipeline. The only way to have "automated" deployment into ESXi is if the customers purchases a vsphere license which is pricey :disappointed:

**Comment by pmichaudrc** [comment]
Hey @d1vious how much more manual effort would it be? I understand it doesn't meet the idea of a CI pipeline, but curious as to what the additional lift would be for intervention.

**Comment by josehelps** [comment]
Maybe using vagrant VMware workstation provider is an alternative https://developer.hashicorp.com/vagrant/docs/providers/vmware

specifically on this code https://github.com/splunk/attack_range/blob/develop/vagrant/windows_server/Vagrantfile#L54-L61
