### ISSUE TITLE
Support for openstack

### ISSUE THREAD

**Issue by mHs-98** [splunk/attack_range#517]
HI! A noob here, I would like to know if there is planned to add openstack support any soon. I would aso apprecite if someone could give me quick guide to add openstack support. I'm thinking using this as summer project. Thanks!

**Comment by ljstella** [comment]
Hi @mHs-98 

Thanks for checking out the project! We don't have any plans of our own to add Openstack support to the project right now, but I'd be more than willing to give you some pointers if you wanted to add it yourself. [Here](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest) is the Openstack Terraform provider. I'd suggest looking through the AWS or Azure terraform bits to determine what sort of things are constructed. 

Individual servers are provisioned through Ansible, and that should all transfer over without any issues, so its really just a matter of defining what sort of infrastructure needs to be provisioned via terraform for Openstack, and then adding relevant bits to the /modules/configuration.py file. Feel free to ask any other questions you might have.

Thanks!
