### ISSUE TITLE
Issue with Kali marketplace image

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#520]
```
╷
│ Error: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=89bab4k3h9x4rkojcm2tj8j4l
│ 	status code: 401, request id: 11ee3d3b-02f5-4e55-a8a0-46142947ec39
│ 
│   with module.kali_machine.aws_instance.kali_machine[0],
│   on ../modules/kali_machine/resources.tf line 18, in resource "aws_instance" "kali_machine":
│   18: resource "aws_instance" "kali_machine" {
│ 
╵
```
when attempting to opt  in you get:

![image](https://user-images.githubusercontent.com/1476868/128955807-7fdc766c-816c-4584-b0dc-f460bf347f63.png)

reported by Joerg Beckert via slack.

**Comment by adriankaylor** [comment]
The Kali ami name changed and needs updated filters.  If you edit terraform/aws/modules/kali_machine/resources.tf and change the following value it will pull the updated image. 

OLD: values = ["kali-linux-2020*"]
NEW: values = ["kali-linux-2021*"]

**Comment by josehelps** [comment]
Thank you @adriankaylor I just made the fix, should address this.
