### ISSUE TITLE
Fixes to WinRM Instructions

### ISSUE THREAD

**Issue by davisshannon** [splunk/attack_range#546]
The single quotes in the winrm settings in https://github.com/splunk/attack_range/wiki/Upload-Windows-10-AMI-to-AWS break the commands.

Under configure winrm:
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'

Should be
winrm set winrm/config/winrs @{MaxMemoryPerShellMB="300"}

Same for the others.

**Comment by davisshannon** [comment]
Also, 300MB doesn't appear to be enough for certain tasks.  Not sure the lowest value to get away with is, but I set mine to 4096 and everything ran ok.

**Comment by josehelps** [comment]
hey made those adjustments, please let me know if it looks good to you :tada: https://github.com/splunk/attack_range/wiki/Upload-Windows-10-AMI-to-AWS
