### ISSUE TITLE
Make machines AMI configurable on attack_range.conf

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#548]
Allow users to pass their specific AWS AMI images in an easy way via the attack_range.conf versus just looking the [latest up](https://github.com/splunk/attack_range/blob/develop/terraform/aws/modules/windows-domain-controller/resources.tf#L2-L16). Ideally if the ami configuration parameter is not set, then the latest should be used, otherwise overwrite the latest image with the customer/user provided AMI.

**Comment by grumpalot23** [comment]
Good afternoon Jose, just wanted to see if you had a chance to review this enhancement.
