### ISSUE TITLE
Troubleshooting section?

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#585]
It might be worth adding a quick section to the documentation about typical errors first time users might see and how to fix them?  And/or or a FAQ around typical configuration changes users might typically want to make?

For example in AWS:
- Missing subscriptions to Kali/NGINX in AWS Marketplace
- How to change the instance types used in building AR
- Hitting the limit number of Elastic IPs and how to configure AR to simply use public IPs instead
- etc.

Happy to contribute directly if helpful.

**Comment by josehelps** [comment]
absolutely I just gave [ccloutier-splunk](https://github.com/ccloutier-splunk) access to the repo, you should be able to write wiki articles now https://github.com/splunk/attack_range/wiki if you do not mind creating a new troubleshooting section and adding anything you think is relevant. Happy to seed it as well.
