### ISSUE TITLE
Need help on VBoxManage: error: code NS_ERROR_FAILURE (0x80004005)

### ISSUE THREAD

**Issue by thatchihuahua** [splunk/attack_range#586]
Hi, Team.

When starting up Virtual Box VMs using vagrant in Ubuntu 18.04, after following the local installation instruction [here](https://github.com/splunk/attack_range_local/wiki/Ubuntu-18.04-Installation), we encountered an error shown in the picture : 
![NS_ERROR_FAILURE0x80004005](https://user-images.githubusercontent.com/100874061/156641853-0edc3ca6-f01b-45e4-a06a-c2260e385958.png)

We appreciate any helps regarding this, thank you.

**Comment by thatchihuahua** [comment]
Just found this closed issue which might help us solve this issue. Any inputs appreciated meanwhile going through below thread :
https://github.com/hashicorp/vagrant/issues/8687

**Comment by askkemp** [comment]
I'm fairly certain my fix for this was to force it to be headless. I think I first deleted all of the VMs with `VBoxManage unregistervm` and also did a  `rm -Rf ./vagrant/.vagrant/`

All of the below originally said "true"

```console
user@splunk:/home/user/attack_range_local# grep -r vb.gui
vagrant/windows-server/Vagrantfile:    vb.gui = false
vagrant/phantom-server/Vagrantfile:    vb.gui = false
vagrant/caldera-server/Vagrantfile:    vb.gui = false
vagrant/splunk_server/Vagrantfile:    vb.gui = false
vagrant/windows10/Vagrantfile:    vb.gui = false
vagrant/Vagrantfile:    vb.gui = false
vagrant/Vagrantfile:    vb.gui = false
vagrant/windows-domain-controller/Vagrantfile:    vb.gui = false
vagrant/kali-machine/Vagrantfile:    vb.gui = false
```

**Comment by thatchihuahua** [comment]
Hi, askkemp! Thanks so much for helping, we're able to get through this
