### ISSUE TITLE
When Splunk ES is enabled, web access link should use HTTPS

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#587]
If you enable ES in Attack Range, Splunk will use HTTPS by default.

We should adapt the initial access link provided to users at the end of the build operation accordingly.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/58239192/156645281-aa90b2c1-64b5-40c1-95fa-b40370f4ad84.png">

**Comment by ljstella** [comment]
This has been resolved. Pulling down the latest code should properly print a URL w/ `https` when ES is installed.
