### ISSUE TITLE
Using Attack Range with existing Splunk Instance

### ISSUE THREAD

**Issue by bcampru** [splunk/attack_range#608]
Hello, 

I'm deploying Attack Range on the Azure cloud, I was wondering if there is any way to configure attack range to work with an existing Splunk instance located in a different resource group than Splunk Attack Range.

The reason to do so is because we already have a Splunk lab with ES installed.

**Comment by salmiery** [comment]
I would like this feature as well

**Comment by josehelps** [comment]
Hey @bcampru @salmiery I will make sure we look into this feature in our next release (post 3.0)

**Comment by P4T12ICK** [comment]
Hey @bcampru @salmiery, we already have a early preview branch ready with the Attack Range 3.0 which has this feature included when you  already want to try it out:
https://github.com/splunk/attack_range/tree/attack_range_3

**Comment by bcampru** [comment]
> 

Thank you very much!

**Comment by P4T12ICK** [comment]
this is now merged into develop
