### ISSUE TITLE
when automatically installing ES (install_es = 1) the installer includes PySci/MLTK, this can cause conflicts and install of Splunk to fail

### ISSUE THREAD

**Issue by splunk-james** [splunk/attack_range#615]
Need a clause to disable installation of MLTK and PySci if ES being installed.  If the option to install ES is enabled in attack_range.conf the ES package includes the PySci and MLTK packages as well and will install them.  The current configuration when ES is selected will intermittently cause conflict with the individual installations of those packages resulting in splunk build process failing.

build output (doesn't give any clues):
module.splunk-server.aws_instance.splunk-server: Still creating... [3m20s elapsed]
module.splunk-server.aws_instance.splunk-server (local-exec): fatal: [54.193.179.23]: FAILED! => {"cache_control": "no-store, no-cache, must-revalidate, max-age=0", "changed": false, "connection": "Close", "content_length": "1818", "content_type": "text/xml; charset=UTF-8", "date": "Mon, 30 May 2022 23:36:22 GMT", "elapsed": 18, "expires": "Thu, 26 Oct 1978 00:00:00 GMT", "msg": "Status code was 500 and not [200, 201]: HTTP Error 500: Internal Server Error", "redirected": false, "server": "Splunkd", "status": 500, "url": "https://127.0.0.1:8089/services/apps/local", "vary": "Cookie, Authorization", "x_content_type_options": "nosniff", "x_frame_options": "SAMEORIGIN"}
module.splunk-server.aws_instance.splunk-server (local-exec): RUNNING HANDLER [search_head : restart splunk] *********************************
module.splunk-server.aws_instance.splunk-server (local-exec): PLAY RECAP *********************************************************************
module.splunk-server.aws_instance.splunk-server (local-exec): 54.193.179.23              : ok=77   changed=39   unreachable=0    failed=1    skipped=12   rescued=0    ignored=0

**Comment by splunk-james** [comment]
"_raw","_time",component,"date_hour","date_mday","date_minute","date_month","date_second","date_wday","date_year","date_zone","event_message",eventtype,host,index,linecount,"log_level",punct,source,sourcetype,"splunk_server","splunk_server_group",tag,"tag::eventtype","thread_id","thread_name",timeendpos,timestartpos
"05-31-2022 02:33:31.978 +0000 ERROR ApplicationManager [7329 TcpChannelThread] - Failed to copy: /opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64 to /opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64. 5 errors occurred. Description for first 5: [{operation:""copying source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin/python"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin/python""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64""}]","2022-05-31T02:33:31.978+0000",ApplicationManager,2,31,33,may,31,tuesday,2022,0,"Failed to copy: /opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64 to /opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64. 5 errors occurred. Description for first 5: [{operation:""copying source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin/python"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin/python""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64/bin""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin/linux_x86_64""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64/bin"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64/bin""}, {operation:""transfering contents from source to destination"", error:""Text file busy"", src:""/opt/splunk/var/run/splunk/bundle_tmp/d46e81d2742bee72/Splunk_SA_Scientific_Python_linux_x86_64"", dest:""/opt/splunk/etc/apps/Splunk_SA_Scientific_Python_linux_x86_64""}]","err0r splunkd-log","splunk-server","_internal",1,ERROR,"--_::._+___[_]_-___:_////////__/////.___.____:_[{:","/opt/splunk/var/log/splunk/splunkd.log",splunkd,"splunk-server-tsar-6099",,error,error,7329,TcpChannelThread,29,0

**Comment by splunk-james** [comment]
temporarily removing the tasks to install from ansible/roles/search_head/tasks/main.yml solves the issue

**Comment by P4T12ICK** [comment]
I'm not sure if that is the root cause why it failed in your case. I used the latest version of Attack Range and installed ES 7.0.1 and it worked for me.

**Comment by splunk-james** [comment]
it is intermittent and I can reproduce this quite easily.  I am building from the attacl_range docker image and have been testing building 250 ranges for a workshop.  at one point it would fail 75% of the time.  other times less than 10% dpeending on download speeds etc I guess.  Have a look at the log dumps above you can see it is busy trying to read/write pysci.  When removed these from the main.yml I was able to build 50 ranges with no failures with ES.  Happoy to show you via Zoom.  Shannon Davis also was helping me with this,

**Comment by splunk-james** [comment]
either way ES includes these files it makes no sense to install them twice if you are installing ES especially seeing pysci is 500MB in size

**Comment by splunk-james** [comment]
just need an option that says do not process the task in main.yml for the search head for pysci and mltk if ES is being installed

**Comment by splunk-james** [comment]
technically pysci, mltk and CIM should all be disabled if ES is being installed as ES will install those packages

**Comment by P4T12ICK** [comment]
yeah we can add this. I will work on it.
