### ISSUE TITLE
local-exec provisioner error

### ISSUE THREAD

**Issue by lukas-foro** [splunk/attack_range#633]
Even though after installing everything right and using azure, i get this error all the time. 
![image](https://user-images.githubusercontent.com/108251491/178987530-c69a3836-f23c-45f7-b981-430cff04a2bc.png)
I already tried building the attack range with the windows domain controller only and it worked.
Somehow I noticed, when using multiple vm's I get this error and i don't know how to fix this.
Thanks for your help in advance!

**Comment by P4T12ICK** [comment]
Hello, let me fix it.

**Comment by P4T12ICK** [comment]
this should be fixed. Please try again

**Comment by lukas-foro** [comment]
It works, thanky you very much!

**Comment by lukas-foro** [comment]
Oooops, i did it again!

![image](https://user-images.githubusercontent.com/108251491/179489154-6d3a1090-7c6f-4a2e-be0c-6acd24c522f7.png)

This happens, when I am using...:
- Windows Domain Controller
- Windows Server
- Windows Client
- Kali Linux
- Linux Machine
...paired with badblood

**Comment by P4T12ICK** [comment]
Let me check.

**Comment by P4T12ICK** [comment]
Please try it again. Kali Linux is currently not working because the image is currently not available in the Azure market store.

**Comment by lukas-foro** [comment]
Thanks!
