### ISSUE TITLE
Kali Linux

### ISSUE THREAD

**Issue by lukas-foro** [splunk/attack_range#638]
I didn't find any answers regarding this topic. All we know is, that there is no Kali Linux image in the marketplace in Azure at the moment. Are there any infos when we get an image again?

**Comment by P4T12ICK** [comment]
The official Kali Linux Image from Offensive Security is not available anymore over the Azure marketplace. See for example discussions in this thread:
https://www.microsoftpartnercommunity.com/t5/Microsoft-AppSource-and-Azure/Kali-Linux-Image-Missing-in-Azure-Marketplace/m-p/54479

**Comment by lukas-foro** [comment]
Thank you very much.
