### ISSUE TITLE
Connect to VM's

### ISSUE THREAD

**Issue by lukas-foro** [splunk/attack_range#640]
Hello!
My question is: Can you connect somehow to the virtual machines, generated by the Attack Range. Like via RDP or SSH.

**Comment by P4T12ICK** [comment]
yes you can. After a successful build it will give you the IP addresses, ssh commands and so on. You can use the printed ssh command to ssh into the splunk server and other linux servers. You can use Remote Desktop to RDP into the Windows Servers.

**Comment by lukas-foro** [comment]
Okay, so i got the IP address for the windows client. I type in the ip address and what are the credentials? admin + password i created earlier, right?

**Comment by P4T12ICK** [comment]
it is the attack_range_password value from attack_range.conf and the user is Administrator. It should diplay this information when you run:
python attack_range.py show

**Comment by lukas-foro** [comment]
Well, it doesn't show information about the user sadly. Just name of the vm and the ip address. 
Furthermore it also doesn't work connecting via RDP. Your credentials did not work.

**Comment by P4T12ICK** [comment]
are you on AWS or Azure. In Azure the user name is AzureAdmin

**Comment by lukas-foro** [comment]
Sorry for the late reply.
On Windows it works, but not on the linux machine via ssh.

**Comment by lukas-foro** [comment]
Actually, i don't even have the ip address for the sysmon-linux machine.

**Comment by lukas-foro** [comment]
I didn't find any linux machine on splunk, which is getting logged. Maybe there is a configuration error, and it isn't getting built. I can't even find it via the show command. On Azure, there is also no resource about the linux machine.

**Comment by lukas-foro** [comment]
Furthermore, i noticed, linux sysmon is not supported by the attack range for Azure. There is no terraform template in the folder of azure. Will there be a fix?

**Comment by P4T12ICK** [comment]
In our next big release Attack Range 3.0, there will be a linux machine for Azure containing Sysmon for Linux and OSQuery.

**Comment by lukas-foro** [comment]
Thank you very much for this information.
