### ISSUE TITLE
Trying to run a simulation on a stopped AR should fail with a user-friendly message

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#649]
When trying to run a simulation on a stopped AR, it would be nice to provide a more user-friendly message.

![image](https://user-images.githubusercontent.com/58239192/185658422-b7a92794-f828-41fe-852f-d8ac7dd2960f.png)

Also, cosmetic only, but the messages about the AR when using `show` could also be skipped when it's in stopped state.  Currently it gives:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/58239192/189910623-076faf0e-d5fd-4ea0-98b8-81f42fb3bee8.png">

**Comment by P4T12ICK** [comment]
this should be fixed in Attack range 3
