### ISSUE TITLE
Azure VM sizes

### ISSUE THREAD

**Issue by lukas-foro** [splunk/attack_range#654]
Just wanted to ask, if you tested out the Azure VM sizes, for optimal cost reduction and performance. Currently the Splunk AR VM's are using `Standard D4 v4 (4 vcpus, 16 GiB memory)`

**Comment by P4T12ICK** [comment]
In our case, we run often Enterprise Security and therefore having 4 CPUs and 16GB memory is the minimum.

**Comment by lukas-foro** [comment]
Thank you very much!
