### ISSUE TITLE
kali - unreacheable problem

### ISSUE THREAD

**Issue by tccontre** [splunk/attack_range#656]
while building the attackrange 2.0 I encounter handshake failure in kali box

![Screenshot 2022-08-30 at 11 17 10](https://user-images.githubusercontent.com/26181693/187425400-76fb4f4b-9f2b-4386-bba2-69a84f038671.png)

I thought it is about my key but when I use the ssh after the build I was able to ssh the kali box.

![Screenshot 2022-08-30 at 11 20 12](https://user-images.githubusercontent.com/26181693/187425550-5955c29c-4b87-47f6-873f-eca0c334f971.png)

**Comment by P4T12ICK** [comment]
#660

**Comment by P4T12ICK** [comment]
fixed
