### ISSUE TITLE
Azure Marketplace holds a Kali Linux VM again

### ISSUE THREAD

**Issue by lukas-foro** [splunk/attack_range#657]
Hello!

The Azure Marketplace holds a Kali Linux VM again. Is there any possibility that you can implement it?
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/kali-linux.kali?tab=Overview

Thanks for your feedback!

**Comment by P4T12ICK** [comment]
Thank you for the feedback. We will add it.

**Comment by lukas-foro** [comment]
Thank you very much!
