### ISSUE TITLE
Add Splunk Sankey Diagram - Custom Visualization to the list of apps deployed with AR

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#658]
We should add the [Splunk Sankey Diagram - Custom Visualization](https://splunkbase.splunk.com/app/3112/) app as part of the default application deployed with Attack Range.

It's used in some new panels of the [Splunk Attack Range Reporting](https://github.com/dlamspl/splunk_attack_range_reporting) app since v1.0.7.

**Comment by P4T12ICK** [comment]
Will be in Attack Range 3.0 #637
