### ISSUE TITLE
AMI not found trying to build phantom-server

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#667]
When trying to build an Attack Range on AWS with Phantom Server enabled (`phantom_server = 1`) fails when trying to use the latest CentOS 7 AMI from Marketplace.

![image](https://user-images.githubusercontent.com/58239192/192780784-9954abfb-a1d6-4a5d-86c3-ad2b5656310e.png)

Checking AWS Marketplace confirms that AMI image name is no longer available and has likely been replaced by the following:
![image](https://user-images.githubusercontent.com/58239192/192781021-647d88be-40bf-433c-8fab-6fcf28257f25.png)

**Comment by ljstella** [comment]
Hey @ccl0utier 

I think you might need to refresh your repo. In the existing develop branch on splunk/attack_range, the filter is here: https://github.com/splunk/attack_range/blob/7c3952ad8705ffda839409fd8e101cf439e2bb63/terraform/aws/modules/phantom-server/resources.tf#L10

It looks like the version you were using that was broken is an older version using an "official" image from CentOS that no longer exists.

**Comment by ccl0utier** [comment]
@ljstella Correct and I realized that after doing the PR.  Thanks for pointing that out.  Having said that, I think using `product-code` as opposed to a fixed AMI name would likely be a better way of future-proofing this?  

What do you think?

**Comment by P4T12ICK** [comment]
I think the combination of CentOS Linux 7* as name in the filter and most_recent=true should give as the latest CentOs 7 image. Let me try it.

**Comment by ccl0utier** [comment]
As a side note, I went with what's documented under "Finding AMI Ids" on the [CentOS Official Wiki](https://wiki.centos.org/Cloud/AWS#Official_and_current_CentOS_Public_Images) for the proposed initial PR.

**Comment by P4T12ICK** [comment]
It should be fixed. Thank you
