### ISSUE TITLE
Deployment error in splunk server due to malformed line in apt/sources.list

### ISSUE THREAD

**Issue by zeflow** [splunk/attack_range#682]
When building the splunk server a warning appears. This prevents the continuation of the build.
I have inspected /apt/sources.list on rule 50 however it appears to be just a comment line.
not sure why it is malformed.

![image](https://user-images.githubusercontent.com/1607691/195538295-2b732108-4f2b-41f5-b4d8-7ca94dd7faea.png)

**Comment by P4T12ICK** [comment]
I will have a look. thank you for your issue

**Comment by P4T12ICK** [comment]
Can you try it again? I assume there was some packages issue in the ubuntu repository (nothing to do with Attack Range). Without any changes, it's working for me in the moment.
