### ISSUE TITLE
Need a "Bring your own Splunk" option back for provider

### ISSUE THREAD

**Issue by siddharth-khatsuriya** [splunk/attack_range#689]
The Splunk add-on development teams  have been using attack_range to execute the [security_content](https://github.com/splunk/security_content) test-suite on their respective add-ons. There is a major change introduced as a part of v3.0.0 which is causing disruption in 60+ splunk addons ESCU tests.

In V2.0.0, there used to be an `orca` provider that could be used when there is an existing Splunk infrastructure. It seems this was removed as a part of V3.0.0. 

ref: https://github.com/splunk/attack_range/blob/v2.0.0/attack_range.conf.template#L19

Is there a way this could be added back ?

**Comment by P4T12ICK** [comment]
The orca option doesn't exist anymore but you can define a "Bring your own Splunk" in the config:
https://github.com/splunk/attack_range/blob/develop/configs/attack_range_default.yml#L48
