### ISSUE TITLE
attack_range.py tests argument does not exist in V3.0.0

### ISSUE THREAD

**Issue by siddharth-khatsuriya** [splunk/attack_range#690]
The Splunk add-on development teams have been using attack_range to execute the [security_content](https://github.com/splunk/security_content) test-suite on their respective add-ons. There is a major change introduced as a part of v3.0.0 which is causing disruption in 60+ splunk addons ESCU tests.

Until V2.0.0 there used to be a test argument in attack_range.py file which was used to execute the test_suite residing in the security_content repo which seems to be removed in V3.0.0. Is there an alternative to this approach added in the latter ?

ref: https://github.com/splunk/attack_range/blob/v2.0.0/attack_range.py#L230-L234

**Comment by P4T12ICK** [comment]
I was not aware that this is command is used by your team. I will make sure to add it again as it was before.

**Comment by P4T12ICK** [comment]
until then, you can always download the v2.0.0 release or the develop branch with the following commit c799bf61327f819e7d777df4dfa1f8464f79fac8 , which was before we merged in the new changes.

**Comment by P4T12ICK** [comment]
We want to migrate the testing feature to contentctl. Can you please use either Attack Range 2.0 release or the develop branch with commit c799bf61327f819e7d777df4dfa1f8464f79fac8. We will let you know when the new feature is available in contentctl.
