### ISSUE TITLE
Attack Range Local docs lack information on Linux and OSX versions that can be used

### ISSUE THREAD

**Issue by 7h3sil3nce-splunk** [splunk/attack_range#691]
The current 3.0 docs for Attack Range Local builds is limited in documentation on what versions the build will work on.

https://attack-range.readthedocs.io/en/latest/Attack_Range_Local.html

**Comment by josehelps** [comment]
For clarity the versions of the OSes supported are not called out, I can easily add these for sure, thank you for raising it.
