### ISSUE TITLE
nginx server not working 

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#694]
module.splunk-server.aws_instance.splunk-server[0]: Creation complete after 17m54s [id=i-06194c3d26b3c7222]
module.splunk-server.aws_eip.splunk_ip[0]: Creating...
module.splunk-server.aws_eip.splunk_ip[0]: Creation complete after 2s [id=eipalloc-0b30e22c20a597e2c]

Error: Error running command 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu --private-key /home/jhernandez/splunk/attack_range/jhernandez-24105.key -i '35.91.148.155,' nginx_web_proxy.yml -e 'ansible_python_interpreter=/usr/bin/python3 attack_range_name="ar" attack_range_password="9yBezzriKQdYUz6CBC3" carbon_black_cloud="0" carbon_black_cloud_agent_name="installer_vista_win7_win8-64-3.8.0.627.msi" carbon_black_cloud_company_code="" carbon_black_cloud_s3_bucket="" cloud_provider="aws" crowdstrike_agent_name="WindowsSensor.exe" crowdstrike_customer_ID="" crowdstrike_falcon="0" crowdstrike_logs_access_key_id="" crowdstrike_logs_region="" crowdstrike_logs_secret_access_key="" crowdstrike_logs_sqs_url="" ip_whitelist="73.139.99.203/32,0.0.0.0/0" key_name="jhernandez-24105" range_name="spookyssl" statepath="/home/jhernandez/splunk/attack_range/modules/../terraform/aws/state/ar.terraform.tfstate" use_prebuilt_images_with_packer="0" version="3.0.0" hostname="nginx" nginx_image="nginx-web-proxy-v3-0-0" nginx_server="1" proxy_server_ip="10.0.1.12" proxy_server_port="8000" byo_splunk="0" byo_splunk_ip="" ingest_bots3_data="0" install_dltk="0" install_es="0" s3_bucket_url="https://attack-range-appbinaries.s3-us-west-2.amazonaws.com" splunk_es_app="splunk-enterprise-security_701.spl" splunk_image="splunk-v3-0-0" splunk_uf_url="https://download.splunk.com/products/universalforwarder/releases/8.2.5/linux/splunkforwarder-8.2.5-77015bc7a462-linux-2.6-amd64.deb" splunk_uf_win_url="https://download.splunk.com/products/universalforwarder/releases/8.2.5/windows/splunkforwarder-8.2.5-77015bc7a462-x64-release.msi" splunk_url="https://download.splunk.com/products/splunk/releases/8.2.5/linux/splunk-8.2.5-77015bc7a462-Linux-x86_64.tgz"'': exit status 1. Output: ERROR! the playbook: nginx_web_proxy.yml could not be found

Error: timeout - last error: SSH authentication failed (kali@35.164.123.27:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by cmoreno94** [comment]
Hi! I do not have any idea about Ansible, but I checked the tag=v2.0.0 and I found a file called "nginx_web_proxy.yml" in [ansible/playbooks](https://github.com/splunk/attack_range/tree/v2.0.0/ansible/playbooks) with the following content: 

```
- hosts: all
  gather_facts: False
  become: true
  roles:
    - nginx_web_proxy
```

So I added this file to packer/ansible/nginx_web_proxy.yml and it works.

**Comment by P4T12ICK** [comment]
this should be fixed
