### ISSUE TITLE
Attack Range local throws packer error 

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#696]
![image](https://user-images.githubusercontent.com/1476868/200144867-cac1ccf6-1408-473d-adba-a334ff091acb.png)

seems like this is not passed as an empty variable when building windows server 2016

**Comment by mikeloether** [comment]
I am seeing the same. Error text below:

`TASK [windows_common : debug] **************************************************
fatal: [ar-win-attack-range-key-pair-ar-0]: FAILED! => {"msg": "The conditional check 'use_prebuilt_images_with_packer == \"0\"' failed. The error was: error while evaluating conditional (use_prebuilt_images_with_packer == \"0\"): 'use_prebuilt_images_with_packer' is undefined\n\nThe error appears to be in '/Users/mloether/Splunk/attack_range/packer/ansible/roles/windows_common/tasks/windows-disable-defender.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ here\n"}`

**Comment by P4T12ICK** [comment]
this should be fixed.
