### ISSUE TITLE
Error in Ansible building the packer image for Zeek

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#699]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/58239192/200843843-31fe47af-b2f0-462c-b0d4-9ca14301c6fc.png">

Seems to be related to the OpenSUSE repo.

**Comment by jhodgkinson-splunk** [comment]
It looks like they've removed the packages for 18.04 - they're only building for 20.x and above https://build.opensuse.org/repositories/security:zeek

**Comment by P4T12ICK** [comment]
this should be fixed. Thank you for reporting it.
