### ISSUE TITLE
Ansible error on local build - Failed to set permissions on the temporary files 

### ISSUE THREAD

**Issue by rcegan** [splunk/attack_range#702]
![image](https://user-images.githubusercontent.com/5835816/201590408-004d6db2-996f-4e25-a7d1-3f05dff5706c.png)

Triggers when Ansible gets up to the "splunk_server_post.yml" step. I've tried allowing global access to tmpfiles but didn't seem to make a difference (See: https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary)

**Comment by P4T12ICK** [comment]
I was not able to reproduce the issue. Can you shore your attack_range.yml configuration? Which OS do you use?
