### ISSUE TITLE
Add a user-friendly message when a selected technique has no test

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#709]
Currently, trying to run tests using Atomic Red Team on a technique that has no test results in an error hidden in Ansible's output.  The Ansible task also does not report it (returns ok).

Here's an example:

![image](https://user-images.githubusercontent.com/58239192/202211277-cf0a21c8-b8bf-4ee4-ae46-69306356c729.png)

It would be nice to check if a request technique has at least one applicable test and report that back to the user in a friendly manner when that's not the case.

Maybe we could use [this](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/Indexes/Indexes-CSV/windows-index.csv)?

**Comment by P4T12ICK** [comment]
fixed by you. Thank you
