### ISSUE TITLE
error attack_range

### ISSUE THREAD

**Issue by CarlosCabal** [splunk/attack_range#71]
INIT - Attack Range v1

starting program loaded for mode - B1 battle droid

  ||/__'`.
  |//()'-.:
  |-.||
  |o(o)
  |||\\  .==._
  |||(o)==::'
   `|T  ""
    ()
    |\
    ||\
    ()()
    ||//
    |//
   .'=`=.

this is not our first run binary directory exists, skipping setup
Traceback (most recent call last):
  File "attack_range.py", line 68, in prep_ansible
    f = open("terraform/terraform.tfvars", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'terraform/terraform.tfvars'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "attack_range.py", line 208, in <module>
    prep_ansible()
  File "attack_range.py", line 88, in prep_ansible
    except e:
NameError: name 'e' is not defined

**Comment by trogdorsey** [comment]
Good catch. Adding in code to catch exception, display error message, and exit

**Comment by diskurse** [comment]
Hi, same issue here.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "attack_range.py", line 208, in <module>
    prep_ansible()
  File "attack_range.py", line 88, in prep_ansible
    except e:
NameError: name 'e' is not defined

**Comment by diskurse** [comment]
Ah I see the problem is that there is not a terraform.tfvars file, didn't realize vagrant was pulling config from there, sorry.

**Comment by d1vious** [comment]
Its a bit of a mess atm, plan is to refactor into a attack_range config file very soon!

**Comment by P4T12ICK** [comment]
Looks like the error is solved. We refactored the code. It should not happen anymore with the current version.
