### ISSUE TITLE
Documentation for PurpleSharp simulation should be corrected

### ISSUE THREAD

**Issue by ccl0utier** [splunk/attack_range#713]
Trying to follow the [documentation](https://attack-range.readthedocs.io/en/latest/Attack_Simulation.html#purple-sharp) to run a PurpleSharp playbook does not seem to work.

![image](https://user-images.githubusercontent.com/58239192/203121621-149ef95b-0783-4557-9106-22a3e00dc1ae.png)

I had to change my command to:

`python attack_range.py simulate -e PurpleSharp -t ar-win-ec2key-mon-canlab-01-ar-0 -p configs/purplesharp_playbook_T1003.001.pb`

**Comment by mvelazc0** [comment]
Thanks @ccl0utier 

Just fixed it in the develop branch.

https://github.com/splunk/attack_range/commit/1573e79cdd3a45289ecc368c8d4aecb264e57905
