### ISSUE TITLE
Error KeyPair

### ISSUE THREAD

**Issue by CarlosCabal** [splunk/attack_range#72]
aws_instance.splunk-server: Creating...

Error: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'terraform' does not exist
	status code: 400, request id: 2911f96b-b45d-41ad-beae-6670f20bce9d

  on main.tf line 53, in resource "aws_instance" "splunk-server":
  53:  resource "aws_instance" "splunk-server" {

Error: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'terraform' does not exist
	status code: 400, request id: 381aee0c-b702-4ae8-ae3d-3482beab270a

  on main.tf line 74, in resource "aws_instance" "windows_2016_dc":
  74: resource "aws_instance" "windows_2016_dc" {

attack_range has been built using terraform successfully

**Comment by d1vious** [comment]
Carlos might this be related to issue #71 did you create your own copy of https://github.com/splunk/attack_range/blob/develop/terraform/terraform.tfvars.example under `terraform/terraform.tfvars`

**Comment by CarlosCabal** [comment]
I already have the copy of terraform.tfvars

**Comment by P4T12ICK** [comment]
@CarlosCabal  please use the newest version of the branch develop, if you still have the problem.
