### ISSUE TITLE
simulate with ART no longer supports specifying single test

### ISSUE THREAD

**Issue by splunk-james** [splunk/attack_range#728]
when running simulate with ART in v3.0.0 i.e. 'python attack_range.py simulate -e ART -te T1003.001 -t target' only technique/sub-technique is working, you cannot specify individual tests i.e. T1003.001-1 .  Appears changes in the check available tests in "run_art_test_windows.yml" may have stopped the ability to use a single test rather than a full set of tests for a sub-technique.  The logic checks for available tests based on the folder names under C:\AtomicRedTeam\atomics and as all tests are under this folder it fails with an error stating the test is not available.

fatal: [52.77.235.60]: FAILED! => {"changed": false, "msg": "The selected technique T1547.001-1 has no atomic tests. Please ensure it it correct and that tests exist for it. See https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/Indexes/Indexes-CSV/windows-index.csv."}

Section from "run_art_test_windows.yml" that checks -te value against folder names:
- name: List available Atomic Red Team Techniques
  ansible.windows.win_find:
    paths: C:\AtomicRedTeam\atomics
    file_type: directory
    patterns: T*
  register: available_techniques

**Comment by patel-bhavin** [comment]
tested the fix in this PR 
https://github.com/splunk/attack_range/pull/763

**Comment by splunk-james** [comment]
thanks @patel-bhavin works well
