### ISSUE TITLE
Update attack_range v3 docker container to support multi platform (Apple M1/M2)

### ISSUE THREAD

**Issue by splunk-james** [splunk/attack_range#729]
Using docker buildx it is possible to create multi-platform docker images.  I have tested the process and created a sample multi-platform image already that appears to work from the latest attack_range v3.  Sample is here in a public repo for anyone to test
jsy998s/attack_range:multi.

There is one small modification required to the Dockerfile for this to work - remove the "[arch=amd64]" parameter from the command to add the hashicorp repo to add all repos.

Steps to create
1. docker buildx create --use (set the default driver to use multi platform)
2. docker buildx build --platform linux/amd64,linux/arm64 --push -t repo/attack_range:tag . (build from the docker directory with buildx and push to a repo).

**Comment by jonod8698** [comment]
Can you link the repo? I can't find the "multi" tag under your fork.

**Comment by P4T12ICK** [comment]
This is done and integrated
