### ISSUE TITLE
404 NOT FOUND = curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

### ISSUE THREAD

**Issue by ralphdt** [splunk/attack_range#731]
404 NOT FOUND 

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

I guess someone moved something ?

**Comment by b33kar** [comment]
That install method is deprecated and removed, below is the correct method.

curl -sSL https://install.python-poetry.org | python3 -

**Comment by patel-bhavin** [comment]
docs are updated with the above^^. thanks!
