### ISSUE TITLE
Azure - default credential scopes set for public cloud

### ISSUE THREAD

**Issue by airlinedev** [splunk/attack_range#733]
Was troubleshooting issues using Azure as the cloud provider and came across some helpful resources. If you're not using the standard public cloud, you might run into issues without specifying the base_url and credential_scopes in your *ManagementClient constructors. See below two links for more insight. I'll try to do a PR, but it might be quicker if someone else fixed it.

https://github.com/Azure/azure-sdk-for-python/issues/16688#issuecomment-777588358
https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-sovereign-domain

**Comment by P4T12ICK** [comment]
Thank you for the feedback and I'm very sorry that we come back to you so late. The problem is that we only have access to the standard public cloud in Azure, therefore we can't fix it and test it.
