### ISSUE TITLE
Apache Tomcat download URL is incorrect

### ISSUE THREAD

**Issue by j00c3** [splunk/attack_range#735]
The Apache Tomcat download URL in `/attack_range/packer/ansible/roles/guacamole/tasks/setup_tomcat.yml` line 9 results in a 404.

I suggest YAML file point to Apache's archive URL. When Apache Foundation updates a version, their download page is updated to reflect the latest release, rendering the previous release's frontpage download URL (`https://dlcdn.apache.org...`) outdated. The releases' archive URL, however, does not.

Example:

Current Tomcat 9 is 9.0.71. Frontpage download URL is `https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz`. Even though it's the current version, it still has an archive URL `https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz`.

**Comment by P4T12ICK** [comment]
thank you very much. I will directly implement it.
