### ISSUE TITLE
Kali - SSH authentication failed

### ISSUE THREAD

**Issue by cmoreno94** [splunk/attack_range#737]
I am working in [992e107](https://github.com/splunk/attack_range/commit/992e107c2453e0ed5b4c117786f7705af10d72f1) commit. Same in issue [https://github.com/splunk/attack_range/issues/656](url)

`
│ Error: remote-exec provisioner error with module.kali-server.aws_instance.kali_machine[0], on modules/kali-server/resources.tf line 30, in resource "aws_instance" "kali_machine": 30:   provisioner "remote-exec" {`<br>` timeout - last error: SSH authentication failed (kali@x.x.x.x:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

**Comment by j00c3** [comment]
Adding data point. I'm having the same experience.

![image](https://user-images.githubusercontent.com/9037100/220787952-27bbb3c4-e651-4140-8fea-464b29eda22b.png)

For context: I have another terminal window open during Terraform/Ansible execution, as well as the AWS console. As soon as the Kali EC2 is spun up and running, I can SSH into the box from the separate terminal. Yet, somehow the SSH during the build process fails.

Edit: I would also appreciate if this error is of consequence to the range setup. I don't see any Ansible playbook related to Kali.

Edit 2: Something isn't right w/ the key usage. Sshd log in Kali.
![image](https://user-images.githubusercontent.com/9037100/220814621-d60a8957-b511-46a1-aece-42dc3976bbbb.png)

These are failed key-base auth attempts during the build process. I have verified that the path to my SSH key in the `attack_range.yml` file is correct.

**Comment by j00c3** [comment]
@cmoreno94 so I think I figured the issue out, if you have not already. I believe you may be using an SSH key with a weaker public key algorithm that is being rejected by Kali image's sshd. Try generating a key pair using ED22519 and try again.

**Comment by cmoreno94** [comment]
Hey @j00c3 ! thank you for the update, I'll try it 👍
