### ISSUE TITLE
How do you locally add a Windows 10 or Windows 11 Client to the Attack Range?

### ISSUE THREAD

**Issue by vonn1e** [splunk/attack_range#744]
In the old version of the Attack Range, it was possible to have Vagrant build a local instance of Windows 10.  I know this can be done in the new attack range on Microsoft Azure; however, how do we add a local instance of Windows 10 or Windows 11?  Is this functionality possible?  If not, is it just a matter of me modifying the VagrantFile and adding the image name?  Any tutorials you can point me to?  THANKS!

**Comment by P4T12ICK** [comment]
Currently there is no out of the box way to use it. But happy to track it as a future feature. For now, you would need to customize the VagrantFiles.
