### ISSUE TITLE
Error During installation of Attack Range by using Dockers

### ISSUE THREAD

**Issue by Logeshrathinakumar** [splunk/attack_range#749]
Hello there,

I have being trying to install the Splunk attack range simulator by using the dockers image in AWS but i am getting the following errors can anyone help me to resolve the issue.

<img width="1091" alt="Screenshot 2023-02-09 at 2 51 21 PM" src="https://user-images.githubusercontent.com/124903994/218141756-273fd172-871d-48bd-aa7a-e27b0fc765b6.png">
<img width="1110" alt="Screenshot 2023-02-09 at 2 51 35 PM" src="https://user-images.githubusercontent.com/124903994/218141771-d981a0c6-18aa-410d-95cd-8ec083a21ca6.png">
<img width="1096" alt="Screenshot 2023-02-09 at 2 51 49 PM" src="https://user-images.githubusercontent.com/124903994/218141772-9dbc38cd-b40a-4567-8e0b-96f1d95c541b.png">

**Comment by patel-bhavin** [comment]
Hello @Logeshrathinakumar : It seems like that your aws cli user account doesn't have all the permissions required to build resources.

**Comment by Logeshrathinakumar** [comment]
Hello @patel-bhavin : Thank you for the response... i do have all the permissions but its doesn't work so i have again created new access key and done the job... and it works now...
