### ISSUE TITLE
splunkforwarder failed encounter in linux box

### ISSUE THREAD

**Issue by tccontre** [splunk/attack_range#754]
while building and testing in attack range 3.0 I notice it fails to setup splunk forwarder for linux box

![Screenshot 2023-02-16 at 11 12 43](https://user-images.githubusercontent.com/26181693/219337967-28e06f5f-6893-43bf-8a40-f6bf405dbd0a.png)

**Comment by cmoreno94** [comment]
Hello @tccontre! I had the same issue, I applied this [workaround](https://github.com/splunk/attack_range/issues/738)

**Comment by tccontre** [comment]
thank you @cmoreno94 for this workaround. I'll test it out:)

**Comment by patel-bhavin** [comment]
@tccontre :this should be fixed with this PR : https://github.com/splunk/attack_range/pull/758
