### ISSUE TITLE
Can't change the attack range name

### ISSUE THREAD

**Issue by cmoreno94** [splunk/attack_range#757]
Hello team,

I tried to deploy 2 attack range deployments with different names in the same region, but the new instance's names didn't change, even if I changed the name in the configuration menu:
`enter attack_range name, multiple can be build under different names in the same region`

My workaround:
I manually changed this file `attack_range/configs/attack_range_default.yml`:
`attack_range_name: "ar"`
to
`attack_range_name: "ar_test"`
and it worked!
 
Noticed in `attack_range/modules/configuration.py`, it is setting the `range_name` variable so, Do we need to change `range_name` to `attack_range_name`. TYIA!

```
get range name
     'type': 'text',
     'message': 'enter attack_range name, multiple can be build under different names in the same region',
     'name': 'range_name',
     'default': "ar",
```

**Comment by patel-bhavin** [comment]
@cmoreno94 : thank you for all these details! Here's the PR in which i tested the fix :

https://github.com/splunk/attack_range/pull/760
