### ISSUE TITLE
Apache Guacamole download URL is incorrect

### ISSUE THREAD

**Issue by j00c3** [splunk/attack_range#759]
The Apache Guacamole Server and Client download URL are outdated. Similar issue to #735, I suggest changing the URLs to the archive URLs going forward even for current versions.

Server: `/packer/ansible/roles/guacamole/tasks/guacamole_server.yml` line 5. Change `https://downloads.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz` to `https://archive.apache.org/dist/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz`

Client: `/packer/ansible/roles/guacamole/tasks/guacamole_client.yml` line 11. Change `https://downloads.apache.org/guacamole/1.4.0/binary/guacamole-1.4.0.war` to https://archive.apache.org/dist/guacamole/1.4.0/source/guacamole-client-1.4.0.tar.gz`

**Comment by patel-bhavin** [comment]
@j00c3 :  thank you very much for reporting this : we have updated these links in this PR:

https://github.com/splunk/attack_range/pull/760
