### ISSUE TITLE
Provide a Python requirements.txt file?

### ISSUE THREAD

**Issue by j00c3** [splunk/attack_range#761]
Been playing around a lot w/ setting up the range for my use cases, and I noticed that on "first" runs (clean runs), I'm having to install a number of Python packages. I had considered making a `requirements.txt` file myself and creating a PR, but I figured opening an issue may be better, since I may not have come across all dependency calls.

The `requirements.txt` file I created contains:

```pyyaml
ansible-runner
python_terraform
boto3
splunk-sdk
tabulate
jinja2
azure-mgmt-compute
azure-mgmt-resource
azure-identity
azure-mgmt-network
questionary
```

For your consideration.

**Comment by pyth0n1c** [comment]
Hi j00c3!  Thanks for the feedback. Did you first try to use Poetry to install all the requirements as described 
[here](https://attack-range.readthedocs.io/en/latest/Attack_Range_AWS.html#linux)? I realize these install instructions aren't immediately visible on the front page of the repo.

Or, alternatively, do you prefer the standard Create VirtualEnv / Activate Virtual Env / Install requirements.txt workflow as opposed to the one provided by poetry?  We find the poetry workflow to be easier as it does all these steps for you.  As such, that will likely continue to be our recommended path for installing the attack_range tooling (besides using the Docker image).  

However, it's _extremely_ easy for us to export the requirements stored in Poetry format into requirements.txt format and publish that to our repo if it meets a need. [It's a one-liner included in the poetry tool.](https://python-poetry.org/docs/cli/#export)

Can you give a little more detail about why requirements.txt would be useful as opposed to Poetry?

Thanks!

**Comment by j00c3** [comment]
I tried the Docker and the straight Mac command line way via Poetry. The Poetry route was...bit difficult. I've been working more with Docker for the past week or so. I can collect more data and return to this ticket, as I'm trying to see how I can customize this and to work out some kinks for my work team.

**Comment by pyth0n1c** [comment]
Hi @j00c3 - do you have any updates on issues with Poetry and/or MacOS? If you can provide some more detail, then we can either clarify the instructions around Poetry, fix an underlying issue, or take another approach.

**Comment by j00c3** [comment]
Ok, thanks for your patience. With the latest dev branch pull, I did not have to go through the individual pip package install process using MacOS/Poetry. 

I did however run into an issue where no matter what I try, the Packer Splunk AMI creation fails. Will open a ticket for this. Will close this issue.

**Comment by pyth0n1c** [comment]
@j00c3 , as an FYI we will still include a requirements.txt file based on your feedback.  This will make the project more accessible for many folks, so thank you for the feedback!
