### ISSUE TITLE
Guacamole not setup for "local" provider

### ISSUE THREAD

**Issue by soladev** [splunk/attack_range#762]
Hello, I'm in the process of installing Splunk Attack Range on a local server, and I saw in the ansible playbook that Apache Guacamole was disabled for the local provider, which is a shame since I've been looking forward to this feature.  

Do you plan to implement it for the local provider at a further release ?

**Comment by P4T12ICK** [comment]
I will have a look into this.

**Comment by Woahd** [comment]
i would also like this very much.

**Comment by P4T12ICK** [comment]
this should be fixed.
