### ISSUE TITLE
AWS Controller config index value is incorrect

### ISSUE THREAD

**Issue by j00c3** [splunk/attack_range#764]
In `module/aws_controller.py` lines 39-40:

```
elif image_name.startswith("windows-2019"):
    self.config['windows_servers'][i]['windows_ami'] = "Windows_Server-2016-English-Full-Base-*"
```
I'm guessing the value being assigned should say "Windows_Server-**_2019_**-English-Full-Base-*"

**Comment by P4T12ICK** [comment]
this should be fixed. Thank you for reporting the issue.
