### ISSUE TITLE
Local Build fails on Task: [windows_aurora_agent : install aurora-agent as a service with standard config]

### ISSUE THREAD

**Issue by Bob-The-User** [splunk/attack_range#765]
<img width="919" alt="Screenshot 2023-03-02 at 3 35 56 PM" src="https://user-images.githubusercontent.com/83099411/222545901-cc1c48eb-f716-43f8-bd27-fc3554f30797.png">

Everything was working fine a couple weeks ago. But recently I have had the attached errors on several systems.

**Comment by P4T12ICK** [comment]
I'm working on it. Thank you for reporting it.

**Comment by P4T12ICK** [comment]
Should be fixed

**Comment by Bob-The-User** [comment]
thanks, I'll give it a shot!

**Comment by Bob-The-User** [comment]
it looks like it made it past that error! Thanks again!
