### ISSUE TITLE
linux packer error

### ISSUE THREAD

**Issue by edwardxwu** [splunk/attack_range#768]
amazon-ebs.ubuntu-18-04: TASK [linux_sysmon : launch with config] ***************************************
amazon-ebs.ubuntu-18-04: fatal: [default]: FAILED! => {"changed": true, "cmd": "sysmon -accepteula -i /tmp/SysMonLinux-CatchAll.xml", "delta": "0:00:03.213770", "end": "2023-03-12 07:47:54.257545", "msg": "non-zero return code", "rc": 1, "start": "2023-03-12 07:47:51.043775", "stderr": "Created symlink /etc/systemd/system/multi-user.target.wants/sysmon.service → /etc/systemd/system/sysmon.service.\nJob for sysmon.service failed because the control process exited with error code.\nSee \"systemctl status sysmon.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Created symlink /etc/systemd/system/multi-user.target.wants/sysmon.service → /etc/systemd/system/sysmon.service.", "Job for sysmon.service failed because the control process exited with error code.", "See \"systemctl status sysmon.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}
amazon-ebs.ubuntu-18-04:
amazon-ebs.ubuntu-18-04: PLAY RECAP *********************************************************************
amazon-ebs.ubuntu-18-04: default                    : ok=38   changed=32   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
amazon-ebs.ubuntu-18-04:
==> amazon-ebs.ubuntu-18-04: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs.ubuntu-18-04: Terminating the source AWS instance...
==> amazon-ebs.ubuntu-18-04: Cleaning up any extra volumes...
==> amazon-ebs.ubuntu-18-04: Deleting temporary security group...
==> amazon-ebs.ubuntu-18-04: Deleting temporary keypair...
Build 'amazon-ebs.ubuntu-18-04' errored after 10 minutes 23 milliseconds: Error executing Ansible: Non-zero exit status: exit status 2

==> Wait completed after 10 minutes 23 milliseconds

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs.ubuntu-18-04: Error executing Ansible: Non-zero exit status: exit status 2

attack_range.yml:
linux_servers:
- hostname: ar-linux

**Comment by P4T12ICK** [comment]
Thank you for reporting this issue. We will work on it. As long as it's not working expected, you can use disable packer.

**Comment by P4T12ICK** [comment]
Potential Sysmon for Linux issue. See issue here:
https://github.com/Sysinternals/SysmonForLinux/issues/101
