### ISSUE TITLE
sysinternal task failing

### ISSUE THREAD

**Issue by edwardxwu** [splunk/attack_range#769]
module.windows-server.aws_instance.windows_server[0] (local-exec): TASK [red_team_tools : install sysinternals] ***********************************
module.windows-server.aws_instance.windows_server[0]: Still creating... [20m0s elapsed]
module.windows-server.aws_instance.windows_server[0]: Still creating... [20m10s elapsed]
module.windows-server.aws_instance.windows_server[0]: Still creating... [20m20s elapsed]
module.windows-server.aws_instance.windows_server[0]: Still creating... [20m30s elapsed]
module.windows-server.aws_instance.windows_server[0]: Still creating... [20m40s elapsed]
module.windows-server.aws_instance.windows_server[0] (local-exec): fatal: [35.167.70.142]: FAILED! => {"changed": true, "cmd": "C:\\\\ProgramData\\\\chocolatey\\\\bin\\\\choco.exe install sysinternals --fail-on-unfound --yes --no-progress --limit-output --timeout 2700 --ignore-checksums", "delta": "0:00:45.083319", "end": "2023-03-13 05:20:17.151977", "msg": "non-zero return code", "rc": 1, "start": "2023-03-13 05:19:32.068658", "stderr": "", "stderr_lines": [], "stdout": "Installing the following packages:\r\nsysinternals\r\nBy installing, you accept licenses for the packages.\r\n\r\nsysinternals v2023.3.9 [Approved]\r\nsysinternals package files install completed. Performing other installation steps.\r\nSysinternals Suite is going to be installed in 'C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools'\r\nDownloading sysinternals \r\n  from 'https://download.sysinternals.com/files/SysinternalsSuite.zip'\r\n\r\nDownload of SysinternalsSuite.zip (44.77 MB) completed.\r\nWARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.\r\nExtracting C:\\Users\\Administrator\\AppData\\Local\\Temp\\chocolatey\\sysinternals\\2023.3.9\\SysinternalsSuite.zip to C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools...\r\nC:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools\r\n ShimGen has successfully created a shim for accesschk.exe\r\n ShimGen has successfully created a shim for accesschk64.exe\r\n ShimGen has successfully created a shim for AccessEnum.exe\r\n ShimGen has successfully created a shim for ADExplorer.exe\r\n ShimGen has successfully created a shim for ADExplorer64.exe\r\n ShimGen has successfully created a shim for ADInsight.exe\r\n ShimGen has successfully created a shim for ADInsight64.exe\r\n ShimGen has successfully created a shim for adrestore.exe\r\n ShimGen has successfully created a shim for adrestore64.exe\r\n ShimGen has successfully created a shim for Autologon.exe\r\n ShimGen has successfully created a shim for Autologon64.exe\r\n ShimGen has successfully created a shim for Autoruns.exe\r\n ShimGen has successfully created a shim for Autoruns64.exe\r\n ShimGen has successfully created a shim for autorunsc.exe\r\n ShimGen has successfully created a shim for autorunsc64.exe\r\n ShimGen has successfully created a shim for Bginfo.exe\r\n ShimGen has successfully created a shim for Bginfo64.exe\r\n ShimGen has successfully created a shim for Cacheset.exe\r\n ShimGen has successfully created a shim for Cacheset64.exe\r\n ShimGen has successfully created a shim for Clockres.exe\r\n ShimGen has successfully created a shim for Clockres64.exe\r\n ShimGen has successfully created a shim for Contig.exe\r\n ShimGen has successfully created a shim for Contig64.exe\r\n ShimGen has successfully created a shim for Coreinfo.exe\r\n ShimGen has successfully created a shim for Coreinfo64.exe\r\n ShimGen has successfully created a shim for CPUSTRES.EXE\r\n ShimGen has successfully created a shim for ctrl2cap.exe\r\n ShimGen has successfully created a shim for Dbgview.exe\r\n ShimGen has successfully created a shim for dbgview64.exe\r\n ShimGen has successfully created a shim for Desktops.exe\r\n ShimGen has successfully created a shim for Desktops64.exe\r\n ShimGen has successfully created a shim for disk2vhd.exe\r\n ShimGen has successfully created a shim for disk2vhd64.exe\r\n ShimGen has successfully created a shim for diskext.exe\r\n ShimGen has successfully created a shim for diskext64.exe\r\n ShimGen has successfully created a shim for Diskmon.exe\r\n ShimGen has successfully created a shim for Diskmon64.exe\r\n ShimGen has successfully created a shim for DiskView.exe\r\n ShimGen has successfully created a shim for DiskView64.exe\r\n ShimGen has successfully created a shim for du.exe\r\n ShimGen has successfully created a shim for du64.exe\r\n ShimGen has successfully created a shim for efsdump.exe\r\n ShimGen has successfully created a shim for FindLinks.exe\r\n ShimGen has successfully created a shim for FindLinks64.exe\r\n ShimGen has successfully created a shim for handle.exe\r\n ShimGen has successfully created a shim for handle64.exe\r\n ShimGen has successfully created a shim for hex2dec.exe\r\n ShimGen has successfully created a shim for hex2dec64.exe\r\n ShimGen has successfully created a shim for junction.exe\r\n ShimGen has successfully created a shim for junction64.exe\r\n ShimGen has successfully created a shim for ldmdump.exe\r\n ShimGen has successfully created a shim for Listdlls.exe\r\n ShimGen has successfully created a shim for Listdlls64.exe\r\n ShimGen has successfully created a shim for livekd.exe\r\n ShimGen has successfully created a shim for livekd64.exe\r\n ShimGen has successfully created a shim for LoadOrd.exe\r\n ShimGen has successfully created a shim for LoadOrd64.exe\r\n ShimGen has successfully created a shim for LoadOrdC.exe\r\n ShimGen has successfully created a shim for LoadOrdC64.exe\r\n ShimGen has successfully created a shim for logonsessions.exe\r\n ShimGen has successfully created a shim for logonsessions64.exe\r\n ShimGen has successfully created a shim for movefile.exe\r\n ShimGen has successfully created a shim for movefile64.exe\r\n ShimGen has successfully created a shim for notmyfault.exe\r\n ShimGen has successfully created a shim for notmyfault64.exe\r\n ShimGen has successfully created a shim for notmyfaultc.exe\r\n ShimGen has successfully created a shim for notmyfaultc64.exe\r\n ShimGen has successfully created a shim for ntfsinfo.exe\r\n ShimGen has successfully created a shim for ntfsinfo64.exe\r\n ShimGen has successfully created a shim for pendmoves.exe\r\n ShimGen has successfully created a shim for pendmoves64.exe\r\n ShimGen has successfully created a shim for pipelist.exe\r\n ShimGen has successfully created a shim for pipelist64.exe\r\n ShimGen has successfully created a shim for portmon.exe\r\n ShimGen has successfully created a shim for procdump.exe\r\n ShimGen has successfully created a shim for procdump64.exe\r\n ShimGen has successfully created a shim for procexp.exe\r\n ShimGen has successfully created a shim for procexp64.exe\r\n ShimGen has successfully created a shim for Procmon.exe\r\n ShimGen has successfully created a shim for Procmon64.exe\r\n ShimGen has successfully created a shim for PsExec.exe\r\n ShimGen has successfully created a shim for PsExec64.exe\r\n ShimGen has successfully created a shim for psfile.exe\r\n ShimGen has successfully created a shim for psfile64.exe\r\n ShimGen has successfully created a shim for PsGetsid.exe\r\n ShimGen has successfully created a shim for PsGetsid64.exe\r\n ShimGen has successfully created a shim for PsInfo.exe\r\n ShimGen has successfully created a shim for PsInfo64.exe\r\n ShimGen has successfully created a shim for pskill.exe\r\n ShimGen has successfully created a shim for pskill64.exe\r\n ShimGen has successfully created a shim for pslist.exe\r\n ShimGen has successfully created a shim for pslist64.exe\r\n ShimGen has successfully created a shim for PsLoggedon.exe\r\n ShimGen has successfully created a shim for PsLoggedon64.exe\r\n ShimGen has successfully created a shim for psloglist.exe\r\n ShimGen has successfully created a shim for psloglist64.exe\r\n ShimGen has successfully created a shim for pspasswd.exe\r\n ShimGen has successfully created a shim for pspasswd64.exe\r\n ShimGen has successfully created a shim for psping.exe\r\n ShimGen has successfully created a shim for psping64.exe\r\n ShimGen has successfully created a shim for PsService.exe\r\n ShimGen has successfully created a shim for PsService64.exe\r\n ShimGen has successfully created a shim for psshutdown.exe\r\n ShimGen has successfully created a shim for psshutdown64.exe\r\n ShimGen has successfully created a shim for pssuspend.exe\r\n ShimGen has successfully created a shim for pssuspend64.exe\r\n ShimGen has successfully created a shim for RAMMap.exe\r\n ShimGen has successfully created a shim for RAMMap64.exe\r\n ShimGen has successfully created a shim for RDCMan.exe\r\n ShimGen has successfully created a shim for RegDelNull.exe\r\n ShimGen has successfully created a shim for RegDelNull64.exe\r\n ShimGen has successfully created a shim for regjump.exe\r\n ShimGen has successfully created a shim for ru.exe\r\n ShimGen has successfully created a shim for ru64.exe\r\n ShimGen has successfully created a shim for sdelete.exe\r\n ShimGen has successfully created a shim for sdelete64.exe\r\n ShimGen has successfully created a shim for ShareEnum.exe\r\n ShimGen has successfully created a shim for ShareEnum64.exe\r\n ShimGen has successfully created a shim for ShellRunas.exe\r\n ShimGen has successfully created a shim for sigcheck.exe\r\n ShimGen has successfully created a shim for sigcheck64.exe\r\n ShimGen has successfully created a shim for streams.exe\r\n ShimGen has successfully created a shim for streams64.exe\r\n ShimGen has successfully created a shim for strings.exe\r\n ShimGen has successfully created a shim for strings64.exe\r\n ShimGen has successfully created a shim for sync.exe\r\n ShimGen has successfully created a shim for sync64.exe\r\n ShimGen has successfully created a shim for Sysmon.exe\r\n ShimGen has successfully created a shim for Sysmon64.exe\r\n ShimGen has successfully created a shim for tcpvcon.exe\r\n ShimGen has successfully created a shim for tcpvcon64.exe\r\n ShimGen has successfully created a shim for tcpview.exe\r\n ShimGen has successfully created a shim for tcpview64.exe\r\n ShimGen has successfully created a shim for Testlimit.exe\r\n ShimGen has successfully created a shim for Testlimit64.exe\r\n ShimGen has successfully created a shim for vmmap.exe\r\n ShimGen has successfully created a shim for vmmap64.exe\r\n ShimGen has successfully created a shim for Volumeid.exe\r\n ShimGen has successfully created a shim for Volumeid64.exe\r\n ShimGen has successfully created a shim for whois.exe\r\n ShimGen has successfully created a shim for whois64.exe\r\n ShimGen has successfully created a shim for Winobj.exe\r\n ShimGen has successfully created a shim for Winobj64.exe\r\n ShimGen has successfully created a shim for ZoomIt.exe\r\n ShimGen has successfully created a shim for ZoomIt64.exe\r\n The install of sysinternals was successful.\r\n  Software installed to 'C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools'\r\n\r\nChocolatey installed 1/1 packages. \r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\n", "stdout_lines": ["Installing the following packages:", "sysinternals", "By installing, you accept licenses for the packages.", "", "sysinternals v2023.3.9 [Approved]", "sysinternals package files install completed. Performing other installation steps.", "Sysinternals Suite is going to be installed in 'C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools'", "Downloading sysinternals ", "  from 'https://download.sysinternals.com/files/SysinternalsSuite.zip'", "", "Download of SysinternalsSuite.zip (44.77 MB) completed.", "WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.", "Extracting C:\\Users\\Administrator\\AppData\\Local\\Temp\\chocolatey\\sysinternals\\2023.3.9\\SysinternalsSuite.zip to C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools...", "C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools", " ShimGen has successfully created a shim for accesschk.exe", " ShimGen has successfully created a shim for accesschk64.exe", " ShimGen has successfully created a shim for AccessEnum.exe", " ShimGen has successfully created a shim for ADExplorer.exe", " ShimGen has successfully created a shim for ADExplorer64.exe", " ShimGen has successfully created a shim for ADInsight.exe", " ShimGen has successfully created a shim for ADInsight64.exe", " ShimGen has successfully created a shim for adrestore.exe", " ShimGen has successfully created a shim for adrestore64.exe", " ShimGen has successfully created a shim for Autologon.exe", " ShimGen has successfully created a shim for Autologon64.exe", " ShimGen has successfully created a shim for Autoruns.exe", " ShimGen has successfully created a shim for Autoruns64.exe", " ShimGen has successfully created a shim for autorunsc.exe", " ShimGen has successfully created a shim for autorunsc64.exe", " ShimGen has successfully created a shim for Bginfo.exe", " ShimGen has successfully created a shim for Bginfo64.exe", " ShimGen has successfully created a shim for Cacheset.exe", " ShimGen has successfully created a shim for Cacheset64.exe", " ShimGen has successfully created a shim for Clockres.exe", " ShimGen has successfully created a shim for Clockres64.exe", " ShimGen has successfully created a shim for Contig.exe", " ShimGen has successfully created a shim for Contig64.exe", " ShimGen has successfully created a shim for Coreinfo.exe", " ShimGen has successfully created a shim for Coreinfo64.exe", " ShimGen has successfully created a shim for CPUSTRES.EXE", " ShimGen has successfully created a shim for ctrl2cap.exe", " ShimGen has successfully created a shim for Dbgview.exe", " ShimGen has successfully created a shim for dbgview64.exe", " ShimGen has successfully created a shim for Desktops.exe", " ShimGen has successfully created a shim for Desktops64.exe", " ShimGen has successfully created a shim for disk2vhd.exe", " ShimGen has successfully created a shim for disk2vhd64.exe", " ShimGen has successfully created a shim for diskext.exe", " ShimGen has successfully created a shim for diskext64.exe", " ShimGen has successfully created a shim for Diskmon.exe", " ShimGen has successfully created a shim for Diskmon64.exe", " ShimGen has successfully created a shim for DiskView.exe", " ShimGen has successfully created a shim for DiskView64.exe", " ShimGen has successfully created a shim for du.exe", " ShimGen has successfully created a shim for du64.exe", " ShimGen has successfully created a shim for efsdump.exe", " ShimGen has successfully created a shim for FindLinks.exe", " ShimGen has successfully created a shim for FindLinks64.exe", " ShimGen has successfully created a shim for handle.exe", " ShimGen has successfully created a shim for handle64.exe", " ShimGen has successfully created a shim for hex2dec.exe", " ShimGen has successfully created a shim for hex2dec64.exe", " ShimGen has successfully created a shim for junction.exe", " ShimGen has successfully created a shim for junction64.exe", " ShimGen has successfully created a shim for ldmdump.exe", " ShimGen has successfully created a shim for Listdlls.exe", " ShimGen has successfully created a shim for Listdlls64.exe", " ShimGen has successfully created a shim for livekd.exe", " ShimGen has successfully created a shim for livekd64.exe", " ShimGen has successfully created a shim for LoadOrd.exe", " ShimGen has successfully created a shim for LoadOrd64.exe", " ShimGen has successfully created a shim for LoadOrdC.exe", " ShimGen has successfully created a shim for LoadOrdC64.exe", " ShimGen has successfully created a shim for logonsessions.exe", " ShimGen has successfully created a shim for logonsessions64.exe", " ShimGen has successfully created a shim for movefile.exe", " ShimGen has successfully created a shim for movefile64.exe", " ShimGen has successfully created a shim for notmyfault.exe", " ShimGen has successfully created a shim for notmyfault64.exe", " ShimGen has successfully created a shim for notmyfaultc.exe", " ShimGen has successfully created a shim for notmyfaultc64.exe", " ShimGen has successfully created a shim for ntfsinfo.exe", " ShimGen has successfully created a shim for ntfsinfo64.exe", " ShimGen has successfully created a shim for pendmoves.exe", " ShimGen has successfully created a shim for pendmoves64.exe", " ShimGen has successfully created a shim for pipelist.exe", " ShimGen has successfully created a shim for pipelist64.exe", " ShimGen has successfully created a shim for portmon.exe", " ShimGen has successfully created a shim for procdump.exe", " ShimGen has successfully created a shim for procdump64.exe", " ShimGen has successfully created a shim for procexp.exe", " ShimGen has successfully created a shim for procexp64.exe", " ShimGen has successfully created a shim for Procmon.exe", " ShimGen has successfully created a shim for Procmon64.exe", " ShimGen has successfully created a shim for PsExec.exe", " ShimGen has successfully created a shim for PsExec64.exe", " ShimGen has successfully created a shim for psfile.exe", " ShimGen has successfully created a shim for psfile64.exe", " ShimGen has successfully created a shim for PsGetsid.exe", " ShimGen has successfully created a shim for PsGetsid64.exe", " ShimGen has successfully created a shim for PsInfo.exe", " ShimGen has successfully created a shim for PsInfo64.exe", " ShimGen has successfully created a shim for pskill.exe", " ShimGen has successfully created a shim for pskill64.exe", " ShimGen has successfully created a shim for pslist.exe", " ShimGen has successfully created a shim for pslist64.exe", " ShimGen has successfully created a shim for PsLoggedon.exe", " ShimGen has successfully created a shim for PsLoggedon64.exe", " ShimGen has successfully created a shim for psloglist.exe", " ShimGen has successfully created a shim for psloglist64.exe", " ShimGen has successfully created a shim for pspasswd.exe", " ShimGen has successfully created a shim for pspasswd64.exe", " ShimGen has successfully created a shim for psping.exe", " ShimGen has successfully created a shim for psping64.exe", " ShimGen has successfully created a shim for PsService.exe", " ShimGen has successfully created a shim for PsService64.exe", " ShimGen has successfully created a shim for psshutdown.exe", " ShimGen has successfully created a shim for psshutdown64.exe", " ShimGen has successfully created a shim for pssuspend.exe", " ShimGen has successfully created a shim for pssuspend64.exe", " ShimGen has successfully created a shim for RAMMap.exe", " ShimGen has successfully created a shim for RAMMap64.exe", " ShimGen has successfully created a shim for RDCMan.exe", " ShimGen has successfully created a shim for RegDelNull.exe", " ShimGen has successfully created a shim for RegDelNull64.exe", " ShimGen has successfully created a shim for regjump.exe", " ShimGen has successfully created a shim for ru.exe", " ShimGen has successfully created a shim for ru64.exe", " ShimGen has successfully created a shim for sdelete.exe", " ShimGen has successfully created a shim for sdelete64.exe", " ShimGen has successfully created a shim for ShareEnum.exe", " ShimGen has successfully created a shim for ShareEnum64.exe", " ShimGen has successfully created a shim for ShellRunas.exe", " ShimGen has successfully created a shim for sigcheck.exe", " ShimGen has successfully created a shim for sigcheck64.exe", " ShimGen has successfully created a shim for streams.exe", " ShimGen has successfully created a shim for streams64.exe", " ShimGen has successfully created a shim for strings.exe", " ShimGen has successfully created a shim for strings64.exe", " ShimGen has successfully created a shim for sync.exe", " ShimGen has successfully created a shim for sync64.exe", " ShimGen has successfully created a shim for Sysmon.exe", " ShimGen has successfully created a shim for Sysmon64.exe", " ShimGen has successfully created a shim for tcpvcon.exe", " ShimGen has successfully created a shim for tcpvcon64.exe", " ShimGen has successfully created a shim for tcpview.exe", " ShimGen has successfully created a shim for tcpview64.exe", " ShimGen has successfully created a shim for Testlimit.exe", " ShimGen has successfully created a shim for Testlimit64.exe", " ShimGen has successfully created a shim for vmmap.exe", " ShimGen has successfully created a shim for vmmap64.exe", " ShimGen has successfully created a shim for Volumeid.exe", " ShimGen has successfully created a shim for Volumeid64.exe", " ShimGen has successfully created a shim for whois.exe", " ShimGen has successfully created a shim for whois64.exe", " ShimGen has successfully created a shim for Winobj.exe", " ShimGen has successfully created a shim for Winobj64.exe", " ShimGen has successfully created a shim for ZoomIt.exe", " ShimGen has successfully created a shim for ZoomIt64.exe", " The install of sysinternals was successful.", "  Software installed to 'C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools'", "", "Chocolatey installed 1/1 packages. ", " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log)."]}

module.windows-server.aws_instance.windows_server[0] (local-exec): PLAY RECAP *********************************************************************
module.windows-server.aws_instance.windows_server[0] (local-exec): 35.167.70.142              : ok=34   changed=31   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

**Comment by P4T12ICK** [comment]
related to #768

**Comment by P4T12ICK** [comment]
the installation of sysinternals is not always super stable, therefore I added a ignore_errors for this step.

**Comment by edwardxwu** [comment]
it seems to not error out and cause the windows hosts to be half-baked anymore
