### ISSUE TITLE
HTTP Error 401 when building splunk_server

### ISSUE THREAD

**Issue by irwan-ismail** [splunk/attack_range#780]
I'm getting the following error when building splunk_server. Any thoughts on what went wrong?

TASK [splunk_server : download splunk-add-on-for-microsoft-windows_840.tgz from S3 bucket] ***
changed: [ar-splunk-attack-range-key-pair-ar]

TASK [splunk_server : Install splunk-add-on-for-microsoft-windows_840.tgz via REST] ***
fatal: [ar-splunk-attack-range-key-pair-ar]: FAILED! => {"cache_control": "private", "changed": false, "connection": "Close", "content_length": "130", "content_type": "text/xml; charset=UTF-8", "date": "Fri, 24 Mar 2023 20:39:42 GMT", "elapsed": 0, "msg": "Status code was 401 and not [200, 201]: HTTP Error 401: Unauthorized", "redirected": false, "server": "Splunkd", "status": 401, "url": "https://127.0.0.1:8089/services/apps/local", "vary": "Cookie, Authorization", "www_authenticate": "Basic realm=\"/splunk\"", "x_content_type_options": "nosniff", "x_frame_options": "SAMEORIGIN"}                                    

PLAY RECAP *********************************************************************
ar-splunk-attack-range-key-pair-ar : ok=54   changed=5    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0                                                        

Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.                                    
2023-03-24 20:39:43,963 - ERROR - attack_range - vagrant failed to build

**Comment by P4T12ICK** [comment]
Do you run the latest version of Attack Range develop branch? Can you try it again by first destroying the Attack Range and then run build again?

**Comment by dagar741** [comment]
I am getting the same error and have not been able to build this locally with Virtualbox.  I have tried it several times over the past few months, doing a git pull, vagrant box update ,and then destroy and build again.  I can't get past this error, but have not had the time to dig into the code much.

**Comment by iosonogio** [comment]
I experienced this error too.
It disappeared after I detroyed and re-built again.
But the root cause is not clear, it seems it happened when re-building after the first attempt failed (and without detroying first).

**Comment by P4T12ICK** [comment]
I tested it today and I didn't run into the issue, therefore it is very difficult for me to debug it.
