### ISSUE TITLE
Docker - Azure - Multiple IP Whitelist values not parsed correctly results in Attackrange open to any public IP

### ISSUE THREAD

**Issue by alexzorila** [splunk/attack_range#782]
Hi Team,

When configuring the attack range from Docker to be used with Azure, specifying more than 1 public IP allowed to reach the attack range is not parsed correctly and results in opening the range to any public ip. This persists when using the build wizard or manually editing the attack_range.yml file.

There seems to be an error in parsing comma delimited values that ends up showing the 2 IP addresses as a single value in the Terraform config instead of a list of 2 values.

**Example Attack Range Config Wizard**

![image](https://user-images.githubusercontent.com/19607232/229375963-aeefeb15-a443-41b9-862e-fd0a70be6ec5.png)

**Resulting Terraform config**

![image](https://user-images.githubusercontent.com/19607232/229375919-d1056c74-4964-4b70-96d1-54867a195972.png)

**Resulting Error**

![image](https://user-images.githubusercontent.com/19607232/229376061-ea3010c8-5322-40ab-90b4-aef3573c56ad.png)

**Comment by GabrielSaul** [comment]
Hey there, I'm having the same issue. I've tried changing the values manually in the YML file, but it doesn't accept the necessary tokens. I've seen online that Azure is expecting an array of values, thus the syntax of @("<ADR_1>", "<ADR_2>") would suffice, but isn't accepted in the YML file. I'm at a loss currently. For now, I manually change the NSGs after it has terraformed for one IP address, but this can get tiring.

**Comment by P4T12ICK** [comment]
Thanks for reporting this. I will have a look into this.
