### ISSUE TITLE
Docker - AWS - Local-exec provisioner error

### ISSUE THREAD

**Issue by 3xtreme3** [splunk/attack_range#783]
Hi guys, I need a hand!
Anyone have experienced following error before?
[3xtreme3_#783_Error local-exec provisioner.txt](https://github.com/splunk/attack_range/files/11466851/3xtreme3_.783_Error.local-exec.provisioner.txt)

**Comment by P4T12ICK** [comment]
Hi @3xtreme3 , 
the first issue is regarding installation of Sysmon Linux, which we reported to the Sysmon for Linux team and got recently some feedback how to fix it. We are currently working on it. 
For some guidnace, how to install Splunk SOAR, you can check my latest reply in this issue:
https://github.com/splunk/attack_range/issues/776
