### ISSUE TITLE
[aws] 'nginx_web_proxy_host' is undefined

### ISSUE THREAD

**Issue by YungBinary** [splunk/attack_range#795]
Hello,

I'm using the aws deployment for Attack Range and running into the following error for the Nginx server:

```
amazon-ebs.nginx-web-proxy: TASK [nginx_web_proxy : copy default.conf to add the proxy information] ********
amazon-ebs.nginx-web-proxy: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'nginx_web_proxy_host' is undefined
amazon-ebs.nginx-web-proxy: fatal: [default]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'nginx_web_proxy_host' is undefined"}
```

This error below might also be related:

```
 TASK [nginx_web_proxy : setup to start at boot] ********************************
│ fatal: [3.16.78.25]: FAILED! => {"changed": true, "cmd": ["/opt/splunkforwarder/bin/splunk", "enable", "boot-start"], "delta": "0:00:00.031899", "end": "2023-05-11
│ 01:16:09.987990", "msg": "non-zero return code", "rc": 255, "start": "2023-05-11 01:16:09.956091", "stderr": "splunk is currently running, please stop it before running
│ enable/disable boot-start", "stderr_lines": ["splunk is currently running, please stop it before running enable/disable boot-start"], "stdout": "", "stdout_lines": []}
```

**Comment by P4T12ICK** [comment]
Thank you for reporting it. We will work on it.

**Comment by ajburnell** [comment]
Having this problem also.
The error is coming from:
`packer/ansible/roles/nginx_web_proxy/templates/default.conf.j2`

Line 10:
` proxy_pass   http://{{nginx_web_proxy_host}}:{{nginx_web_proxy_port}};`

These variables don't exist.

They do exist in a slightly different format in:
[terraform/aws/variables.tf](https://github.com/splunk/attack_range/blob/768a981d21254249e305e4683587e613e5146b9d/terraform/aws/variables.tf#L85)

```
proxy_server_ip = "10.0.1.12"
proxy_server_port = "8000"
```

The only problem is that during the Packer build, it doesn't actually see these variables from what I can gather. I added the these two default variables into nginx_web_proxy.yml in the Packer Ansible configuration, and amended the variable names in the .j2 file to be consistent with the naming across the rest of the config. 

If the IP varies from this then the NGINX post config Ansible playbook will overwrite the config anyway. If this is an acceptable solution I'll submit a pull request. It worked in my testing. (Although fails on the next unrelated task anyway which I'll look at next).

**Comment by ajburnell** [comment]
The next failing task in the AWS Packer build was:
` Use 'systemctl start SplunkForwarder' to start the service. Root permission is required. Login as root user or use sudo."]}`

Swapping out:
```
- name: restart splunk
  become: true
  command: "/opt/splunkforwarder/bin/splunk restart"
```

for:
```
- name: restart splunk
  become: true
  service:
    name: SplunkForwarder
    state: restarted
```
in
https://github.com/splunk/attack_range/blob/768a981d21254249e305e4683587e613e5146b9d/packer/ansible/roles/nginx_web_proxy/tasks/main.yml

seems to have done the job...

**Comment by P4T12ICK** [comment]
merged the bugfix. Thank you
