### ISSUE TITLE
[aws] Guacamole 1.5.X+ Error "Public key authentication failed: Unable to extract public key from private key."

### ISSUE THREAD

**Issue by YungBinary** [splunk/attack_range#797]
I'm using the latest changes and running into the following error. Note, this error does not happen when connecting to Windows servers, but it does happen with all other servers. I am able to ssh in manually but I am not able to connect via Guacamole. Resources were deployed to AWS.

I discovered this error in the logs:

```
guacd[504233]: Public key authentication failed: Unable to extract public key from private key.
```

![image](https://github.com/splunk/attack_range/assets/93540406/efa8ea7a-887a-44e7-802b-0b778d177e9b)

Updates:

- Reverted to Guacamole 1.4.0 and no longer having issues, except for the Kali VM I am still unable to ssh into, see "guacamole_server.yml" - I have located the commit where the version was upgraded to 1.5.0 -> 4a5a7b794a3b775001d0d65a73405df4207d6621
- Found a workaround for Kali and 1.4.0 is working, by adding the rsa algorithm to sshd with the following commands:

echo -e "HostKeyAlgorithms=ssh-rsa\nPubkeyAcceptedAlgorithms=+ssh-rsa" | sudo tee -a /etc/ssh/sshd_config
sudo systemctl restart sshd

**Comment by P4T12ICK** [comment]
We integrated this command as part off Ansible and it should work now. Thank you for reporting.
