### ISSUE TITLE
[Packer Build] Failed to Delete AWS Instances

### ISSUE THREAD

**Issue by 3xtreme3** [splunk/attack_range#798]
I seems to have an issue on destroying instances when build with packer.

![image](https://github.com/splunk/attack_range/assets/81975870/3d3149b9-f88e-4709-9469-a840044c10bf)

**Comment by P4T12ICK** [comment]
I'm currently working on this issue.

**Comment by P4T12ICK** [comment]
This should be fixed. Thank you.

**Comment by Egotism3851** [comment]
How do I implement this fix? I am having this issue and to want to destroy everything without doing it manually
