### ISSUE TITLE
Missing tags on dockerhub - only available is "latest"

### ISSUE THREAD

**Issue by mkolasinski-splunk** [splunk/attack_range#801]
Currently docker image is always pushed with single tag - latest: 
https://hub.docker.com/r/splunk/attack_range/tags
https://github.com/splunk/attack_range/blob/develop/.github/workflows/publish-docker-image.yml#L38
This is not enough if user wants to pin particular image version.

I would like to refactor CI to build, publish and push docker image to dockerhub in single workflow, based on semantic versioning.
Let me know what are your thoughts on this idea.

**Comment by P4T12ICK** [comment]
Yes I think this is a good idea. Then we also need to change our workflow of tagging and releasing a Attack Range version in a regular base.

**Comment by P4T12ICK** [comment]
this is available now
