### ISSUE TITLE
Error when starting local

### ISSUE THREAD

**Issue by WaughB** [splunk/attack_range#802]
I am on Windows 11 running this all inside of a fresh Ubuntu 20.04.02 VM. 

Here are the steps I have taken so far:
```
  git clone https://github.com/splunk/attack_range.git
  cd attack_range
  Install vagrant and virtualbox

  apt-get update
  apt-get install virtualbox
  wget https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb
  apt install ./vagrant_2.2.19_x86_64.deb

  curl -sSL https://install.python-poetry.org/ | python -
  poetry shell
  poetry install

  python attack_range.py configure
```
Options I chose are:
* local
* changeme
* No windows server
* Yes linux server
* No SOAR

I receive a confirmation of the following:
```
> configuration file was written to: /home/brett/Desktop/attack_range/attack_range.yml, run 'python attack_range.py build' to create a new attack_range you can also edit this file to configure advance parameters
> setup has finished successfully ... exiting
```
I got some build errors initially that had this error:
```
The IP address configured for the host-only network is not within the allowed ranges. Please update the address used to be within the allowed ranges and run the command again. 

Address: 10.0.1.12
Ranges: 192.168.56.0/21

Valid ranges can be modified in the /etc/vbox/networks.cond file. For more information including valid format see:
https://www.virtualbox.org/manual/ch06.html#network_hostonly
```

And I was able to resolve that by editing ```/etc/vbox/networks.conf ```  to ```* 0.0.0.0/0 ::/0```

Then I got this error:
```
There was an error while executing 'VBoxManage', a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e691c23c-a9e1-4bb2-8d61-93d3c9a2c9e4", "--type",  "gui"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005),  component ConsoleWrap, interface IConsole
```

Which able to be resolved by running ```VBoxManage modifyvm <YourVirtualMachineName> --nested-hw-virt on``` in ```C:\Program Files\Oracle\VirtualBox``` .

However, when I try to build I get this:
```
There was an error while executing 'VBoxManage', a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e691c23c-a9e1-4bb2-8d61-93d3c9a2c9e4", "--type",  "gui"]

Stderr: VBoxManage: error: The machine 'ar-splunk' is already locked by a session (or being locked or unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), ComSafeArrayAsInParam(aBstrEnv), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp
```

I tried restarting several times, but that did not make the program go away. Any ideas?

Also, I am trying to run a few demo/tutorial-level examples on my local machine before I start doing things on AWS. Is there a reference with any demo examples that work out of the box?

Thank you all in advance!

**Comment by P4T12ICK** [comment]
Sorry for my late reply. I'm currently working on that the ip addresses used by attack range local are in the default network 192.168.56.0/21. I would try to run first the destroy command and then I would make sure that there is no ar-splunk vm in the GUI of VirtualBox. I even had to delete a remaning folder under [your_windows_home_dir]/VirtualBox VMs.
Do you run ubuntu 20.04 in wsl2? Is VirtualBox running in Windows?

**Comment by P4T12ICK** [comment]
The default IP address range for local is changed to 192.168.56.0/21.
