### ISSUE TITLE
Aurora EDR removes AtomicsFolder

### ISSUE THREAD

**Issue by alekwisnia** [splunk/attack_range#807]
I am not able to perform ART simulation due to Aurora EDR turned on. I got results similar to this:

`TASK [atomic_red_team : debug] *************************************************
ok: [my_ip] => {
    "output_art.stdout_lines": [
        "PathToAtomicsFolder = ",
        "",
        "Found 0 atomic tests applicable to windows platform for Technique "
    ]
}`

When I manually login to Windows machines and turn it off it works fine for me. Please consider disabling it in the future releases.

**Comment by P4T12ICK** [comment]
This should be fixed. The installation of Aurora EDR is optional now.
