### ISSUE TITLE
SCP transfer error to Splunk server during packer build

### ISSUE THREAD

**Issue by neokjames** [splunk/attack_range#812]
Receiving the below error to do with SCP command syntax when running a new image build.

Using Docker, on AWS.

"**unknown option -- O**"

``amazon-ebs.splunk-ubuntu: Found Image ID: ami-08631d91a2bc26238
==> amazon-ebs.splunk-ubuntu: Creating temporary keypair: packer_64942f05-921d-a948-1edf-0ab2a8712669
==> amazon-ebs.splunk-ubuntu: Creating temporary security group for this instance: packer_64942f06-9e56-a71e-a95f-7a8d85c239d0
==> amazon-ebs.splunk-ubuntu: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs.splunk-ubuntu: Launching a source AWS instance...
amazon-ebs.splunk-ubuntu: Instance ID: i-04c40ebcb8d8e25e0
==> amazon-ebs.splunk-ubuntu: Waiting for instance (i-04c40ebcb8d8e25e0) to become ready...
==> amazon-ebs.splunk-ubuntu: Using SSH communicator to connect: 54.206.56.76
==> amazon-ebs.splunk-ubuntu: Waiting for SSH to become available...
==> amazon-ebs.splunk-ubuntu: Connected to SSH!
==> amazon-ebs.splunk-ubuntu: Provisioning with Ansible...
amazon-ebs.splunk-ubuntu: Setting up proxy adapter for Ansible....
==> amazon-ebs.splunk-ubuntu: Executing Ansible: ansible-playbook -e packer_build_name="splunk-ubuntu" -e packer_builder_type=amazon-ebs --ssh-extra-args '-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa' --scp-extra-args '-O' --extra-vars byo_splunk="0" byo_splunk_ip="" ingest_bots3_data="0" install_dltk="0" install_es="0" s3_bucket_url="https://attack-range-appbinaries.s3-us-west-2.amazonaws.com" splunk_es_app="splunk-enterprise-security_701.spl" splunk_image="splunk-v3-0-0" splunk_uf_url="https://download.splunk.com/products/universalforwarder/releases/9.0.5/linux/splunkforwarder-9.0.5-e9494146ae5c-linux-2.6-amd64.deb" splunk_uf_win_url="https://download.splunk.com/products/universalforwarder/releases/9.0.5/windows/splunkforwarder-9.0.5-e9494146ae5c-x64-release.msi" splunk_url="https://download.splunk.com/products/splunk/releases/9.0.5/linux/splunk-9.0.5-e9494146ae5c-Linux-x86_64.tgz" attack_range_name="ar" attack_range_password="infected" aurora_agent="1" carbon_black_cloud="0" carbon_black_cloud_agent_name="installer_vista_win7_win8-64-3.8.0.627.msi" carbon_black_cloud_company_code="" carbon_black_cloud_s3_bucket="" cloud_provider="aws" crowdstrike_agent_name="WindowsSensor.exe" crowdstrike_customer_ID="" crowdstrike_falcon="0" crowdstrike_logs_access_key_id="" crowdstrike_logs_region="" crowdstrike_logs_secret_access_key="" crowdstrike_logs_sqs_url="" ip_whitelist="0.0.0.0/0" key_name="root-30536" statepath="/attack_range/modules/../terraform/aws/state/ar.terraform.tfstate" use_prebuilt_images_with_packer="0" version="3.0.0" -e ansible_ssh_private_key_file=/tmp/ansible-key512671240 -i /tmp/packer-provisioner-ansible1350331007 /attack_range/packer/ansible/splunk_server.yml
amazon-ebs.splunk-ubuntu: [DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks
amazon-ebs.splunk-ubuntu: instead. This feature will be removed in version 2.16. Deprecation warnings can
amazon-ebs.splunk-ubuntu:  be disabled by setting deprecation_warnings=False in ansible.cfg.
amazon-ebs.splunk-ubuntu:
amazon-ebs.splunk-ubuntu: PLAY [all] *********************************************************************
amazon-ebs.splunk-ubuntu:
amazon-ebs.splunk-ubuntu: TASK [linux_common : Upgrade all apt packages] *********************************
amazon-ebs.splunk-ubuntu: fatal: [default]: FAILED! => {"msg": "failed to transfer file to /root/.ansible/tmp/ansible-local-11836vcwsj7y/tmpqrg6sfx7 /home/ubuntu/.ansible/tmp/ansible-tmp-1687432990.4262993-1188-151977172129425/AnsiballZ_apt.py:\n\nunknown option -- O\r\nusage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]\n            [-J destination] [-l limit] [-o ssh_option] [-P port]\n            [-S program] source ... target\n"}
amazon-ebs.splunk-ubuntu:
amazon-ebs.splunk-ubuntu: PLAY RECAP *********************************************************************
amazon-ebs.splunk-ubuntu: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
amazon-ebs.splunk-ubuntu:
==> amazon-ebs.splunk-ubuntu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs.splunk-ubuntu: Terminating the source AWS instance...
==> amazon-ebs.splunk-ubuntu: Cleaning up any extra volumes...
==> amazon-ebs.splunk-ubuntu: Deleting temporary security group...
==> amazon-ebs.splunk-ubuntu: Deleting temporary keypair...
Build 'amazon-ebs.splunk-ubuntu' errored after 1 minute 43 seconds: Error executing Ansible: Non-zero exit status: exit status 2``

**Comment by neokjames** [comment]
Looks like this might be to do with Ansible within the Docker container, or, the scp binary used in the Docker container has no "O" flag?

**Comment by neokjames** [comment]
Does seem to be the scp binary in the Docker container has no 'O' flag.

```
# scp -v
usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
```

**Comment by neokjames** [comment]
Introduced in a recent merge --scp-extra-args

**Comment by P4T12ICK** [comment]
this should be fixed. Can you check again?

**Comment by P4T12ICK** [comment]
It still exists. I will check it again.

**Comment by P4T12ICK** [comment]
this should be fixed
