### ISSUE TITLE
References to Ubuntu 18.04 still exist and is preventing the linux machine from installing tools

### ISSUE THREAD

**Issue by sothisagain** [splunk/attack_range#826]
In the terraform/aws/variables.tf file it still references Ubuntu 18.04 this needs to be updated to Ubuntu 22.04
---
variable "linux_servers" {
  type = list
  default = [
    {
        hostname = "ar-linux"
        image = "ubuntu-18-04-v2-0-0"
        sysmon_config = "configs/SwiftOnSecurity.xml"
    }
  ]
}

**Comment by P4T12ICK** [comment]
this should't be a problem as it will be overwritten during execution.

**Comment by sothisagain** [comment]
It's not been overwritten on my build
