### ISSUE TITLE
Typo in file name terraform/aws/ressources.tf

### ISSUE THREAD

**Issue by sothisagain** [splunk/attack_range#827]
File name terraform/aws/ressources.tf should be terraform/aws/resources.tf 

also in docs/source/Control_Attack_Range.md

docs/source/Control_Attack_Range.md:Destroys an Attack Range and deletes/deprovision all used ressources
docs/source/Control_Attack_Range.md:Shows the ressources of an Attack Range

**Comment by P4T12ICK** [comment]
Thank you. Will fix it.

**Comment by P4T12ICK** [comment]
Fixed it. Thank you.
