### ISSUE TITLE
Allow file transfers in guacamole to allow for additional tools to be easily installed

### ISSUE THREAD

**Issue by sothisagain** [splunk/attack_range#828]
To facilitate the install of additional tools into the environment please add additional parameters to the terraform/ansible/roles/guacamole/templates/user-mapping.xml file for windows machines

<param name="enable-drive">true</param>
<param name="drive-path">/shared-folder</param>

**Comment by P4T12ICK** [comment]
Thanks for the feedback. I just implemented it.
