### ISSUE TITLE
cmd hostname casue an issue 

### ISSUE THREAD

**Issue by SamiNM** [splunk/attack_range#829]
Hi 

I followed the same steps as per the document for attack_range_local.
However I keep getting this issue, see the image below:

//// These two lines happened just before the error 
    ar-win-attack-range-key-pair-ar-0: WinRM execution_time_limit: PT2H
    ar-win-attack-range-key-pair-ar-0: WinRM transport: plaintext

//// This is the error message 
An error occurred executing a remote WinRM command.

Shell: Cmd
Command: hostname
Message: [WSMAN ERROR CODE: 2147942421]: <f:WSManFault Code='2147942421' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The device is not ready. </f:ProviderFault></f:Message></f:WSManFault>

/// and this is the last line printed after the error message
2023-07-20 23:42:25,838 - ERROR - attack_range - vagrant failed to build

**Comment by P4T12ICK** [comment]
I never saw this issue. It can be related to your Virtualbox or Vagrant installation.
