### ISSUE TITLE
BYO Splunk issues

### ISSUE THREAD

**Issue by Bob-The-User** [splunk/attack_range#836]
No matter what when I try to set BYO Splunk it stands up its own splunk.

**Comment by TrashMaster112** [comment]
I am also having the same issue when trying to use the attack_range_default.yml for configuring the range.

**Comment by Bob-The-User** [comment]
i'm going to close this ticket, as it seems a non-issue. It still works, but there seems to be no good reason to have it stand up an internal Splunk server when you do BYO Splunk
