### ISSUE TITLE
[Feature Request - terraform plan]

### ISSUE THREAD

**Issue by chaeheekang** [splunk/attack_range#845]
I know that Terraform has a command called the `terraform plan` command that shows the prediction results in advance about what kind of infrastructure the defined code will create.

Before building an attack range server, I also want to use the plan function to know in advance whether there will be any errors.
For example, if I run `python attack_range.py plan` I can predict the infrastructure to be created.

Can you add that feature?

Thanks!

**Comment by P4T12ICK** [comment]
Hello @chaeheekang , thank you for this feature request. I will talk to the team and let you know if we can add it.
