### ISSUE TITLE
Update Documentation for AWS / Azure Instance Configuration

### ISSUE THREAD

**Issue by abhinavkakku** [splunk/attack_range#846]
The Documentation for changing the default AWS Instance type states the following :- 
https://github.com/splunk/attack_range/wiki/Configurations

This is configured in attack_range/attack_range.conf for the instance type globally.

But the attack_range/attack_range.conf does not exists.

attack_range/attack_range.yml exists.
And updating this does not works.

Please update the documentation.

**Comment by abhinavkakku** [comment]
The other part of documentation where we modify the terraform modules (each one as required), might work.

**Comment by P4T12ICK** [comment]
Hello @abhinavkakku , the GitHub wiki is depreacted as it can be seen here
https://github.com/splunk/attack_range/wiki
Please use the new official docs:
https://attack-range.readthedocs.io/en/latest/
