### ISSUE TITLE
Prelude Operator : End of line/support

### ISSUE THREAD

**Issue by LetMeR00t** [splunk/attack_range#848]
Hello,

I recently heard that the Prelude Operator will not be supported by the end of April 2024. 
What is the impact on your project after this date ? Do you have any roadmap plan to change something about it already ? 

Thank you

**Comment by P4T12ICK** [comment]
Hi @LetMeR00t, I didn't hear it yet. Can you share a link with me?
When this is the case, we would remove Prelude Operator from Attack Range. You could still use the existing tools such as Atomic Red Team and PurpleSharp.

**Comment by LetMeR00t** [comment]
Hi @P4T12ICK 
The official statement that I heard is below, basically with the release of Detect, the usage of Operator has declined significantly and it seems that the decision have been made to 'end of life' the Operator product. There is a kind of mandatory transition to Prelude Detect. The official date seems to be April 30 2024.  I didn’t find any communication.
Thank you

**Comment by P4T12ICK** [comment]
Thank you for the info. We will probably remove it until April.
