### ISSUE TITLE
Tried installing poetry on ubuntu 18.04 based on instructions for linux

### ISSUE THREAD

**Issue by configmanCooper** [splunk/attack_range#851]
Based on instructions for local range local install on linux as following:

Install and run poetry

curl -sSL https://install.python-poetry.org/ | python -
poetry shell
poetry install

When trying to do this, it has a syntax error
Using python3, it starts to run, but install fails as it can't find version 1.6.1

**Comment by gowthamarajr** [comment]
@configmanCooper Could you please provide the complete Error you are getting ?
