### ISSUE TITLE
Installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by configmanCooper** [splunk/attack_range#852]
After much trouble shooting I was able to get poetry installed and get to the last steps provided in documentation of how to install on a standalone linux on ubuntu 18.04

I now get the following errors, and have tried apt-get install, pip install, and pip3 install for all of the packages

python attack_range.py configure
Traceback (most recent call last):
  File "attack_range.py", line 5, in <module>
    from modules.config_handler import ConfigHandler
ImportError: No module named modules.config_handler

python3 attack_range.py configure
Traceback (most recent call last):
  File "attack_range.py", line 6, in <module>
    from modules.aws_controller import AwsController
  File "/home/cptadmin/Downloads/attack_range/modules/aws_controller.py", line 2, in <module>
    import ansible_runner
ModuleNotFoundError: No module named 'ansible_runner'

I have installed all the packages as I said (ansible_runner, Config , in pip and pip3) and I still receive these errors

**Comment by P4T12ICK** [comment]
This is very difficult to debug from our side. Can you try to use the docker image which comes with all needed packages pre-installed?

**Comment by configmanCooper** [comment]
I opened this ticket months ago so I've moved on to other projects

However, I would have loved to use docker. I ran into many issues with that as well

To recreate many issues just Literally just download a new Ubuntu iso and try to run through the steps in the splunk range and try to actually start up a range. Unless things have been fixed the last few months, I ran into dozens of issues that I troubleshooted and couldn't get past

The developers just need to actually run through the steps that are documented to see they don't work

**Comment by P4T12ICK** [comment]
I work with Ubuntu with the Attack Range and don't run into these issues. Therefore it is very hard to troubleshoot when I don't know which causes the issue in your special case.

**Comment by configmanCooper** [comment]
Ok since I am getting actual responses I literally just created a new ubuntu and it still doesnt work
Went through the following commands
docker pull splunk/attack_range
docker run -it splunk/attack_range
aws configure
python attack_range.py configure

Configure wanted soar unpriv installer, so i download put it apps folder and gave it name

Then I go to build with the command 

python attack_range.py build

I get the error **vagrant executable cannot be found. vagrant failed to build**

I remember troubleshooting all this before. I tried getting vagrant. etc etc etc
I can try again. But if you follow the documented steps it does not work correctly
I am using the docker that "has all packages preinstalled" but that doesnt appear to be the case

**Comment by configmanCooper** [comment]
I then installed vagrant. Now it wants me to install virtualbox. I can do all this again but again, I want to stress, it IS NOT running correctly

**Comment by configmanCooper** [comment]
Now I've installed virtualbox, with apt-get install virtualbox . and it complains the installation is incomplete. These are all errors that I ran into last time.  This is on a fresh ubuntu 22.04

**Comment by P4T12ICK** [comment]
The instructions for Attack Range Local can be found in the docs:
https://attack-range.readthedocs.io/en/latest/Attack_Range_Local.html
Attack Range Local doesn't use the dockerfile.

**Comment by configmanCooper** [comment]
What?!

You literally said earlier in this thread: "Can you try to use the docker image which comes with all needed packages pre-installed?"

This whole thread started with me using the documentation for attack range local but you insisted on me using the docker file?

This is not closed.
