### ISSUE TITLE
Error when running local standalone on Ubuntu 22.04

### ISSUE THREAD

**Issue by configmanCooper** [splunk/attack_range#853]
Installed and dowloaded all requirements sucessfully on a standalone ubuntu 22.04
Get the following error upon build:
TASK [phantom : Copy Splunk SOAR to server] ************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [ar-phantom-attack-range-key-pair-ar]: FAILED! => {"changed": false, "msg": "Could not find or access '../../apps/soarinstall'\nSearched in:\n\t/home/cptadmin/attack_range/packer/ansible/roles/phantom/files/../../apps/soarinstall\n\t/home/cptadmin/attack_range/packer/ansible/roles/phantom/../../apps/soarinstall\n\t/home/cptadmin/attack_range/packer/ansible/roles/phantom/tasks/files/../../apps/soarinstall\n\t/home/cptadmin/attack_range/packer/ansible/roles/phantom/tasks/../../apps/soarinstall\n\t/home/cptadmin/attack_range/packer/ansible/files/../../apps/soarinstall\n\t/home/cptadmin/attack_range/packer/ansible/../../apps/soarinstall on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by gowthamarajr** [comment]
Please update the Repo once more with the latest "develop" branch and Try it. It should fix the issue since few of tasks being commented out in the latest branch, That includes "Copy Splunk SOAR to server".

Reference:
1. https://github.com/splunk/attack_range/blob/develop/packer/ansible/roles/phantom/tasks/install_phantom.yml
