### ISSUE TITLE
Install ACL errors out 

### ISSUE THREAD

**Issue by configmanCooper** [splunk/attack_range#854]
Was able to download everything for local install, and configure

However, upon build, I get this error
TASK [linux_common : Install Acl] **********************************************
fatal: [ar-splunk-attack-range-key-pair-ar]: FAILED! => {"cache_update_time": 1695518810, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'acl'' failed: E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/a/acl/acl_2.2.53-6_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/a/acl/acl_2.2.53-6_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/a/acl/acl_2.2.53-6_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  acl\n0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 37.8 kB of archives.\nAfter this operation, 197 kB of additional disk space will be used.\nErr:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 acl amd64 2.2.53-6\n  Temporary failure resolving 'us.archive.ubuntu.com'\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  acl", "0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.", "Need to get 37.8 kB of archives.", "After this operation, 197 kB of additional disk space will be used.", "Err:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 acl amd64 2.2.53-6", "  Temporary failure resolving 'us.archive.ubuntu.com'"]}

PLAY RECAP *********************************************************************
upgraded.", "Need to get 37.8 kB of archives.", "After this operation, 197 kB of additional disk space will be used.", "Err:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 acl amd64 2.2.53-6", "  Temporary failure resolving 'us.archive.ubuntu.com'"]}

PLAY RECAP *********************************************************************
ar-splunk-attack-range-key-pair-ar : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by configmanCooper** [comment]
Tried adding focal main and focal universe mirrors, still have same error

**Comment by gowthamarajr** [comment]
Could you please share your "attack_range.yml" ? So that i can take a look at it and help you.
