### ISSUE TITLE
Feature Request: Start / Stop / Rebuild Individual VMs

### ISSUE THREAD

**Issue by dluxtron** [splunk/attack_range#858]
Currently using AR as my lab environment and loving it! 

It would be awesome if I could just start up my Splunk server, to do some testing and power it down without starting up all the other devices. 

And similarly, being able to rebuild the windows hosts running a single line of code allowing me to preserve my Splunk instance would be super helpful.

**Comment by gowthamarajr** [comment]
Thanks for bring that up. 
We will do our best to get it done as soon as possible for you.

Really appreciate your ideas on making AR better!

**Comment by gowthamarajr** [comment]
Hey, @dluxtron 

We've successfully implemented the feature you requested for AWS in AR. It's now available for use. Please don't hesitate to test it out and reach out if you have any queries or need assistance. You can find the details here: https://github.com/splunk/attack_range/pull/870.
