### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Rudy-RENOUX** [splunk/attack_range#859]
Hello,

When I simulate an attack against a Windows server on a port other than 5985, I get the following error:

python attack_range.py simulate -e ART -t ar-win2016-server-member-1 -te T1053.005-1
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "ssl: HTTPSConnectionPool(host='127.0.0.1', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))", "unreachable": true}

My first server is a win2016 DC (port 5985): on this port, it works fine
My second server is a win2016 member of the domain (port 5986): ko

My environment is : 
python 3.9.17
vagrant 2.3.7

Has anyone come across this problem before ?

**Comment by Rudy-RENOUX** [comment]
To solve the issue, in attack_range/modules/ansible/atomic_red_team.yml, i had ansible_winrm_scheme: 'http'

![image](https://github.com/splunk/attack_range/assets/137391505/b0df824d-64c6-48d1-b374-ca6826c364fd)

**Comment by kyusan93** [comment]
It would be better to change from source.
modules/art_simulation_controller.py

**Comment by P4T12ICK** [comment]
This should be fixed and merged soon.
