### ISSUE TITLE
Chocolatey v1.4.0 failed to install

### ISSUE THREAD

**Issue by Zeik0s** [splunk/attack_range#860]
I don't have the error message at hand, but the configured old version of chocolatey failed to install. (I think it occured also because of the .NET 4.8 framework)

Setup on Azure, via prebuilt container-Image

**Comment by P4T12ICK** [comment]
I can't reproduce the issue. Maybe it was during the time in November. Sorry for the late reply.

**Comment by P4T12ICK** [comment]
This should be fixed. Thank you.
