### ISSUE TITLE
Terraform apply on Azure fails with timeout

### ISSUE THREAD

**Issue by Zeik0s** [splunk/attack_range#862]
After terraform planning the application of the build in azure failed with a timeout. 
Somehow the provider registration at the provider "Microsoft.Media" if i remember it right fails.

**Comment by P4T12ICK** [comment]
Do you have sufficient access rights on the subscription level of your Azure account?

**Comment by Zeik0s** [comment]
Yes i have, but i think this was in combination with an azure subscription where i don't have sufficient access to provision things. When changing the subscription in addition to the subscription ID in the wizard with `az account set --subscription <subscription-id>`, it worked. 

So i'm closing this issue since it didn't happen again.
