### ISSUE TITLE
Container build fails with ubuntu 22.04 base image

### ISSUE THREAD

**Issue by Zeik0s** [splunk/attack_range#864]
Successful build with the provided Dockerfile is possible on 20.04, but with 22.04 the build fails at poetry dependencies install with ansible-core. 
Also the poetry install seemed to have changed to the script on `https://install.python-poetry.org/`.

<details><summary>Host info (neofetch)</summary>
<p>

OS: Ubuntu 22.04.3 LTS x86_64
Host: Virtual Machine Hyper-V UEFI Release v4.1
Kernel: 6.2.0-1016-azure
Uptime: 9 days, 2 hours, 32 mins
Packages: 765 (dpkg), 4 (snap)
Shell: bash 5.1.16
Resolution: 1024x768
Terminal: /dev/pts/0
CPU: AMD EPYC 7763 (2) @ 3.243GHz
Memory: 538MiB / 3853MiB

</p>
</details>

**Comment by Zeik0s** [comment]
I went back to 20.04, modified it and introduced some improvements: c77f392

**Comment by P4T12ICK** [comment]
I can't reproduce your issue. I have no problems building the docker images as it is. What host os do you use?

**Comment by Zeik0s** [comment]
@P4T12ICK see my neofetch addition above - was Ubuntu 22.04.3 LTS x86_64

**Comment by Zeik0s** [comment]
Strange enough, i can't reproduce it as well, so i'm closing this as it seems as a temporary issue.
