### ISSUE TITLE
Attack Range Attempting to Build in Wrong Subscription

### ISSUE THREAD

**Issue by GabrielSaul** [splunk/attack_range#866]
When trying to build from attack_range.py, I get an error for not having write access due to the fact that it is trying to build in the wrong subscription.

I have specified the target subscription with the "configure" command, and it has been written to the attack_range.yml file. I have verified all other details.

I have noticed that when building, it selects the top subscription alphabetically by subscription ID in my subscription list. Could this be an issue with the "known after apply" placeholder? Otherwise, I have no idea.

**Comment by Zeik0s** [comment]
If you are referring to Azure, i stumbled upon this as well, you have to set the subscription manually using the az command:
az account set --subscription <name or id>
