### ISSUE TITLE
Atomic Red Team simulation issue

### ISSUE THREAD

**Issue by tar1127** [splunk/attack_range#868]
when simulating a Atomic red team `python attack_range.py simulate -e ART -te T1003.002 -t <windows DC>`. no logs present in splunk for this technique. 

when running ART simulate the output shows  

TASK [atomic_red_team : debug] *************************************************
ok: [IP_Address] => {
    "output_art.stdout_lines": [
        "PathToAtomicsFolder = ",
        "",
        "Found 0 atomic tests applicable to windows platform for Technique "
    ]
}

**Comment by P4T12ICK** [comment]
Hello @tar1127, I was not able to reproduce your issue. I was just testing it with the same command and it was working for me. Can you check again?
