### ISSUE TITLE
Fatal error by install contentctl

### ISSUE THREAD

**Issue by t0mg1t** [splunk/attack_range#875]
I'm facing in the following error by a local installation:

fatal: [ar-linux-attack-range-key-pair-ar-0]: FAILED! => {"msg": "The conditional check '(use_prebuilt_images_with_packer == \"0\") and (install_contentctl == \"0\")' failed. The error was: error while evaluating conditional ((use_prebuilt_images_with_packer == \"0\") and (install_contentctl == \"0\")): 'install_contentctl' is undefined\n\nThe error appears to be in '/home/...../git_tools/attack_range/packer/ansible/roles/linux_universal_forwarder/tasks/install_universal_forwarder.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: add splunk group\n  ^ here\n"}

Can anybody help? Many thanks!

**Comment by ljstella** [comment]
Howdy @t0mg1t -

Can you confirm when you pulled the docker image or pulled this repo? We shipped a fix yesterday that should address this.

**Comment by t0mg1t** [comment]
Hi @ljstella
Thanks for your help
I pulled this repo today.

**Comment by ljstella** [comment]
Under the `general` section of your attack_range.yml config file, you can add 
```yml
install_contentctl: "0"
```

which should clean this up while we work on a more permanent fix.
