### ISSUE TITLE
C:\Temp is missing by CB Cloud installation

### ISSUE THREAD

**Issue by t0mg1t** [splunk/attack_range#877]
When i try to install the Carbon Black Cloud Sensor, the following error occurs:

[nlGIPlpZdTh5oTssCWn](fatal: [ar-win-attack-range-key-pair-ar-0]: FAILED! => {"changed": true, "checksum": "150b873cd32aa24516fd36c2dee72075b24a0331", "dest": "C:\\Temp\\WindowsSensor.msi", "msg": "failed to copy file /home/....../git_tools/attack_range/apps/installer_vista_win7_win8-64-4.0.0.1292.msi: Destination directory 'C:\\Temp' does not exist", "operation": "file_copy", "original_basename": "installer_vista_win7_win8-64-4.0.0.1292.msi", "size": 78417920, "src": "../../apps/installer_vista_win7_win8-64-4.0.0.1292.msi"})

Maybe C:\Temp can be created in the playbook or changed to c:\tmp which already exists.

**Comment by P4T12ICK** [comment]
I'm not able to reproduce your issue. I deployed Attack Range to AWS with Carbon Black Cloud Sensor. Everything is working. What was your setup?
