### ISSUE TITLE
Local VMs cannot be stopped

### ISSUE THREAD

**Issue by t0mg1t** [splunk/attack_range#878]
Hey there

When I try to stop the local attack range with `python attack_range.py stop`, the following error occurs:

Traceback (most recent call last):
  File "/home/....../git_tools/attack_range/attack_range.py", line 235, in <module>
    main(sys.argv[1:])
  File "/home/......./git_tools/attack_range/attack_range.py", line 231, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/home/......./git_tools/attack_range/attack_range.py", line 93, in stop
    controller.stop(instance_ids)
TypeError: VagrantController.stop() takes 1 positional argument but 2 were given

**Comment by roadside-picnicx** [comment]
Im just adding that i have the same problem, both stop and run commands return errors like the one described above.

**Comment by TimWinkler** [comment]
hi, goto line 93 in attack_range.py and change from `controller.stop(instance_ids)` to `controller.stop()`

**Comment by TimWinkler** [comment]
I think the issue is that if the instance_ids are "empty" it is still set to the Datatype "None" (which is not "null/empty") and 
then passed as 2nd argument to the VagrantController

**Comment by rangerrkm** [comment]
same issue here

**Comment by P4T12ICK** [comment]
Thank you for reporting it. Yes it was a feature developed for the Attack Range in AWS and Azure but we forgot to add the logic to vagrant. Fix will be pushed soon.
