### ISSUE TITLE
Vagrant system path issue- not new issue just Question

### ISSUE THREAD

**Issue by venomspl** [splunk/attack_range#880]
Trying to run build but erroring out with error: 
What is the path, as the .deb is installed under attack_range directory and present. 

The Vagrant executable cannot be found. Please check if it is in the system path.
2024-02-11 21:44:59,991 - INFO - attack_range - [action] > build

2024-02-11 21:45:00,017 - ERROR - attack_range - vagrant failed to build

**Comment by P4T12ICK** [comment]
We use the module https://pypi.org/project/python-vagrant/ which is a thin wrapper around the vagrand command line executable. This means, that you need to install vagrant that you can call the vagrant command from anywhere in your command line.
