### ISSUE TITLE
Install Local Issue

### ISSUE THREAD

**Issue by joshsolman** [splunk/attack_range#892]
python attack_range.py build
/opt/attack_range/attack_range.py:17: SyntaxWarning: invalid escape sequence '\^'
  print("""

                              __
                            .d$$b
                          .' TO$;\
                         /  : TP._;
                        / _.;  :Tb|
                       /   /   ;j$j
                   _.-"       d$$$$
                 .' ..       d$$$$;
                /  /P'      d$$$$P. |\
               /   "      .d$$$P' |\^"l
             .'           `T$P^"""""  :
         ._.'      _.'                ;
      `-.-".-'-' ._.       _.-"    .-"
    `.-" _____  ._              .-"
   -(.g$$$$$$$b.              .'
     ""^^T$$$P^)            .(:
       _/  -"  /.'         /:/;
    ._.'-'`-'  ")/         /;/;
 `-.-"..--""   " /         /  ;
.-" ..--""        -'          :
..--""--.-"         (\      .-(\
  ..--""              `-\(\/;`
    _.                      :
                            ;`-
                           :\
                           ;  bug

By: Splunk Threat Research Team [STRT] - research@splunk.com

2024-05-10 11:42:23,050 - INFO - attack_range - [action] > build

Traceback (most recent call last):
  File "/opt/attack_range/attack_range.py", line 235, in <module>
    main(sys.argv[1:])
  File "/opt/attack_range/attack_range.py", line 231, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/opt/attack_range/attack_range.py", line 84, in build
    controller.build()
  File "/opt/attack_range/modules/vagrant_controller.py", line 49, in build
    v1 = vagrant.Vagrant('vagrant/', quiet_stdout=False, quiet_stderr=False)
         ^^^^^^^^^^^^^^^
AttributeError: module 'vagrant' has no attribute 'Vagrant'
(attack-range-py3.12) root@attackrange:/opt/attack_range#

**Comment by P4T12ICK** [comment]
It looks like that you don't have vagrant installed. Attack Range local needs vagrant.
