### ISSUE TITLE
Docutils dependency not found

### ISSUE THREAD

**Issue by Thomas-McKanna** [splunk/attack_range#894]
I followed the installation instructions at https://attack-range.readthedocs.io/en/latest/Attack_Range_AWS.html for both macOS and Linux. The Mac has an Apple Silicon chip, and the Linux machine runs Ubuntu 22.04.

In both cases, running poetry install results in the following error:

```
Updating dependencies
Resolving dependencies... (1.8s)

Package docutils (0.21.post1) not found.
```

I thought the issue might be related to my Python version (3.11), so I installed Python 3.8 (as specified in the Linux installation instructions), but the same error occurred.

**Comment by waja1n0z** [comment]
I encountered the same issue trying to install on Ubuntu 24.04. Will keep digging to find a workaound

**Comment by yaleman** [comment]
There's a poetry bug listed for it here: https://github.com/python-poetry/poetry/issues/9293

Might just need to bump the docutils version to avoid the yanked package?

**Comment by 0xtamsee1** [comment]
Adding `https://pypi.org/simple/` as the source to pyproject.toml worked as a workaround for me
```
[[tool.poetry.source]]
name = "pypi-public"
url = "https://pypi.org/simple/"
```

**Comment by P4T12ICK** [comment]
this is fixed. Thank you.
