### ISSUE TITLE
Missing Packer plugins required to create AMIs for AWS deployment

### ISSUE THREAD

**Issue by ajpc500** [splunk/attack_range#895]
Using the docker image to build AMIs, packer produces errors for missing `ansible` and `amazon` plugins.

```
Error: Unknown provisioner type "ansible"

on packer/splunk_server/splunk_aws.pkr.hcl line 64:
(source code not available)

The provisioner ansible is unknown by Packer, and is likely part of a plugin
that is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.

https://developer.hashicorp.com/packer/integrations?filter=ansible
```

As per [here](https://developer.hashicorp.com/packer/integrations/hashicorp/ansible), this can be fixed with the below commands:

```
packer plugins install github.com/hashicorp/ansible
packer plugins install github.com/hashicorp/amazon
```

It looks like this can also be added to Packer configuration files, which might be a better fix for this issue as additional dependencies aren't installed for users that are using local or Azure deployments?

**Comment by P4T12ICK** [comment]
I would recommend to not use packer. Our plan is to remove packer in a future release.
