### ISSUE TITLE
Attack Range 3.0 local build  vagrant fails

### ISSUE THREAD

**Issue by brucechimusoro** [splunk/attack_range#896]
Failing to Build Attack Range 3.0 on Linux Mint 21.2  (ubuntu codename jammy)

I have been following installation instructions on https://attack-range.readthedocs.io/en/latest/Attack_Range_Local.html  for a attack range local install on linux

Attack range fails during the build process  (python attack_range build)

<--output cut-->

ASK [phantom : Creates directory] *********************************************
changed: [ar-phantom-attack-range-key-pair-ar]

TASK [phantom : Copy Splunk SOAR to server] ************************************
[WARNING]: Error deleting remote temporary files (rc: 1, stderr: Could not
chdir to home directory /home/vagrant: Permission denied bash:
/home/vagrant/.bashrc: Permission denied })
changed: [ar-phantom-attack-range-key-pair-ar]

TASK [phantom : prepare phantom install script without apps] *******************
fatal: [ar-phantom-attack-range-key-pair-ar]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /home/vagrant/.ansible/tmp `\"&& mkdir \"` echo /home/vagrant/.ansible/tmp/ansible-tmp-1716446324.3823583-133581-59531706665728 `\" && echo ansible-tmp-1716446324.3823583-133581-59531706665728=\"` echo /home/vagrant/.ansible/tmp/ansible-tmp-1716446324.3823583-133581-59531706665728 `\" ), exited with result 1", "unreachable": true}

PLAY RECAP *********************************************************************
ar-phantom-attack-range-key-pair-ar : ok=2 changed=2 unreachable=1 failed=0 skipped=6 rescued=0 ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
2024-05-23 08:38:44,768 - ERROR - attack_range - vagrant failed to build

**Comment by P4T12ICK** [comment]
I was not able to reproduce this issue. Do you still have this issue? Sorry for the late reply.
