### ISSUE TITLE
[Feature Request - Adversary and Micro Emulation Plans]

### ISSUE THREAD

**Issue by 0xtamsee1** [splunk/attack_range#899]
Requesting for feature for attack_range : Can we have Adversary emulation plans and Micro emulation plans from MITRE's [Center for Threat-Informed Defense (Center)](https://github.com/center-for-threat-informed-defense/adversary_emulation_library)

I would really like to have Micro emulations plans of Active Directory Enumeration, and other in attack_range. Please let me know if this is a good idea.

**Comment by P4T12ICK** [comment]
Yes I think this is a good idea but I think it would be better to have it as a separate project and then it could be integrated into Attack Range.
