### ISSUE TITLE
Ansible playbook used by packer to create the linux image fails the exeuction due to an error on the linux_osquery task.

### ISSUE THREAD

**Issue by zatarra** [splunk/attack_range#906]
Whenever Packer tries to build the linux image it fails with  the following error: 
<img width="1056" alt="image" src="https://github.com/splunk/attack_range/assets/4305862/b175ee6f-b709-4df2-967b-317a27cbb6e3">

Any idea how to fix it?

**Comment by P4T12ICK** [comment]
I would recommend to not use packer. Our plan is to remove packer in a future release.
