### ISSUE TITLE
install with docker image splunk/attack_range fails.

### ISSUE THREAD

**Issue by cb13579** [splunk/attack_range#916]
The Docker Standalone install within the provided docker image splunk/attack_range fails.

Until here:
`[Host computer]
$ docker pull splunk/attack_range
$ docker run -it splunk/attack_range

[Docker container]
# aws configure ( or az login )`

it works, but the configure step within the container is missing the module "ansible_runner".  Via pip it is not installable.

`root@425f16767493:/attack_range# python attack_range.py configuration
Traceback (most recent call last):
  File "/attack_range/attack_range.py", line 6, in <module>
    from modules.aws_controller import AwsController
  File "/attack_range/modules/aws_controller.py", line 2, in <module>
    import ansible_runner
ModuleNotFoundError: No module named 'ansible_runner'
root@425f16767493:/attack_range# pip install ansible-runner
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/ansible-runner/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/ansible-runner/
`

**Comment by P4T12ICK** [comment]
It should be fixed now. Thank you.
