### ISSUE TITLE
Error: remote-exec provisioner error

### ISSUE THREAD

**Issue by wenglokc** [splunk/attack_range#956]
OS: Kali linux

I am having the following error after trying to build the attack_range. I could see both windows server and splunk instance being created and I can rdp and ssh to them. However I am unable to access the web gui for splunk and guacamole on port 8000 and 8080 respectively.

![error](https://github.com/user-attachments/assets/bfb912a5-791b-47ed-8685-d1ccf6c1df93)

I've check some previous issue here https://github.com/splunk/attack_range/issues/737 that was similar to my error but I have verified that my ssh key generated was using rsa-2048.

**Comment by splunk-james** [comment]
What is the config for your pub and priv SSH key? Are you using an exisiting key or generating a new one each time you build? If you are using an existing key have you set permissions correctly on the private key file?

**Comment by wenglokc** [comment]
I generated a new one when I ran python attack_range.py configure

**Comment by splunk-james** [comment]
Can you share your attack_range.yml file or at least the sections relating to the SSH configs?

**Comment by wenglokc** [comment]
are you talking about this section?

![image](https://github.com/user-attachments/assets/83c6c0c1-0cd7-4b1c-bf3e-e84e3a468a00)

**Comment by splunk-james** [comment]
What are the permissions on that private key file and there should also be another section for the key name in aws, does
That match?

**Comment by wenglokc** [comment]
Are you referring to this?

![image](https://github.com/user-attachments/assets/98eb16b5-6643-4373-a639-2401d2c53ea3)

**Comment by splunk-james** [comment]
That looks like the attack range default yaml file and not the one generated by running 'python attack_range.py configure'

**Comment by wenglokc** [comment]
oh you meant this 
![image](https://github.com/user-attachments/assets/7ee9e1ef-a911-4912-9fd0-24e8655ed5c9)
