### ISSUE TITLE
create attack_range.yml configuration parameter for Cisco AMP API FQDN

### ISSUE THREAD

**Issue by splunk-james** [splunk/attack_range#961]
Cisco Secure Endpoint (AMP) uses different API FQDNs depending on the cloud region:

Public Cloud Regions AMP for Endpoints | URL endpoint | port | protocol
North America | api.amp.cisco.com, export-streaming.amp.cisco.com | 443 | TCP
Europe | api.eu.amp.cisco.com, export-streaming.eu.amp.cisco.com | 443 | TCP
Asia Pacific | api.apjc.amp.cisco.com, export-streaming.apjc.amp.cisco.com | 443 | TCP

Recommended that option to configure this value in the attack_range.yml file is provided rather than directly editing the tasks/templates for cisco_secure_endpoint_logs

**Comment by P4T12ICK** [comment]
this is fixed
