### ISSUE TITLE
Kali AMI no longer exists

### ISSUE THREAD

**Issue by shubs123** [splunk/attack_range#964]
The resources.tf file for the Kali Linux AMI has a filter like this - 

filter {
      name   = "name"
      values = ["kali-last-snapshot-amd64-2023*"]
}

There is no available AMI with the following name because 2023 is hardcoded in it.

Can this config please be updated to something like this -

filter {
      name   = "name"
      values = ["kali-last-snapshot-amd64-*"]
}

**Comment by P4T12ICK** [comment]
Thank you for improving it. I will merge it in.
