### ISSUE TITLE
Provide feature-parity across Azure/Local builds

### ISSUE THREAD

**Issue by rcegan** [splunk/attack_range#999]
Hi team,

Really loving Splunk Attack Range. As a local & Azure user, it would be really great if some of the newer options (zeek, Kali, etc.) could be ported across to Azure and Local builds too. Thanks!

**Comment by P4T12ICK** [comment]
Hello, happy that you like Attack Range. We would love to have all features on the different Attack Range provider (AWS, Azure. local).
Sometimes it is not possible of technical reasons e.g that there is no kali image on Azure. Sometimes we just don't have enough development time to build all features for all providers. Contributions are welcomed to help us make Attack Range even better.
